### ISSUE TITLE
Prevent snapshot dependencies when releasing

### ISSUE THREAD

**Issue by uguy** [aleksandr-m/gitflow-maven-plugin#10]
Hi there,
If you find some time, could you add some checks when releasing to prevent snapshot dependencies ? Currently, the project version itself is move to release version, but there is not check on its deps, so you can easily end ups with a release that rely on snapshots.

Thanks anyway

**Comment by aleksandr-m** [comment]
Arghhh... github auto closed this one.

@uguy  Can you clone, build and test it?

**Comment by uguy** [comment]
Thanks, I'll give it a try as soon as I can !

**Comment by aleksandr-m** [comment]
@uguy Version `1.2.2` is released.
