### ISSUE TITLE
Enhancement Request -- Release branch manipulation

### ISSUE THREAD

**Issue by Steve973** [aleksandr-m/gitflow-maven-plugin#101]
If I am cutting a release candidate through release:start, and my release branch is created and the first release candidate is tagged, I would like to be able to tag the next release candidate after some fixes have been made and committed against the release branch.  Currently, I'm doing this manually (with Jenkins) via a "git tag" command after checking out the release branch.  Could you add more release goals to handle this situation, since it's a valid stage in gitflow?  Some options that might be helpful are:

- Allow for the version to remain the same.  For example, the version on the release candidate branch might be 1.2.0-RC, and users might not need specific release candidate versions.
- Allow for specific release candidate versions.  For example, the first deployed release candidate might be 1.2.0-RC1, so the "development" version on the release candidate branch would be incremented to 1.2.0-RC2.

As I was saying, this can definitely be achieved somewhat manually, but I think it would be a good feature to include in your plugin.  Thoughts?

**Comment by aleksandr-m** [comment]
@Steve973 Something like [release-update](https://github.com/aleksandr-m/gitflow-maven-plugin/commit/3a085045ff36b3cfb2360c6851621c60b7158ec2)? Take a look. Try it out.

**Comment by Steve973** [comment]
@aleksandr-m Thank you.  That looks like it will probably work.  However, I'm on an enclave, and I can't try it out in my project at work, but I will see if I can find a moment to try it at home.  I'd close this ticket but I don't seem to have permissions to do that.
