### ISSUE TITLE
releaseRebase=true   => [ERROR] hint: Updates were rejected because a pushed branch tip is behind its remote

### ISSUE THREAD

**Issue by DanielCharczynski** [aleksandr-m/gitflow-maven-plugin#102]
When we use releaseRebase=true there is following problem with pushing master branch

**mvn gitflow:release -DskipTestProject=true -DreleaseRebase=true**

[INFO] --- gitflow-maven-plugin:1.9.0:release (default-cli) @ okapi ---
[INFO] Checking for uncommitted changes.
[INFO] Fetching remote branch 'origin develop'.
[WARNING] There were some problems fetching remote branch 'origin develop'. You can turn off remote branch fetching by setting the 'fetchRemote' parameter to false.
[INFO] Fetching remote branch 'origin master'.
[INFO] Comparing local branch 'master' with remote 'origin/master'.
[INFO] Checking out 'develop' branch.
[INFO] Checking for SNAPSHOT versions in dependencies.
What is release version? [0.3.2]:
[INFO] Version is blank. Using default version.
[INFO] Updating version(s) to '0.3.2'.
[INFO] Committing changes.
[INFO] Checking out 'master' branch.
[INFO] Rebasing 'develop' branch.
[INFO] Creating 'okapi-0.3.2' tag.
[INFO] Checking out 'develop' branch.
[INFO] Updating version(s) to '0.3.3-SNAPSHOT'.
[INFO] Committing changes.
[INFO] Pushing 'master' branch to 'origin'.

....

[ERROR] Failed to execute goal com.amashchenko.maven.plugin:gitflow-maven-plugin:1.9.0:release (default-cli) on project okapi: release: To https://git.pl.ing-ad/DA/okapi.git
[ERROR] * [new tag]           okapi-0.3.2 -> okapi-0.3.2
[ERROR] ! [rejected]          master -> master (non-fast-forward)
[ERROR] error: failed to push some refs to 'https://gq28bl@git.pl.ing-ad/DA/okapi.git'
[ERROR] hint: Updates were rejected because a pushed branch tip is behind its remote
[ERROR] hint: counterpart. Check out this branch and integrate the remote changes
[ERROR] hint: (e.g. 'git pull ...') before pushing again.
[ERROR] hint: See the 'Note about fast-forwards' in 'git push --help' for details.
[ERROR] -> [Help 1]

**Comment by aleksandr-m** [comment]
Do you want a force push option?

If you're using rebase then you can set `pushRemote` to `false` and force push later manually.

**Comment by lrkwz** [comment]
> Do you want a force push option?

A pull *before* pushing will resolve the problem.
