### ISSUE TITLE
New Feature for Kubernetes (Helm)

### ISSUE THREAD

**Issue by marandalucas** [aleksandr-m/gitflow-maven-plugin#103]
We are using your plugin for quite some time and we are very happy because it's working very well.

 But now we have new needs for projects deployed in kubernetes and we would need that in addition to pom.xml modify the file chart.yaml (With the same version of pom).
Do you think it would be possible to synchronize the two files?
Thanks for a great work

**Comment by aleksandr-m** [comment]
Why not to use [Maven's resource filtering](https://maven.apache.org/plugins/maven-resources-plugin/examples/filter.html)?
