### ISSUE TITLE
[Question] How to configure Jenkins

### ISSUE THREAD

**Issue by willsilvano** [aleksandr-m/gitflow-maven-plugin#104]
Hello friends!

I'm testing your plugin and I have a question.

How to configure Jenkins to construct and perform maven release with this plugin?

![image](https://user-images.githubusercontent.com/7406991/38829583-ebc17f04-418f-11e8-8ded-b8f60fcb2926.png)

Above is my current setting.

Sometimes I will also need to increase the version of minor, which I do today as print below.

![image](https://user-images.githubusercontent.com/7406991/38829441-6916a71e-418f-11e8-8d56-3c5e4312d48a.png)

Can you help me?

Thanks!

**Comment by aleksandr-m** [comment]
What is the problem? Read [Non-interactive Release](https://github.com/aleksandr-m/gitflow-maven-plugin#non-interactive-release).

**Comment by aleksandr-m** [comment]
@willsilvano Can we close this?
