### ISSUE TITLE
Bugfixes on release-branch and incrementing of patch-version

### ISSUE THREAD

**Issue by JorgenRingen** [aleksandr-m/gitflow-maven-plugin#106]
Hi, thanks for a great plugin!

We have the following versioning scheme: 1.0.0-SNAPSHOT = develop
When we create a new release-branch of develop we increment develop to 1.1.0-SNAPSHOT and the release-branch is 1.0.0. This works excellent in the plugin by using release-start.

However, we want to be able to do bugfixes on the release-branch in case 1.0.0 failed a step in our deployment pipeline (performance testing, manual testing, etc). A bugfix on the release-branch would increment the patch-version to 1.0.1, and 1.0.1 would be deployed to nexus and get verified in the deployment pipeline. There can be several patches on the release-branch that increments the patch-version.

What is the best way to achieve this? Is it possible to release multiple times from the same release-branch with different version numbers for release? Develop version should not be affected by this.

I guess we can increment the patch-version manually, but just wanted to check if this is integrated in the plugin somehow?

**Comment by aleksandr-m** [comment]
Hi,

You can use `hotfix` goals.

Also take a look at [release-update](https://github.com/aleksandr-m/gitflow-maven-plugin/commit/3a085045ff36b3cfb2360c6851621c60b7158ec2), it is still wip though.

**Comment by ismarslomic** [comment]
Ok, thanks! I thought `hotfix` was mainly used for fixes in `master`-branch, and `bugfix` for fixes in `develop` and release branches.

**Comment by aleksandr-m** [comment]
See [`version-update` goal](https://github.com/aleksandr-m/gitflow-maven-plugin/blob/master/src/main/java/com/amashchenko/maven/plugin/gitflow/GitFlowVersionUpdateMojo.java).
