### ISSUE TITLE
Option to not merge to master for release-finish

### ISSUE THREAD

**Issue by ismarslomic** [aleksandr-m/gitflow-maven-plugin#107]
Hi, thanks for great plugin!

Is it possible to do the merge, for goal `release-finish`, only to **development** (`develop`), but not **production** (`master`)? We don´t want to merge an `release` to `master` branch which is not yet tested (performance test, manual tests, etc) in an test environment. In addition we do not allow push to master without Pull Requests. 

Since `release-finish` goal automatically merge to develop and master, after creating an release, it is difficult to achieve this. 

Any suggestions?

**Comment by hypery2k** [comment]
having the same issue here. Any new thoughts here?

**Comment by aleksandr-m** [comment]
@hypery2k Do you really need a release branch? Feature/support/hotfix/some other branch maybe?

BTW the `hotfix-finish` goal has `skipMergeProdBranch` option since 1.12.0.

**Comment by hypery2k** [comment]
I'm using the option for now, so from my side no need for the issue as it can be resolved with the help of the option

**Comment by aleksandr-m** [comment]
Duplicate of #74, which is resolved by now.
