### ISSUE TITLE
Longer lived release branches

### ISSUE THREAD

**Issue by mhvelplund** [aleksandr-m/gitflow-maven-plugin#108]
Is there a way have the release branch live for longer than one release tag? Suppose I want to create a release branch from the development branch to allow me to keep working in the development branch on the next version.

I want to run the plugin, making the update in my release branch, and tagging and merging both to master and develop (the latter is optional). 

Then, if I find a bug, I want to fix it in the release branch and run the the plugin again to create a new tag in the master (and optionally in develop). I don't want to pulle changes from develop again.

Is there a way to do this?

**Comment by aleksandr-m** [comment]
There are some options you can explore:

1. hotfix
2. [support-branches](http://gitversion.readthedocs.io/en/latest/git-branching-strategies/gitflow-examples/#support-branches)
3. `sameBranchName` parameter in release goal

**Comment by mhvelplund** [comment]
Thanks! I worked out version 3, but I’ll look into the others too.
