### ISSUE TITLE
tags are not pushed

### ISSUE THREAD

**Issue by DVanderstoken** [aleksandr-m/gitflow-maven-plugin#11]
released tags are not pushed to git repository.

pom file :
`<plugin>
  <groupId>com.amashchenko.maven.plugin</groupId>
  <artifactId>gitflow-maven-plugin</artifactId>
  <version>1.2.2</version>
  <configuration>
  
    <installProject>false</installProject>
    <verbose>false</verbose>
    <gitFlowConfig>
      <versionTagPrefix>${project.artifactId}-</versionTagPrefix>
    </gitFlowConfig>
  </configuration>
</plugin>`

I can see them trough git tag command :
`eureka-0.0.6
eureka-0.0.7
`
But not in gitlab repository.

**Comment by aleksandr-m** [comment]
Currently this plugin doesn't do `git push` at all. To push tags refer to [git-push](https://git-scm.com/docs/git-push) documentation and to this SO question - [Push git commits & tags simultaneously](http://stackoverflow.com/q/3745135/1700321).

**Comment by DVanderstoken** [comment]
Many thanks for the reply.
