### ISSUE TITLE
command mvn not found

### ISSUE THREAD

**Issue by wumpz** [aleksandr-m/gitflow-maven-plugin#110]
I start the maven goals via IDE (Netbeans). Somehow I was not able to add maven/bin to my path and make Netbeans use it. 

So I found, that a valid setting for me was 

`<mvnExecutable>${M2_HOME}/bin/mvn</mvnExecutable>`

to get the plugin running.

Maybe this could be a fallback to run / find **mvn**.

**Comment by DRoppelt** [comment]
Seems like 'mvn' is not in your PATH then?

> Maven and Git executables are assumed to be in the PATH, if executables are not available in the PATH or you want to use different version use mvnExecutable and gitExecutable parameters

When you open "cmd.exe", can you execute "mvn --version", if no, this is your issue.

**Comment by wumpz** [comment]
Mvn is part of my windows path. From cli everything works fine. But I was somehow not able to get Netbeabs work with it. But m2_home could be used. See my proposal.

**Comment by aleksandr-m** [comment]
You can always set `mvnExecutable`.

Don't see a clear way to implement fallback mechanism here. PR-s are welcome.

**Comment by wumpz** [comment]
How to configure cross platform win and Linux? My suggestion worked out of the box.

**Comment by aleksandr-m** [comment]
@wumpz By your suggestion you mean what exactly?

**Comment by wumpz** [comment]
My suggestion was to set this:

`<mvnExecutable>${M2_HOME}/bin/mvn</mvnExecutable>`

by default.

**Comment by aleksandr-m** [comment]
`M2_HOME` is not required for maven to work. Using it as a default for `mvnExecutable` is not good.

**Comment by raehalme** [comment]
I think it's pretty common to have `mvn` on your `PATH` so let's stick to the current behavior. You can always make modifications that better fit your environment in your (parent) POM.

**Comment by wumpz** [comment]
Using Jenkins build with docker nodes I never specified a path. But I think the maven plugin of Jenkins does specify this m2 environment variable. That's why my proposal works.

**Comment by aleksandr-m** [comment]
> without setting up environment variables

You don't have to. All you need is to put maven in the path, which is the most natural thing to do.

**Comment by wumpz** [comment]
Which did not work for me, as I mentioned.
