### ISSUE TITLE
How to use SSH instead of HTTPS

### ISSUE THREAD

**Issue by julienBaleizao** [aleksandr-m/gitflow-maven-plugin#112]
Hi,
I am using your plugin in a Gtilab CI pipeline that is releasing my project.
Everything is working fine until the push process.

I get the following error:
_unable to access 'https://gitlab-ci-token:xxxxxxxxxxxxxxxxxxxx@XXXXXXX/XXXXXX/XXXXXX.git/': The requested URL returned error: 403._

It is using HTTPS instead of SSH.
**How can I force the plugin to use SSH ?**
**What is the 'gitlab-ci-token' variable ?**

By the way I have configured my 'SCM' pom section to use SSH.

Thank you.

**Comment by aleksandr-m** [comment]
Remote comes from project's git config. Have you added remote ssh?

**Comment by aleksandr-m** [comment]
@julienBaleizao Have you tried to add remote with ssh instead of https?

**Comment by limkinZero** [comment]
@julienBaleizao Did you resolve the issue? I have the same problem in my gitlab-ci pipeline when I try to generate the gitflow:release.
