### ISSUE TITLE
gitflow:release-finish not able to delete release branch

### ISSUE THREAD

**Issue by Wavemaster111188** [aleksandr-m/gitflow-maven-plugin#114]
### Problem
When I tried to execute gitflow:release-finish (with --batch-mode) and I did some changes on the release branch, maven was not able to delete the release branch.

See the log:
```
[INFO] Creating 'mtx-7.2.4.0' tag.
[INFO] Checking out 'develop' branch.
Your branch is up to date with 'origin/develop'.
[INFO] Merging (--no-ff) 'release-7.2.4.0' branch.
Merge made by the 'recursive' strategy.
 .../main/java/de/db/mtx/service/xxx.java    | 3 +++
 1 file changed, 3 insertions(+)
[INFO] Deleting 'release-7.2.4.0' branch.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] xxxxxxxxxxxxx ..................... FAILURE [02:21 min]
[INFO] xxx ............................... SKIPPED
[INFO] xxxxxxxxxxxxx ..................... SKIPPED
[INFO] xxxxxxxxxxxxxx .................... SKIPPED
[INFO] xxxxxxxxxxxxxxxxxxxxxx ............ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:23 min
[INFO] Finished at: 2018-07-17T18:08:16+02:00
[INFO] Final Memory: 31M/434M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.amashchenko.maven.plugin:gitflow-maven-plugin:1.9.0:release-finish (default-cli) on project mtx: release-finish: warning: not deleting branch 'release-7.2.4.0' that is not yet merged to 'refs/remotes/origin/release-7.2.4.0', even though it is merged to HEAD.
[ERROR] error: The branch 'release-7.2.4.0' is not fully merged.
[ERROR] If you are sure you want to delete it, run 'git branch -D release-7.2.4.0'.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

D:\xxx\server>

```
### Reason
It seems the branch ist not merged to the remote origin one before deleting it.

Interestingly, the remote branch is marked as merged in `develop `and `master`

When the release branch has no commits, it's deleted as expected.

### Solution
I don't exactly know, what's the best approach here is.

Maybe an additional parameter for using `gitBranchDeleteForce` (like `featureSquash`)?  
Maybe syncing the remote and local branches?

### Is there a workaround? 
A workaround would be much appreciated!

**Comment by Wavemaster111188** [comment]
### My current workaround
For this issue, my workaround is to set `<keepBranch>` to `true` and then execute 
```
git push origin -d `git branch | grep -E 'release-*'` && git branch -D `git branch | grep -E 'release*'`
```
right after the `gitflow:release-finish`.

It first gets the name of the release branch (there can only be one) and deletes the release branch in origin. After that, it gets the name again and force deletes the branch locally.

**Comment by aleksandr-m** [comment]
Why not to push changes before running release-finish?

As for the solution: remote operations and deleting local branch can be swapped. I.e. delete remote branch then local.

**Comment by Wavemaster111188** [comment]
My bad!

If I push the branch before trying to finish the release, it works like a charm! :100: 

Please close this issue.

**Comment by aleksandr-m** [comment]
@Wavemaster111188 I've swapped remote and local delete branch operations. This way it should work w/o pushing release branch that is going to be deleted anyway. :)

**Comment by testphreak** [comment]
@aleksandr-m thank you for the fix! When can we expect it to be released?

**Comment by aleksandr-m** [comment]
@Wavemaster111188 @testphreak `1.10.0` is released. Enjoy!
