### ISSUE TITLE
use of processAllModules flag doesn't work for mvn modules

### ISSUE THREAD

**Issue by Zegveld** [aleksandr-m/gitflow-maven-plugin#116]
We're trying to use your plugin for both maven and tycho builds.
The cause appears to be that the versions-maven-plugin is set to 2.1 in the code which doesn't support this property yet.

The pull request below removes the version '2.1' entirely, allowing support for future versions.
see pullrequest https://github.com/aleksandr-m/gitflow-maven-plugin/pull/115

**Comment by aleksandr-m** [comment]
Merged. Thanks.

**Comment by aleksandr-m** [comment]
@Zegveld Released.

**Comment by Zegveld** [comment]
Thanks :+1:
