### ISSUE TITLE
Proposal: For release-finish goal merge the new version tag in master branch back into development branch and push to origin at the end of the execution

### ISSUE THREAD

**Issue by testphreak** [aleksandr-m/gitflow-maven-plugin#117]
I know the plugin implementation models git flow as described [here](https://nvie.com/posts/a-successful-git-branching-model/). But one thing that would be nice in this model have do is to eventually merge the release tags created in master back into the develop branch after releasing a feature.

Essentially, say we are creating a new release v2.1.1, at the very end the `release-finish` goal, I am proposing that from the `develop` branch we do for example -- 

```
git fetch --tags origin
git merge 2.1.1
git push origin develop
```

Maybe this proposal deviates from strictly following the git flow model, but has the benefit that the tags created in `master` branch make it's way into the `develop` branch. This will also help when you generate change log from git log as part of your `Maven` build lifecycle.

Does this make sense? Do you see any downsides to this approach? I can explain further if the description isn't clear.

**Comment by aleksandr-m** [comment]
@testphreak First of all, you cannot have multiple tags with the same name.

In the original gitflow every commit in production branch is deployable and therefore tagged. If you don't use master branch as a production branch then maybe you should use single branch model. This plugin supports it too. :)

> This will also help when you generate change log from git log as part of your Maven build lifecycle.

Can you explain further. Do you use some plugin to do that?

**Comment by testphreak** [comment]
Thanks @aleksandr-m will look into the single branch model. I do use `master` as my production branch, but would like the tags to get pushed back into `develop` or some other branch right after release, so my change log is always up to date.  Even with the single branch model, wouldn't I have this same issue where I don't get the latest release tags in a non-master branch, since that is where I start the release process?

The plugin I use for generating my change logs is [gitlog-maven-plugin](http://danielflower.github.io/maven-gitlog-plugin/index.html). I generate the change log in the package phase and use [maven-scm-plugin](https://maven.apache.org/scm/maven-scm-plugin/) to commit the updated change log. Since I generate and commit the change log for a new release as part of the build lifecycle, the tags need to be on some branch other than master.
