### ISSUE TITLE
Git and Jenkins properties not populating

### ISSUE THREAD

**Issue by philharperv** [aleksandr-m/gitflow-maven-plugin#118]
Hi,

I am creating a version file every time the project is built in Jenkins. The file contains parameters that are replaced once copied and filtered in the pom.

When running `mvn clean package` the file is populated correctly, but when running `mvn gitflow:release-finish -DpostReleaseGoals=deploy` the file is only being partially populated. The information below explains which properties are working and which are not.

Working
${project.artifactId}
${project.version}

Not working
${GIT_COMMIT}
${GIT_URL}
${BUILD_NUMBER}
${JOB_NAME}
${NODE_NAME}
${BUILD_URL}

Thanks,

Phil

**Comment by aleksandr-m** [comment]
Hard to tell. Does it work w/o `postReleaseGoals`?

**Comment by philwilsonvistair** [comment]
It works on its own, yes. I think the postReleaseGoals is not passing the parameters down to the maven executable when it runs.
