### ISSUE TITLE
release-start with commitDevelopmentVersionAtStart uses releaseFinishMessage

### ISSUE THREAD

**Issue by akuntsch** [aleksandr-m/gitflow-maven-plugin#120]
See https://github.com/aleksandr-m/gitflow-maven-plugin/blob/master/src/main/java/com/amashchenko/maven/plugin/gitflow/GitFlowReleaseStartMojo.java#L210

Shouldn't it use the releaseStartMessage?

**Comment by raehalme** [comment]
releaseStartMessage is used when committing the release version. The line you're referring to commits the next snapshot version and therefore uses the releaseFinishMessage.

**Comment by akuntsch** [comment]
I know. But the commit still happens during release-start, so imo it does not make sense to use the releaseFinishMessage when the release is not yet finished.

**Comment by raehalme** [comment]
The releaseFinishMessage has a value of `update for next development version` and that's what it does.

**Comment by akuntsch** [comment]
So how do we proceed? I think there are multiple options:

* change the default commit messages
* add another commit message for that special case
* leave as is

Maybe we can get @aleksandr-m's opinion on this?

**Comment by aleksandr-m** [comment]
What exactly the problem is? Are you overriding default message? How bad does it looks like with your configuration?
