### ISSUE TITLE
hotfix finished with merge problems, restart of plugin not possible

### ISSUE THREAD

**Issue by wumpz** [aleksandr-m/gitflow-maven-plugin#121]
I hat expected the plugin to work again, after I resolved all merge conflicts and committed. But I get exceptions like: hotfix tag already exists or nothing to pull from develop branch, etc.

The plugin should in this case do the needed steps to finish the hotfix. 

Same problem occurs for feature branches.

**Comment by aleksandr-m** [comment]
#109
