### ISSUE TITLE
ArgLine paramater should accept list of params

### ISSUE THREAD

**Issue by uncool89** [aleksandr-m/gitflow-maven-plugin#127]
During gitflow:release-start and gitflow:release-finish I need to pass two parameters: 
-Dargline=--settings=path,-Dsettings.security=path
This is failing due to fact that -Dargline is not accepting list of params separated by comma.

**Comment by srsp** [comment]
Have you tried using quotes?

`mvn gitflow:release-start -Dargline='--settings=path -Dsettings.security=path'`

**Comment by uncool89** [comment]
Yes, I tried this solution however it also failed. It is treated as one long path to settings file.

**Comment by aleksandr-m** [comment]
@uncool89 Why comma? Use spaces. Simon's example should work.

**Comment by uncool89** [comment]
I already tired without commas and it didn't work. I am passing those arguments to bamboo build and when passing like this: -DargLine='--settings=path -Dsettings.security=path' it can't find settings.xml file as it is treated as one long path to settings file. However when I am passing only -DargLine=--settings=path it finds settings file but fails due to authentication problem. In both scenarios I always pass the same path so it isn't fault of wrong path.

**Comment by aleksandr-m** [comment]
@uncool89 Works for me. Can you show exact path you're using?
