### ISSUE TITLE
bugfix/* branches

### ISSUE THREAD

**Issue by inteloid** [aleksandr-m/gitflow-maven-plugin#133]
What are your thoughts (future plans) on these? 

Or maybe a parameter that will create a bugfix branch when calling feature-start?

**Comment by aleksandr-m** [comment]
Have you seen [this](https://github.com/nvie/gitflow/issues/24)?

How bugfix branch would be different from feature branch?

**Comment by aleksandr-m** [comment]
@inteloid Ping.
