### ISSUE TITLE
MultiModule Version not set on child modules on Windows

### ISSUE THREAD

**Issue by rhirtstzh** [aleksandr-m/gitflow-maven-plugin#134]
Thanks Aleksandr for your answer on my entry, yes indeed, I'm running on Windows. Is there a way to get rid of the quotes?

And about your comment, yes, in the comment on the issue it did not turn out quoted correctly. Here is what is running:

`mvn org.codehaus.mojo:versions-maven-plugin:set -DgroupId='*' -DartifactId='*' -DnewVersion=1.4.35-L-SNAPSHOT -DgenerateBackupPoms=false`

does not work, but this here does work:

`mvn org.codehaus.mojo:versions-maven-plugin:set -DgroupId=* -DartifactId=* -DnewVersion=1.4.35-L-SNAPSHOT -DgenerateBackupPoms=false`

Could we get a fix on this issue?

**Comment by aleksandr-m** [comment]
@rhirtstzh Cannot reproduce it in my test setup. Which error do you get? Can you share your project? Or create simple project to demonstrate the issue you have.

**Comment by rhirtstzh** [comment]
I created a small multi-module Project (attached zip, should run standalone):

[blueprint.zip](https://github.com/aleksandr-m/gitflow-maven-plugin/files/2498115/blueprint.zip)

When I run mvn gitflow:release-start from the develop branch, and I do not override the target release version, this step works fine, I end up on the release branch (in my blueprint it would be release/1.0.1). 
However, if I specify, that my release will be 1.1.0 for example, it fails. Attached, I also put the debug-log output from my maven call in the terminal. 
[logfile.txt](https://github.com/aleksandr-m/gitflow-maven-plugin/files/2498124/logfile.txt)
There I see, because the update of the versions did not work, and I see an error when committing afterwards. 

As soon as I run that line of mvn setting the version without the quotes, it works. In context of the gitflow plugin I can not test if ommitting the quotes would help. I assume yes.

The same issue occurs anyway upon release-finish. Because the set-version has to be run in all cases, and does not work with the same issue as above.

I appreciate your help!

**Comment by aleksandr-m** [comment]
@rhirtstzh Thanks for the sample project. Can you try to run with empty groupId and artifactId, like `-DgroupId= -DartifactId=`. Looking at the [source code of the versions plugin](https://github.com/mojohaus/versions-maven-plugin/blob/master/src/main/java/org/codehaus/mojo/versions/SetMojo.java#L299) both of them are set to `*` if they are empty.

**Comment by rhirtstzh** [comment]
@aleksandr-m That seems to do the trick, it works well when using groupId and artifactId as you proposed. I understand that solution would work on Linux as well? Then we would have a go for a change on the plugin itself? That would be great, thanks in advance.

**Comment by rhirtstzh** [comment]
@aleksandr-m thank you very much!
