### ISSUE TITLE
Need to skip 'master' branch build after gitflow:release...

### ISSUE THREAD

**Issue by kitplummer** [aleksandr-m/gitflow-maven-plugin#135]
I have a feeling we're close, but are just missing something simple.

We run: `mvn -B gitflow:release` and everything works as expected, we get our 'develop' and 'master' branches updated as expected.  However, when the push to 'master' happens it triggers another build.  We're trying to use Bitbucket.org's Pipelines - which provide a "skip" ability by using [skip CI] as the commit message.  We've tried all kinds of combos of defining the commit messages in the pom configuration.  However, there isn't a commit message for the merge from develop to master - when the push happens during the release so we end up unable to actual skip it.

Any insight/help would be so greatly appreciated.  We've poked at rebasing and fast-forwards to no avail too.  

TIA.

**Comment by jjlharrison** [comment]
I'm [working on a pull-request](https://github.com/jjlharrison/gitflow-maven-plugin/commit/bc5d0fd1ecf29b5ab509babeffea1590cb674f80) to allow custom merge commit messages. Would that solve your problem?

**Comment by kitplummer** [comment]
I believe so!

**Comment by jjlharrison** [comment]
> @jjlharrison I think most users are ok with default git merge messages and they can be customized in git config. Custom messages in this plugin would override them. How about create blank merge commit messages in `CommitMessages` and if they are blank then use default git messages.

Sure, will do. 👍🏻

**Comment by kitplummer** [comment]
That'd be awesome.  Thanks guys, looking forward to getting this working.

**Comment by aleksandr-m** [comment]
@jjlharrison Any progress?

**Comment by aleksandr-m** [comment]
@kitplummer I've pushed some changes. Can you take a look.
Do you need some parameters in merge commit message e.g. branch names?

**Comment by kitplummer** [comment]
Cool!  Looks like that'll work.  I don't believe we would.

**Comment by aleksandr-m** [comment]
@kitplummer Great! `1.11.0` is released.
