### ISSUE TITLE
[Question] Is it possible do package in release-finish goal?

### ISSUE THREAD

**Issue by limkinZero** [aleksandr-m/gitflow-maven-plugin#137]
Hi,
I´ve an issue executing finish-release goal in a multi module maven project because in one of my modules I use `unpack-dependencies` from `maven-dependency-plugin`. 
The problem is when I launch the release start, a clean and testing is done. I need to package the modules before. I have tried with the parameter -DpreReleaseGoals without result.

**Comment by aleksandr-m** [comment]
@limkinZero You can skip clean testing if that is the problem.

**Comment by limkinZero** [comment]
How? Put -Dskiptests ?

**Comment by aleksandr-m** [comment]
With [skipTestProject](https://aleksandr-m.github.io/gitflow-maven-plugin/release-finish-mojo.html#skipTestProject) parameter.

**Comment by limkinZero** [comment]
Thanks, works. I close it.
