### ISSUE TITLE
Use Maven Toolchains to specify paths for <mvnExecutable> and <gitExecutable>

### ISSUE THREAD

**Issue by pjverity** [aleksandr-m/gitflow-maven-plugin#138]
Would [Maven Toolchains](https://maven.apache.org/guides/mini/guide-using-toolchains.html) be a more appropriate place to configure the Git and Maven executables?

As the organisation restricts setting environment variables on developer workstations, we have to either write wrapper scripts to adjust the `PATH` to launch the IDE, or configure the IDE separately (which I've not done successfully in IntelliJ yet). As developer and CI environments differ as to where these tools are installed, we can't provide a fixed location for `<mvnExecutable>` or `<gitExecutable>` in a projects POM.

One approach is to use an _active by default_ `<profile>` in the `settings.xml` file to expose these paths as `<properties>` which  `<mvnExecutable>` and `<gitExecutable>` refer to. Each developer and build server then define these properties providing the path to their locally installed Git and Maven executables. While this works, it introduces what seems like an unnecessary profile. Would it be cleaner to use the `toolchains.xml` configuration to specify these paths?

**Comment by aleksandr-m** [comment]
You need maven to run maven plugin, don't you?
