### ISSUE TITLE
mvn gitflow:release - allow fast-forward merge of developmentBranch to productionBranch

### ISSUE THREAD

**Issue by DemonicTutor** [aleksandr-m/gitflow-maven-plugin#14]
When using **mvn gitflow:release** the branch **develop** is merged back to **master** using a merge-commit.

I would like to have the option to use a fast-forward commit / rebase-merge.

**Comment by aleksandr-m** [comment]
Although [original article](http://nvie.com/posts/a-successful-git-branching-model/) recommends using `--no-ff`, the fast-forward could make sense in some cases.

**Comment by DemonicTutor** [comment]
Personally i prefer rebase because merge-commit just *look* more cluttered and as if there is "something important"  ... when in reality its just a update branch master.... there is no important information - just making it look more complex (some may say fancier) than it really is.

Personal preference.
