### ISSUE TITLE
[Question] Is it possible to include the argLine in pom file? 

### ISSUE THREAD

**Issue by ErfanMaybe** [aleksandr-m/gitflow-maven-plugin#143]
When we do `gitflow:feature-finish` we can include the `argLine` parameter to pass required parameters for Maven subcommands. Since this is a repetitive  process with often same parameters e.g. for surefire it would be great to have the possibility to include it in the pom file.

Thanks.

**Comment by aleksandr-m** [comment]
@ErfanMaybe Yes, you can. Do you have some issue with that?

**Comment by ErfanMaybe** [comment]
Oh really? I didn't know I could define it on pom file, is it documented somewhere?

**Comment by ErfanMaybe** [comment]
@aleksandr-m any updates on this? Thanks!

**Comment by aleksandr-m** [comment]
Do you know any parameter that cannot be configured in the pom? What update do you expect?

**Comment by ErfanMaybe** [comment]
I didn't know you could configure the `argLine` parameter in the pom. I was asking for an update to my second question when I asked if it's documented anywhere as I haven't seen any examples or documentation where it's stated that `argLine` can be configured on pom file.

So if I understand your response right, instead of doing `mvn gitflow:feature-finish -DargLine="-Dxxx=yyy"` I could configure my pom as such and just run `mvn gitflow:feature-finish`, right?

```
<plugin>
    <groupId>com.amashchenko.maven.plugin</groupId>
    <artifactId>gitflow-maven-plugin</artifactId>
    <version>1.10.0</version>
    <configuration>
        <argLine>-Dxxx=yyy</argLine>
        ...
    ...
...
```

**Comment by aleksandr-m** [comment]
Yes.
