### ISSUE TITLE
Issue with postReleaseGoals parameter

### ISSUE THREAD

**Issue by limkinZero** [aleksandr-m/gitflow-maven-plugin#144]
Hi @aleksandr-m,

I am using the parameter to deploy the generation of the release within my gitlab-ci 
`mvn -B gitflow:release -DpostReleaseGoals=deploy -DskipTests=true `
and I'm getting errors when signing my artifacts. The fact is that I use the plugin `maven-gpg-plugin (v1.6)` and getting the following error:
```
[INFO] --------------------------< com.test:ci-test >--------------------------
[INFO] Building ci-test 0.0.5-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- gitflow-maven-plugin:1.11.0:release (default-cli) @ ci-test ---
[INFO] Checking for uncommitted changes.
[INFO] Local branch 'develop' doesn't exist. Trying to fetch and check it out from 'origin'.
[INFO] Fetching remote branch 'origin develop'.
[INFO] Creating a new branch 'develop' from 'origin/develop' and checking it out.
[INFO] Fetching remote branch 'origin develop'.
[INFO] Comparing local branch 'develop' with remote 'origin/develop'.
[INFO] Fetching remote branch 'origin master'.
[INFO] Comparing local branch 'master' with remote 'origin/master'.
[INFO] Checking out 'develop' branch.
[INFO] Checking for SNAPSHOT versions in dependencies.
[INFO] Cleaning and testing the project.
[INFO] Version is blank. Using default version.
[INFO] Updating version(s) to '0.0.5'.
[INFO] Committing changes.
[INFO] Checking out 'master' branch.
[INFO] Merging (--no-ff) 'develop' branch.
[INFO] Creating '0.0.5' tag.
[INFO] Running Maven goals: deploy
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
...
[ERROR] [INFO] --- maven-gpg-plugin: 1.6: sign (sign-artifacts) @ ci-test ---
[ERROR] gpg: can not open '/ dev / tty': No such device or address
```

If instead of doing the deploy as a subphase of the release I execute it by itself as mvn deploy, the process ends correctly.

I think the plugin is not passing all the information to the third-party plugins that are running in the phase. I have set the DEBUG mode but the plugin does not get the detailed information of the configuration of the maven-gpg-plugin. I think this could be another bug.

**Comment by limkinZero** [comment]
> Have you set `verbose` parameter to true? Yes I do but i can´t see the gpg maven plugin configuration.

I put a log file of release and deploy proccess. You can reproduce the error using the plugin gpg-maven-plugin and execute gpg: sign.
[Error_release_deploy.log](https://github.com/aleksandr-m/gitflow-maven-plugin/files/2734025/Error_release_deploy.log)

**Comment by aleksandr-m** [comment]
Have you tried to set `--no-tty`? See [gpg-doesnt-work-in-crontab](https://serverfault.com/questions/190871/gpg-doesnt-work-in-crontab) and [gpg: cannot open '/dev/tty': No such device or address](https://github.com/nodejs/docker-node/issues/922).

Try also adding `-vv` to gpg to see more logs.

**Comment by aleksandr-m** [comment]
@limkinZero Have you resolved this?

**Comment by limkinZero** [comment]
Yes but I had to do in two steps. I can't use the post release task. I don't know why the process doesn't take maven got parameters.

**Comment by glianeric** [comment]
Could you please describe exactly how you resolved this?

**Comment by limkinZero** [comment]
I did in two maven steps changing to master branch.

```yaml
    - mvn $MAVEN_CLI_OPTS -B gitflow:release -DskipTests=true
    - git checkout master
    - mvn $MAVEN_CLI_OPTS deploy -DperformRelease=true
````

**Comment by wpater** [comment]
I have a similar issue - I am using custom settings - `-s ./.m2/settings.xml` and it's not provided to the post-release step.
