### ISSUE TITLE
Merge conflicts during release-finish

### ISSUE THREAD

**Issue by bugada** [aleksandr-m/gitflow-maven-plugin#148]
I'm encountering problems during release-finish, merge conflicts on pom occur. Tthis happens to me on some projects (not all). I'm using latest version of this plugin, but happens also on 1.10.0.

```
++<<<<<<< HEAD
 +      <version>2.0.1-SNAPSHOT</version>
++=======
+       <version>2.0.1</version>
++>>>>>>> release-2.0.1
```

It seems there is a hidden space, but actually there isn't in both file. Due to this, the merge fails.
The only option I see is to use a merge driver or specify the --strategy-option=theirs, but this plugin afaik doesn't support this.

Do you have any suggestions?
Thank you

**Comment by aleksandr-m** [comment]
@bugada  Maybe line endings problem? You can try creating `.gitattributes`.
