### ISSUE TITLE
Unable to do support hotfix-finish 

### ISSUE THREAD

**Issue by Rudi75** [aleksandr-m/gitflow-maven-plugin#152]
Hi
I've created a support branch (**support/0.2.0**) and a hotfix branch ontop of this support branch ( **hotfix/support/0.2.0/0.2.1**). When I try to finish the hotfix my branch isn't shown in the list of available branches. Another hotfix branch made ontop of the master branch (**hotfix/0.3.1**) is shown.

I'm using the default branch-prefixes
```
<groupId>com.amashchenko.maven.plugin</groupId>
	<artifactId>gitflow-maven-plugin</artifactId>
	<configuration>
		<postHotfixGoals>clean deploy site-deploy</postHotfixGoals>
		<postReleaseGoals>clean deploy site-deploy</postReleaseGoals>
		<hotfixBranchPrefix>hotfix-${project.artifactId}-</hotfixBranchPrefix>
		<versionDigitToIncrement>1</versionDigitToIncrement>
		<skipTestProject>true</skipTestProject>
		<argLine>-DskipTests=true -P processAfUnits,build</argLine>
		<useSnapshotInHotfix>true</useSnapshotInHotfix>
		<useSnapshotInRelease>true</useSnapshotInRelease>
		<commitDevelopmentVersionAtStart>true</commitDevelopmentVersionAtStart>
		<allowSnapshots>true</allowSnapshots>
	</configuration> 
```

**Comment by aleksandr-m** [comment]
> I'm using the default branch-prefixes

But you are - `<hotfixBranchPrefix>hotfix-${project.artifactId}-</hotfixBranchPrefix>` and it doesn't match your hotfix support branch prefix `hotfix/support/0.2.0/0.2.1`.

**Comment by Rudi75** [comment]
Ah sry, I just added this line for test purposes AFTER it didn't work. I removed the line and tried the whole process again but same result.

**Comment by Rudi75** [comment]
Even if i change the hotfixBranchPrefix, create a new hotfix branch with hotfix-start and try to finish it afterwards with hotifix-finish I get the error "hotfix-finish: There are no hotfix branches."

**Comment by aleksandr-m** [comment]
Where do you change it? Hotfix branches from production branch. You are probably changing it in the development branch.

**Comment by Rudi75** [comment]
on develop, master and my support branch from which I want to create the hotfix branch

**Comment by Rudi75** [comment]
I think it is an OS specific problem: works on my Windows machine, doesn't work on my linux system

**Comment by aleksandr-m** [comment]
@Rudi75  Please share your configuration and exact steps to reproduce this issue.

**Comment by Rudi75** [comment]
System:
![image](https://user-images.githubusercontent.com/10672836/52698682-4ca36800-2f74-11e9-9ecb-6684c62c26b1.png)

Configuration:
![image](https://user-images.githubusercontent.com/10672836/52699469-1b2b9c00-2f76-11e9-8605-dc5d85fb6032.png)


Branches:
- master
- develop

Tags
- 0.1.0
- 0.2.0
- 0.3.0

Steps:
1. 'mvn gitflow:support-start' and selecting 0.3.0 -> creates branch support/0.3.0
2. 'git checkout support/0.3.0'
3. 'mvn gitflow:hotfix-start' and selecting support/0.3.0 -> creates branch hotfix/support/0.3.0/0.3.1
4. 'mvn gitflow:hotfix-finish' -> "hotfix-finish: There are no hotfix branches."

**Comment by aleksandr-m** [comment]
@Rudi75 
Works fine for me under ubuntu. Does `verbose` prints something interesting?

You can try to see what happens if you execute below from the terminal.

```
git for-each-ref --format="%(refname:short)" refs/heads/hotfix/**
```

**Comment by Rudi75** [comment]
` git for-each-ref --format="%(refname:short)" refs/heads/hotfix/** `-> return nothing
`git for-each-ref --format="%(refname:short)" refs/heads/hotfix/`   -> hotfix/support/0.3.0/0.3.1

**Comment by aleksandr-m** [comment]
Hmm... How about `git for-each-ref --format="%(refname:short)" "refs/heads/hotfix/**"` ?

**Comment by Rudi75** [comment]
nop, still nothing. Without the two * at the end it works.

**Comment by aleksandr-m** [comment]
Should work.
