### ISSUE TITLE
prevent snapshot build

### ISSUE THREAD

**Issue by dominik42** [aleksandr-m/gitflow-maven-plugin#153]
Hi,
is it possible to prevent the snapshot build which is started AFTER update the version in pom.xml ? We use gitflow plugin within Jenkins CI and would like to use archiveArtifact the resulting *.jar file. But due to this snapshot build, the only resulting jar file which is archive'able is the *-SNAPSHOT.jar file, which we dont like to use for subsequent deployments ![grafik](https://user-images.githubusercontent.com/969608/52485764-e3a9a200-2bb9-11e9-9c9b-d1bd0b7a495d.png)

kind regards
Dominik

**Comment by aleksandr-m** [comment]
Have you set `installProject` to `true`?

**Comment by dominik42** [comment]
Yep. Would „false“ prevent the snapshot build ?

**Comment by aleksandr-m** [comment]
Yes.

**Comment by dominik42** [comment]
Ok, it worked. 
But can you please clarify this in the documentation. Its not obvious that a parameter `installProject` prevent the subsequent snapshot build. In addition, one have to define the parameter in pom.xml plugin configuration only. Given as runtime parameter for the maven run as `-DinstallProject=false` didn't prevent those behavoir. 

But anyway, great work, your gitflow plugin, thank you !

kind regards
Dominik

**Comment by aleksandr-m** [comment]
@dominik42 
>  In addition, one have to define the parameter in pom.xml plugin configuration only. Given as runtime parameter for the maven run as -DinstallProject=false didn't prevent those behavoir.

`-DinstallProject=` works as expected. You cannot override from the command line already defined plugin configuration parameters. So if you had `<installProject>` in your pom under the plugin configuration then setting it from the command line has no effect. It is how Maven works. Remove it from the pom then you can set it from the command line.

> But can you please clarify this in the documentation. Its not obvious that a parameter installProject prevent the subsequent snapshot build.

Yeah, it probably needs a better wording. :)
