### ISSUE TITLE
release-finish fails with: refusing to update checked out branch refs/origin/master

### ISSUE THREAD

**Issue by cahi** [aleksandr-m/gitflow-maven-plugin#154]
We're using Bamboo to build and release our project.
We do a straight forward release-start - deploy - release-finish with V-1.11.0

The build is braking at the last step, when pushing to the master:
I attached the log since I dont seem to get the log well formatted :-(

`build	12-Feb-2019 06:45:18	[INFO] ------------------------------------------------------------------------
build	12-Feb-2019 06:45:18	[INFO] Building aim parent pom 1.1.3
build	12-Feb-2019 06:45:18	[INFO] ------------------------------------------------------------------------
build	12-Feb-2019 06:45:18	[INFO] 
build	12-Feb-2019 06:45:18	[INFO] --- gitflow-maven-plugin:1.11.0:release-finish (default-cli) @ aim-parent-pom ---
build	12-Feb-2019 06:45:20	[INFO] Checking for uncommitted changes.
build	12-Feb-2019 06:45:20	[INFO] Checking out 'release/1.1.3' branch.
build	12-Feb-2019 06:45:20	[INFO] Checking for SNAPSHOT versions in dependencies.
build	12-Feb-2019 06:45:20	[INFO] Fetching remote branch 'origin release/1.1.3'.
build	12-Feb-2019 06:45:20	[WARNING] There were some problems fetching remote branch 'origin release/1.1.3'. You can turn off remote branch fetching by setting the 'fetchRemote' parameter to false.
build	12-Feb-2019 06:45:20	[INFO] Fetching remote branch 'origin develop'.
build	12-Feb-2019 06:45:20	[INFO] Comparing local branch 'develop' with remote 'origin/develop'.
build	12-Feb-2019 06:45:20	[INFO] Fetching remote branch 'origin master'.
build	12-Feb-2019 06:45:20	[INFO] Comparing local branch 'master' with remote 'origin/master'.
build	12-Feb-2019 06:45:20	[INFO] Checking out 'release/1.1.3' branch.
build	12-Feb-2019 06:45:20	[INFO] Cleaning and testing the project.
build	12-Feb-2019 06:45:25	[INFO] Checking out 'master' branch.
build	12-Feb-2019 06:45:25	[INFO] Merging (--no-ff) 'release/1.1.3' branch.
build	12-Feb-2019 06:45:25	[INFO] Creating 'V1.1.3' tag.
build	12-Feb-2019 06:45:25	[INFO] Checking out 'develop' branch.
build	12-Feb-2019 06:45:25	[INFO] Merging (--no-ff) 'release/1.1.3' branch.
build	12-Feb-2019 06:45:25	[INFO] Updating version(s) to '1.1.4-SNAPSHOT'.
build	12-Feb-2019 06:45:31	[INFO] Committing changes.
build	12-Feb-2019 06:45:31	[INFO] Pushing 'master' branch to 'origin'.
build	12-Feb-2019 06:45:31	[INFO] ------------------------------------------------------------------------
build	12-Feb-2019 06:45:31	[INFO] BUILD FAILURE
build	12-Feb-2019 06:45:31	[INFO] ------------------------------------------------------------------------
build	12-Feb-2019 06:45:31	[INFO] Total time: 13.285 s
build	12-Feb-2019 06:45:31	[INFO] Finished at: 2019-02-12T06:45:31+00:00
build	12-Feb-2019 06:45:31	[INFO] Final Memory: 16M/175M
build	12-Feb-2019 06:45:31	[INFO] ------------------------------------------------------------------------
build	12-Feb-2019 06:45:31	[ERROR] Failed to execute goal com.amashchenko.maven.plugin:gitflow-maven-plugin:1.11.0:release-finish (default-cli) on project aim-parent-pom: release-finish: remote: error: refusing to update checked out branch: refs/heads/master
build	12-Feb-2019 06:45:31	[ERROR] remote: error: By default, updating the current branch in a non-bare repository
build	12-Feb-2019 06:45:31	[ERROR] remote: error: is denied, because it will make the index and work tree inconsistent
build	12-Feb-2019 06:45:31	[ERROR] remote: error: with what you pushed, and will require 'git reset --hard' to match
build	12-Feb-2019 06:45:31	[ERROR] remote: error: the work tree to HEAD.
build	12-Feb-2019 06:45:31	[ERROR] remote: error:
build	12-Feb-2019 06:45:31	[ERROR] remote: error: You can set 'receive.denyCurrentBranch' configuration variable to
build	12-Feb-2019 06:45:31	[ERROR] remote: error: 'ignore' or 'warn' in the remote repository to allow pushing into
build	12-Feb-2019 06:45:31	[ERROR] remote: error: its current branch; however, this is not recommended unless you
build	12-Feb-2019 06:45:31	[ERROR] remote: error: arranged to update its work tree to match what you pushed in some
build	12-Feb-2019 06:45:31	[ERROR] remote: error: other way.
build	12-Feb-2019 06:45:31	[ERROR] remote: error:
build	12-Feb-2019 06:45:31	[ERROR] remote: error: To squelch this message and still keep the default behaviour, set
build	12-Feb-2019 06:45:31	[ERROR] remote: error: 'receive.denyCurrentBranch' configuration variable to 'refuse'.
build	12-Feb-2019 06:45:31	[ERROR] To file:///opt/bambooagent/bamboo-agent-home/xml-data/build-dir/_git-repositories-cache/e25e308b7a6b53f7f665d56212eddcf10ef6c24f
build	12-Feb-2019 06:45:31	[ERROR] * [new tag]         V1.1.3 -> V1.1.3
build	12-Feb-2019 06:45:31	[ERROR] ! [remote rejected] master -> master (branch is currently checked out)
build	12-Feb-2019 06:45:31	[ERROR] error: failed to push some refs to 'file:///opt/bambooagent/bamboo-agent-home/xml-data/build-dir/_git-repositories-cache/e25e308b7a6b53f7f665d56212eddcf10ef6c24f'
build	12-Feb-2019 06:45:31	[ERROR] -> [Help 1]
build	12-Feb-2019 06:45:31	[ERROR] 
build	12-Feb-2019 06:45:31	[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
build	12-Feb-2019 06:45:31	[ERROR] Re-run Maven using the -X switch to enable full debug logging.
build	12-Feb-2019 06:45:31	[ERROR] 
build	12-Feb-2019 06:45:31	[ERROR] For more information about the errors and possible solutions, please read the following articles:
build	12-Feb-2019 06:45:31	[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
simple	12-Feb-2019 06:45:31	Failing task since return code of [/usr/share/atlassian-plugin-sdk-6.3.7/apache-maven-3.2.1/bin/mvn -Djava.io.tmpdir=/tmp/DEVOPS-M3POM-JOB1 -B gitflow:release-finish] was 1 while expected 0
simple	12-Feb-2019 06:45:31	Finished task 'finish release' with result: Failed`
[plan-38273432-JOB1-40.log](https://github.com/aleksandr-m/gitflow-maven-plugin/files/2854629/plan-38273432-JOB1-40.log)

**Comment by aleksandr-m** [comment]
> By default, updating the current branch in a non-bare repository ....

Judging by the error, you are trying to push into non-bare repo.

**Comment by aleksandr-m** [comment]
@cahi Thanks for posting a solution.
