### ISSUE TITLE
Merge conflict on versions in pom during hotfix-finish into exiting release branch 

### ISSUE THREAD

**Issue by iulvalSPL** [aleksandr-m/gitflow-maven-plugin#159]
Hello,

I found a bug that is very similar to the one described in #19, but it happens during  gitflow:hotfix-finish when the hotfix branch in merged into an existing release branch.

Scenario:
Branch master --> pom.xml 1.0
Branch hotfix --> pom.xml 1.0.1-SNAPSHOT
Branch release -->pom.xml 1.1-SNAPSHOT
Branch develop -->pom.xml 1.2-SNAPSHOT

I use the plugin with the following configuration:
```
<configuration>
  <pushRemote>true</pushRemote>
  <keepBranch>false</keepBranch>
  <useSnapshotInRelease>true</useSnapshotInRelease>
  <useSnapshotInHotfix>true</useSnapshotInHotfix>
  <commitDevelopmentVersionAtStart>true</commitDevelopmentVersionAtStart>
</configuration>
```
gitflow:hotfix-finish fails with merge conflicts on the release branch on pom versions :

```
        <artifactId>foobar</artifactId>
<<<<<<< HEAD
        <version>1.1-SNAPSHOT</version>
=======
        <version>1.0.1</version>
>>>>>>> hotfix-1.0.1
```

I have a fork and will create a PR soon.

**Comment by aleksandr-m** [comment]
@iulvalSPL Your PR has gone to some other fork. Also can you change only relevant code for this issue.

**Comment by iulvalSPL** [comment]
@aleksandr-m I was hoping for a CR inside my organisation first, before creating a PR from the fork, but that was delayed, so  I've created the PR and considered your comment. Thanks!

**Comment by aleksandr-m** [comment]
Merged. Thanks.
