### ISSUE TITLE
artifactId cant include property

### ISSUE THREAD

**Issue by stefanmeisner** [aleksandr-m/gitflow-maven-plugin#16]
The gitflow:release goal cant handle an artifactId like my.artifact.${somProperty}.
Both the jar and deploy plugins handles artifactId like this

**Comment by aleksandr-m** [comment]
But not the [versions-maven-plugin](https://github.com/mojohaus/versions-maven-plugin).

**Comment by stefanmeisner** [comment]
https://github.com/mojohaus/versions-maven-plugin/issues/76

**Comment by aleksandr-m** [comment]
@stefanmeisner Does versions-maven-plugin 2.4 solve you problem? Or do you want to use property in the project artifactId? See https://github.com/mojohaus/versions-maven-plugin/issues/172.

**Comment by aleksandr-m** [comment]
The versions-maven-plugin version can be set in pom see 01275d041f3982e114090944064e9d7a88f55f0f
