### ISSUE TITLE
Bump develop version after feature-finish

### ISSUE THREAD

**Issue by jam01** [aleksandr-m/gitflow-maven-plugin#162]
A way to allow the develop version to be bumped after doing a feature-finish

gitCheckout(gitFlowConfig.getDevelopmentBranch())
gitMergeNoff(featureBranchName)
commitProjectVersion(nextSnapshotVersion, commitMessages.getReleaseVersionUpdateMessage())

I could probably throw in a PR if you're OK with this functionality. Perhaps through a `incrementDevelopmentVersionAtFinish` parameter or something along those lines.

**Comment by aleksandr-m** [comment]
@jam01 Sure. PR-s are welcome.

**Comment by ashusharmatech** [comment]
PR opened for this enhancement PR #241
