### ISSUE TITLE
Custom properties in releaseFinishMergeMessage is treated as literals

### ISSUE THREAD

**Issue by steve-todorov** [aleksandr-m/gitflow-maven-plugin#163]
## Issue

According to the [docs](https://github.com/aleksandr-m/gitflow-maven-plugin#custom-properties-in-commit-messages) you can use `custom properties` in the commit messages. However, once we've configured our [`releaseFinishMergeMessage`](https://github.com/carlspring/unboundid-maven-plugin/blob/master/pom.xml#L132) to be `[release] Merge branch release/@{version}` the commit message was actually literal ([check here](https://github.com/carlspring/unboundid-maven-plugin/commit/d7764db19b0bcc4ec81495934ffbe50f170828c6))

**Comment by aleksandr-m** [comment]
The `releaseFinishMergeMessage` was added in #135 and currently it is missing `@{version}` replacement.

**Comment by steve-todorov** [comment]
Awesome! Many thanks for fixing this so fast! Do you plan to cut a release soon?

**Comment by aleksandr-m** [comment]
@steve-todorov 1.12.0 is out. Enjoy!

**Comment by steve-todorov** [comment]
Great! Thanks for letting me know and for all your hard work! :)

**Comment by s-berdnikov** [comment]
The same problem still exists with `featureSquashMessage` (version v1.20.0)
