### ISSUE TITLE
Hotfix finish release merge

### ISSUE THREAD

**Issue by segersb** [aleksandr-m/gitflow-maven-plugin#165]
We noticed that during a hotfix-finish the hotfix branch is merged to master and develop.
However we would also like it to be merged to release, if there is a release branch.
Could you explain if that is possible or add this as a feature request?

[INFO] Checking for uncommitted changes.
[INFO] Fetching remote branch 'origin hotfix/18.26.1'.
[INFO] Comparing local branch 'hotfix/18.26.1' with remote 'origin/hotfix/18.26.1'.
[INFO] Fetching remote branch 'origin develop'.
[INFO] Comparing local branch 'develop' with remote 'origin/develop'.
[INFO] Local branch 'master' doesn't exist. Trying to fetch and check it out from 'origin'.
[INFO] Fetching remote branch 'origin master'.
[INFO] Creating a new branch 'master' from 'origin/master' and checking it out.
[INFO] Fetching remote branch 'origin master'.
[INFO] Comparing local branch 'master' with remote 'origin/master'.
[INFO] Checking out 'hotfix/18.26.1' branch.
[INFO] Cleaning and testing the project.
[INFO] Checking out 'master' branch.
[INFO] Merging (--no-ff) 'hotfix/18.26.1' branch.
[INFO] Creating '18.26.1' tag.
[INFO] Running Maven goals: deploy
[INFO] Checking out 'develop' branch.
[INFO] Updating version(s) to '18.26.1'.
[INFO] Committing changes.
[INFO] Merging (--no-ff) 'hotfix/18.26.1' branch.
[INFO] Updating version(s) to '19.2.0-SNAPSHOT'.
[INFO] Committing changes.
[INFO] Pushing 'master' branch to 'origin'.
[INFO] Pushing 'develop' branch to 'origin'.
[INFO] Deleting remote branch 'hotfix/18.26.1' from 'origin'.
[INFO] Deleting 'hotfix/18.26.1' branch.

**Comment by aleksandr-m** [comment]
It is [already implemented.](https://github.com/aleksandr-m/gitflow-maven-plugin/blob/6c21067d7cd0090fa39e1f755f796552ffc27709/src/main/java/com/amashchenko/maven/plugin/gitflow/GitFlowHotfixFinishMojo.java#L234)
Do you have release branch locally?

**Comment by aleksandr-m** [comment]
@segersb Ping.
