### ISSUE TITLE
Does the plugin pushes wars to a nexus repository  ? 

### ISSUE THREAD

**Issue by hbellahc** [aleksandr-m/gitflow-maven-plugin#167]
Hi
When I run a release with the plugin (goal release), everything seems OK except that the war is not published in nexus repository ?

Does the plugin pushes wars to a nexus repository  ? 

In my pom.xml in have the distributionManagement well configured (it's works for releases done with the maven release plugin).

Thanks for your help.
Hicham

**Comment by jjlharrison** [comment]
Deployment to your Maven repository is not the responsibility of this plugin. The maven-deploy-plugin (or deploy phase) should be used for that. 

I’m my organisation, we use this plugin locally to tag the release and Jenkins runs a `mvn deploy` to push to Nexus.

**Comment by aleksandr-m** [comment]
@hbellahc You can use `postReleaseGoals` parameter to run `deploy` goal.
