### ISSUE TITLE
Cut another release: v1.12.0?

### ISSUE THREAD

**Issue by sdoxsee** [aleksandr-m/gitflow-maven-plugin#168]
Great project. I've been playing with it today and found it to be quite solid. I ran into some problems finishing a hotfix with release branches open. These issues seem to have been addressed since the previous release. Would it be ok to cut a new release soon?

Thanks!

**Comment by aleksandr-m** [comment]
I would like to merge #164 before.

**Comment by sdoxsee** [comment]
Works for me. Thanks so much!
