### ISSUE TITLE
Is there a possibility to automatically tag on feature finish?

### ISSUE THREAD

**Issue by wumpz** [aleksandr-m/gitflow-maven-plugin#173]

**Comment by aleksandr-m** [comment]
@wumpz Currently no. Tags go to production branch. What is your use case for tagging development branch?

**Comment by wumpz** [comment]
To highlight a feature merge into the development branch.

**Comment by wumpz** [comment]
@aleksandr-m I thought a while about it. I don't need it for every feature merge. Therefore, to tag it manually has more benefits, than doing it always.
