### ISSUE TITLE
Added support for overriding merge message for the gitflow:release-finish on develop branch

### ISSUE THREAD

**Issue by pcoulso1** [aleksandr-m/gitflow-maven-plugin#175]
Most of the git commit messages can now be overridden, however one during gitflow:release-finish cannot.

Our git commit hooks require a ticket to be listed against all commits. This one merge message prevents us from using this plugin.

**Proposed solution**

Use the releaseFinishMergeMessage for the one commit message which cannot be overridern

e.g. within src/main/java/com/amashchenko/maven/plugin/gitflow/GitFlowReleaseFinishMojo.java at line 281 modify the code from

`
                // merge branch master into develop
                gitMerge(releaseBranch, releaseRebase, releaseMergeNoFF, false, null, null);
`

to

`
                // merge branch master into develop
                gitMerge(releaseBranch, releaseRebase, releaseMergeNoFF, false, 
                    commitMessages.getReleaseFinishMergeMessage(), messageProperties);
`

**Comment by aleksandr-m** [comment]
@pcoulso1 `1.13.0` is out.
