### ISSUE TITLE
[FR] git parameters

### ISSUE THREAD

**Issue by laur89** [aleksandr-m/gitflow-maven-plugin#178]
Could we have ability to provide git params similar to maven?
This might be needed in CI env to enforce some specific behavior, eg bypassing git hooks by providing `--no-verify`.

**Comment by aleksandr-m** [comment]
@laur89 The are plenty of git commands used that can be messed up with additional arbitrary parameters.
Do you need something else besides `--no-verify`? Additional parameter can be added to control `--no-verify` in commit goals.

**Comment by laur89** [comment]
`git push` takes options, that can be used to instruct CIs to skip pipelines, eg [gitlab respects](https://docs.gitlab.com/ee/ci/yaml/#skipping-jobs) `-o ci.skip`.
These are the immediate flags we'd need.

>Additional parameter can be added to control --no-verify in commit goals.
Is this already supported feature? Worked through the readme but couldn't find it.

**Comment by aleksandr-m** [comment]
Push options implemented in cb93c2f
