### ISSUE TITLE
Hotfix merge to develop creates "Christmas tree"

### ISSUE THREAD

**Issue by asodja** [aleksandr-m/gitflow-maven-plugin#179]
I was playing a bit with hotfix and it seems that it's merge creates Christmas tree when checking `git log --graph` as shown below. I guess this happens because hotfix is created from master branch and then merged into develop. Can this be avoided somehow or is there already an option for that? Probably a fix would be to cherry-pick commit(s) from hotfix into develop. 

<img width="413" alt="Screenshot 2019-05-28 at 20 15 28" src="https://user-images.githubusercontent.com/3939893/58501858-a0ce0300-8185-11e9-8a5f-01d3afdebd2b.png">

**Comment by aleksandr-m** [comment]
@asodja Usually, hotfix branches are for small critical fixes. Are you sure you need hotfix goals? There are `support` and `feature` branches that can be more appropriate.
Also you graph looks a bit odd with all the release messages. How did you managed to create that with hotfix goals? :)

**Comment by asodja** [comment]
I am aware of the fact that hotfix should be used for small critical commits, I used wrong versioning here for hotfix, but this does not affect the behaviour anyway. I am using feature branches and normal releases otherwise. :)

This output was generated with `git log --graph` (I actually used `git log --graph --pretty=format:"%B"` for more visible output). So when using just `git log` you won't see "Christmas tree" and all release messages together.

I was able to create this with normal hotfix flow. I did not have any hotfix before in the project, I just had some releases. Then I did:
1. mvn gitflow:hotfix-start
2. I did a commit
3. mvn gitflow:hotfix-finish
4. And finally `git log --graph` outputed such history

**Comment by aleksandr-m** [comment]
@asodja Can you show exact commands that you've run to get this? How do you expect this can be avoided?

**Comment by asodja** [comment]
@aleksandr-m  sorry for late response. Exact commands I used:
1. mvn gitflow:hotfix-start (and select the new version you want)
2. touch new-file.txt && git add new-file.txt && git commit -m "Hotfix with new-file.txt"
3. mvn gitflow:hotfix-finish -DskipTestProject=true

Basically why this git log graph happens: hotfix is created from master and then merged into develop. But this is just how hotfix works. 

To avoid this a possible solution would be to cherry-pick the commit (or commits) from hotfix branch and apply them to develop. Of course this should be optional and default behaviour should stay the same as it is now.
