### ISSUE TITLE
Snapshots are allowed when running gitflow release start

### ISSUE THREAD

**Issue by manderson23** [aleksandr-m/gitflow-maven-plugin#182]
If I run the following command with snapshot dependencies in the pom
```
mvn gitflow:release-start -DpushRemote=true -DversionDigitToIncrement=1 -DcommitDevelopmentVersionAtStart=true
```
the command succeeds even though `allowSnapshots` should be using the default value of `false`.

I think this is a regression introduced when an issue related to snapshots that I previously reported was fixed - #169

**Comment by aleksandr-m** [comment]
@manderson23 Cannot reproduce. Can you create a simple test project.

**Comment by Opa-** [comment]
I had the same issue and had to downgrade the plugin to v1.11.0

**Comment by glianeric** [comment]
I have created a very, very dirty 'fix' for this, which is why I'm not submitting it as a PR right now.  I basically added an enforcer run just before the merge, which runs the requirereleasedeps enforcer rule on the project.   I still believe that fixing up @aleksandr-m  function is a much better solution, but for now I can run with 'allowSnapshots', while my addition catches any unwanted snapshots.

**Comment by aleksandr-m** [comment]
@manderson23 @Opa- @glianeric reprex please or mcve or mwe.

**Comment by aekrylov** [comment]
@aleksandr-m It seems that snapshots versions aren't checked properly when the version is defined in a property. Here's a minimal example: https://github.com/aekrylov/snapshots-reprex/tree/develop

**Comment by manderson23** [comment]
In my case all versions are defined in properties.

**Comment by cidus** [comment]
I have encountered this is issue as well, and have verified it with a dummy project.

This will be properly checked:
```
	<dependencies>
		<dependency>
			<groupId>world.hello</groupId>
			<artifactId>dummy-library</artifactId>
			<version>1.0.0-SNAPSHOT</version>
		</dependency>
	</dependencies>
```

This will not:
```
	<properties>
		<dummy-library.version>1.0.0-SNAPSHOT</dummy-library.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>world.hello</groupId>
			<artifactId>dummy-library</artifactId>
			<version>${dummy-library.version}</version>
		</dependency>
	</dependencies>
```

**Comment by cidus** [comment]
I replaced readModel with reloadProject which uses ProjectBuilder in order to recompute all project info, it should resolve transitive dependencies and property versions.
PR https://github.com/aleksandr-m/gitflow-maven-plugin/pull/204
