### ISSUE TITLE
DevelopmentVersion is not used in batch mode?

### ISSUE THREAD

**Issue by GaborVarga** [aleksandr-m/gitflow-maven-plugin#183]
I try to set the developmentVersion in non-interactive mode (-DdevelopmentVersion=${next_development_version}) but the plugin still updates the pom files with the default increased value (e.g. release version is 3.0.2, I want next as 3.1.0-SNAPSHOT, plugins ignores this and uses 3.0.3-SNAPSHOT).
In the logs I can see this: 
 [DEBUG]   (f) developmentVersion = 3.1.0-SNAPSHOT
Still the bad value is used at the end: 
from version 3.0.2 to 3.0.3-SNAPSHOT

Any idea what is wrong?

**Comment by aleksandr-m** [comment]
@GaborVarga What goal are you running? Which parameters do you use?

**Comment by GaborVarga** [comment]
The command is : "mvn gitflow:release-finish -DallowSnapshots=true -DpushRemote=false -DargLine=-Pobfuscation -DdevelopmentVersion=${next_development_version}"

Since then I realized what could be wrong: I missed -B, right?
