### ISSUE TITLE
Release 1.12.1 is needed with updated docs

### ISSUE THREAD

**Issue by bbezanson** [aleksandr-m/gitflow-maven-plugin#184]
In the current README.md there is a reference to the April 25, 2019 changes for supporting "revision" https://github.com/aleksandr-m/gitflow-maven-plugin#update-maven-properties and it references version 1.12.1 for the plug-in. But as you know, version 1.12.0 is the current release.

Please update the README.md to cover the use of skipUpdateVersion and versionProperty. They are only semi-documented if one searches the issue database. I'm not fully sure what the differences are between skipUpdateVersion = true or false and if these are both required in the release-start and release-finish phases. I can see versionProperty used for both, but I'm not sure in regards to skipUpdateVersion.

**Comment by bbezanson** [comment]
@aleksandr-m - Would you be able to do this soon?

**Comment by gonzalofj** [comment]
> @aleksandr-m - Would you be able to do this soon?

@aleksandr-m it will be great if you can release the v1.12.1 soon ... Thank you!

**Comment by aleksandr-m** [comment]
@bbezanson @gonzalofj `1.13.0` is released. Readme updated.
