### ISSUE TITLE
Hotfix finish commit message

### ISSUE THREAD

**Issue by SergeZh4Dev** [aleksandr-m/gitflow-maven-plugin#185]
Add new commit message hotfixFinishMergeMessage similar to releaseFinishMergeMessage. At the moment hotfix merge to production and development branches are made without specifing message, so default git messages are used.
So in GitFlowHotfixFinishMojo.java need to call gitMergeNoff with commit message. For this to be able a new overloaded version of gitMergeNoff  is needed.

**Comment by aleksandr-m** [comment]
@SergeZh4Dev `1.13.0` is released
