### ISSUE TITLE
altDeploymentRepository parameter not passed to postReleaseGoals

### ISSUE THREAD

**Issue by darmbrust** [aleksandr-m/gitflow-maven-plugin#187]
It appears that when I do this:

mvn -B gitflow:release-start gitflow:release-finish -DreleaseVersion=6.00 -DdevelopmentVersion=6.01-SNAPSHOT -DaltDeploymentRepository=awsnexus::default::http://myserver/nexus/content/repositories/releases -DpostReleaseGoals="clean deploy"

It fails to deploy during the postReleaseGoals, because the paramter isn't passed to the second invocation.

It does look like you can cheat and get it to work by passing -DaltDeploymentRepository a second time, as the very first parameter within the quoted postReleaseGoals.

**Comment by glianeric** [comment]
Use -DargLine=-DaltDeploymentRepository=awsnexus::default::http://myserver/nexus/content/repositories/releases

**Comment by aleksandr-m** [comment]
Use `argLine`.
