### ISSUE TITLE
feature request: add a "prefix" option that is applied to all commit messages

### ISSUE THREAD

**Issue by darmbrust** [aleksandr-m/gitflow-maven-plugin#188]
It would be really nice to be able to specify a prefix for the commit messages that is applied to every commit done by the plugin.  I saw the ability to customize individual messages, but didn't see an easy way to prepend something like "[automated]" to each message.

**Comment by aleksandr-m** [comment]
@darmbrust Why do you need this?

**Comment by darmbrust** [comment]
I don't know that its a need, but the old plugin I used for gitflow did this.
Its nice to have all get operations done by the plugin labeled as such in the commit message.
I get part of it by using the commitMessages tags for releaseStart / releaseFinish.
But it dosen't give me an option for the merges that the plugin does, so its harder to identify all of the git activity that happened in an automated way.

Prefixing something like [gitflow] onto the messages makes it easier for developers to identify commits that they really don't need to review, even if it does modify a lot of files like ours do.

**Comment by jOphey** [comment]
We would like to be able to set a commit message prefix by command-line option in order to have the jira-task-id as prefix.
This would help us to assign the commits automatically for codereviews etc.
Alternatively it would be nice, if one could set the whole commit-message by command-line option (e.g. '-DcommitMessages.releaseFinishMergeMessage="${JIRA_TASK} Finish release ${RELEASE_VERSION}"' in a shell-script.

**Comment by jOphey** [comment]
Thanks man! This is really helpful for us!

**Comment by aleksandr-m** [comment]
@darmbrust @jOphey `1.14.0` is out.

**Comment by darmbrust** [comment]
Very cool!  Thanks.

**Comment by darmbrust** [comment]
I just tested this out, and found a minor issue - the prefix message doesn't get applied to merge commits unless the merge commit already has a message specified.

See my comments on the commit diff.
https://github.com/aleksandr-m/gitflow-maven-plugin/commit/f5276b10b4e2787538e9216f663254407acb66d3

**Comment by aleksandr-m** [comment]
@darmbrust I don't think there is a way to add prefix to default git merge commit message and there is no easy way to get that message either.

I can update readme with that caveat about using `commitMessagePrefix`.

**Comment by darmbrust** [comment]
hmm, guess I didn't look at the code carefully, I just glanced at the diff, and thought that it would do what I expected if you changed it from 
if (StringUtils.isNotBlank(message)) {

to
if (StringUtils.isNotBlank(message) || StringUtils.isNotBlank(commitMessagePrefix)) {

and then you might need a null check below... so 

```
if (StringUtils.isNotBlank(message)  || StringUtils.isNotBlank(commitMessagePrefix)) {
  if (StringUtils.isNotBlank(commitMessagePrefix)) {
    message = commitMessagePrefix + (message == null ? "" : message);
  }
```

What am I missing?
