### ISSUE TITLE
merge conflict on poms during hotfix-finish

### ISSUE THREAD

**Issue by emerout** [aleksandr-m/gitflow-maven-plugin#19]
Hello,

I'm trying to use hotfix feature.

gitflow:release-start and gitflow:release-finish are ok, automatically upgrading snapshot versions nicely.
For instance 1.0.0 is released, next snapshot version 1.0.1-SNAPSHOT

gitflow:hotfix-start is ok, branching from latest version on master. hotfix version set to 1.0.1

gitflow:hotfix-finish fail with merge conflicts on branch develop with pom versions : 

```
        <artifactId>foobal</artifactId>
<<<<<<< HEAD
        <version>1.0.1-SNAPSHOT</version>
=======
        <version>1.0.1</version>
>>>>>>> hotfix-1.0.1
```

How to deal with this problem ? hotfix life-cycle is unusable if we have to merge manually pom versions updates ...
Also, it will be nice to be able to use `mvn --batch-mode gitflow:hotfix-finish`

**Comment by aleksandr-m** [comment]
For example: master version is 1.0.0, develop version is 1.0.1-SNAPSHOT, hotfix version is 1.0.1.
```
    ____h
   /
__m
   \__d
```

Merge to master is ok, but merge to develop fails with conflict because develop branch pom version has changed.

Any thoughts how to resolve this w/o manual merging?

**Comment by Lorkster** [comment]
I'm curious about this as well since I'm seeing the exact same behaviour.

**Comment by marandalucas** [comment]
1.Hi i have the same problem.
Do you fix this issue? I think that in command mvn gitflow:hotfix-finish should ask what is the develop version? and later change de pom.xml with the input version for develop with SNAPSHOTS.

2. Can you add the batch-mode to gitflow:hotfix-finish?
Thanks for all 
Good Jobs!

**Comment by marandalucas** [comment]
@aleksandr-m ping

**Comment by aleksandr-m** [comment]
1. Asking for version won't help, because version in develop branch has changed and you get merge conflict. One of the possible solutions I can think of is to allow to continue goal execution after resolving merge by hand.

2. You mean to allow to provide branch name to finish in the command arguments?

**Comment by marandalucas** [comment]
**My branches and versions:**
Branch master --> pom.xml <version>1.0.0</version>
Branch develop --> pom.xml <version>2.0.0-SNAPSHOT</version>

**1. We want to apply a hotfix to the version 1.0.0,  We will use the following commands:**

`$ mvn gitflow:hotfix-start`  (Into branch develop)

```
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building apinators 2.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- gitflow-maven-plugin:1.5.0:hotfix-start (default-cli) @ apinators ---
[INFO] Checking for uncommitted changes.
[INFO] Checking out 'master' branch.
[INFO] Fetching remote branch 'origin master'.
[INFO] Comparing local branch 'master' with remote 'origin/master'.
What is the hotfix version? [1.0.1]:
```
***IMPORTANT (I need to automate this, could you continue with the recommended one automatically?)**
```
[INFO] Creating a new branch 'hotfix-1.0.1' from 'master' and checking it out.
[INFO] Updating version(s) to '1.0.1'.
[INFO] Committing changes.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

`$ mvn gitflow:hotfix-finish`  (Into branch hotfix-1.0.1)
```
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building apinators 1.0.1
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- gitflow-maven-plugin:1.5.0:hotfix-finish (default-cli) @ apinators ---
[INFO] Checking for uncommitted changes.
Hotfix branches:
1. hotfix-1.0.1
Choose hotfix branch to finish (1):
```
***IMPORTANT (I need to automate this, could you continue with the recommended one automatically?)**

```
[INFO] Fetching remote branch 'origin master'.
[INFO] Comparing local branch 'master' with remote 'origin/master'.
[INFO] Checking out 'master' branch.
[INFO] Merging (--no-ff) 'hotfix-1.0.1' branch.
[INFO] Creating 'v@1.0.1' tag.
[INFO] Checking out 'develop' branch.
[INFO] Merging (--no-ff) 'hotfix-1.0.1' branch.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```
```
[ERROR] Failed to execute goal com.amashchenko.maven.plugin:gitflow-maven-plugin:1.5.0:hotfix-finish (default-cli) on project apinators: Auto-merging pom.xml
[ERROR] CONFLICT (content): Merge conflict in pom.xml
```
**what happened?**

`$ git diff`
```
++<<<<<<< HEAD                                                                                                 
 +    <version>2.0.0-SNAPSHOT</version>                                                                       
++=======                                                                                                      
+     <version>1.0.1</version>                                                                                
++>>>>>>> hotfix-1.0.1   
```
**IMPORTANT. To give a solution to this problem, I would not change the POM version in develop. But if it would bring me the other changes of hotfix.**

I have also used the atlasian plugin for hotfix, It seems to work correctly. I'm going to investigate the flow.

@aleksandr-m What do you think?

**Comment by aleksandr-m** [comment]
@marandalucas Unlike `release` there can be multiple `hotfix` branches, so there is no default in `hotfix-finish` prompt.

> Don't make any changes in develop, Only make changes in master. I prefer to take the changes to develop manually

That is more or less what happens right now. You can resolve merge conflict manually, increment development version and push to remote.

**Comment by marandalucas** [comment]
> Unlike release there can be multiple hotfix branches, so there is no default in hotfix-finish prompt.
You're right. But could a batch mode be implemented in order to automate it in my CI? (want to enter values ​​automatically).


> That is more or less what happens right now. You can resolve merge conflict manually, increment development version and push to remote.

It is true. But I would like an option to only do it in master, since I have to integrate it into CI.

@aleksandr-m  **Thank you very much for that great work**

**Comment by askannon** [comment]
What about the following solution when hotfix-finish is executed:

- parse version from hotfix branch
- parse version from develop branch
- replace version in develop branch with hotfix version and commit
- merge hotfix into develop and commit
- change develop version back to original value and commit

This should avoid the merge conflict. At least that is how another gitflow maven plugin worked around this issue. And while it may not be a perfect solution it would cover most simple scenarios and avoid merge conflict.

**Comment by aleksandr-m** [comment]
@askannon *change develop version back to original value* - The hotfix version can be set ahead of the current development version, so using original value maybe isn't appropriate. On the other hand using hotfix version in development doesn't seems right too, because development version can be changed as well.

**Comment by MouettE-SC** [comment]
@askannon could be modified this way :

- parse version from hotfix branch
- parse version from develop branch
- replace version in develop branch with hotfix version and commit
- merge hotfix into develop and commit
- compare the hotfix version and the original develop version :
 - If develop version is higher than hotfix change it back
 - Else increment the hotfix version, append -SNAPSHOT and commit

And BTW this plugin is awesome 🥇

**Comment by masrawi** [comment]
would this be of help resolving this issue? i.e ignoring merge conflicts on pom.xml
https://gist.github.com/tmaybe/4c9d94712711229cd506

**Comment by aleksandr-m** [comment]
@askannon and @MouettE-SC Thanks!
