### ISSUE TITLE
argLine cannot pass on multiple parameters

### ISSUE THREAD

**Issue by glianeric** [aleksandr-m/gitflow-maven-plugin#190]
My builds use a number of custom settings, and profiles.

I have a requirement to build the following command-line:
mvn clean install '-Pwindows,build-machine  -DaltDeploymentRepository=ourrepo'

The original command line looked like:

mvn -B -X gitflow:release-start -DallowSnapshots=true -DskipTestProject=true -DargLine='-Pwindows,build-machine',-DaltDeploymentRepository=ourrepo

Note that I had to fight with the -DargLine a LOT to get the quotes in the right place, and I had no idea that the list of arguments is done with commas.

I tried:

-DargLine='-Pwindows,build-machine -DaltDeploymentRepository=ourrepo' which filed, considering everything after the first comma to be another part of the profile name somehow.

Clear instructions are needed to help people construct these arglines :)

**Comment by glianeric** [comment]
It turns out that what I did did not work correctly:  While the profiles are passed on correctly, the deploy plugin complains that -DaltDeploymentRepository=ourrepo was not passed on correctly.

**Comment by glianeric** [comment]
No matter what I try, I cannot get this to work:

mvn -B -X gitflow:release-start gitflow:release-finish -DallowSnapshots=true -DskipTestProject=true -DargLine='-Pwindows,build-machine -DaltDeploymentRepository=ourrepo'

Let's go over the variations that I've tried:
**1)** -DargLine=-Pwindows,build-machine -DargLine=-DaltDeploymentRepository=ourrepo

results in the last -DargLine being set

**2)** -DargLine='-Pwindows,build-machine -DargLine=-DaltDeploymentRepository=ourrepo'

results in an error like:  

[WARNING] The requested profile "build-machine -DaltDeploymentRepository=ourrepo" could not be activated because it does not exist.

I've tried a whole bunch of other variations, all of them unsuccessful.

**Comment by glianeric** [comment]
After much trial, the solution for me in the end was to add code to strip the first and last single quote (not all quotes) from the argLine string and submit that to your maven command constructor.

The PR will come soon.

In effect you can submit multiple arguments on argLine by suplying, say:

-DargLine='-Pwindows,build-machine -DargLine=-DaltDeploymentRepository=ourrepo'

and the command constructor will pick it up as
mvn clean install -Pwindows,build-machine -DargLine=-DaltDeploymentRepository=ourrepo

instead of 

mvn clean install '-Pwindows,build-machine -DargLine=-DaltDeploymentRepository=ourrepo'

**Comment by aleksandr-m** [comment]
It is the same as in direct command line parameters. No commas, just spaces.
