### ISSUE TITLE
It looks like "versionDigitToIncrement" property doesn't work

### ISSUE THREAD

**Issue by mireczatko** [aleksandr-m/gitflow-maven-plugin#194]
In documentation states:
_The gitflow:release-finish and gitflow:release goals have **versionDigitToIncrement** parameter which controls which digit to increment in the next development version. Starts from zero. For example, if the release version is 1.2.3.4 and versionDigitToIncrement is set to 1 then the next development version will be 1.3.0.0-SNAPSHOT. If not set or set to not valid value defaults to increment last digit in the version._

I set it to 1 as in example, however after `gitflow:release` of version `0.2.0` there is development version `0.2.1-SNAPSHOT`

**Comment by glianeric** [comment]
It works correctly for me, although I use a release-start/finish workflow, and not the singular 'release' goal.  Have you experimented at all to see if release-start/finish will work correctly instead of just release?

**Comment by mireczatko** [comment]
I am closing the issue, it was my fault, now everything seems to work as expected...
