### ISSUE TITLE
fetch branches from remote on "-finish" goals

### ISSUE THREAD

**Issue by mireczatko** [aleksandr-m/gitflow-maven-plugin#196]
it would be much easier to run "-finish" goals for user who didn't start it (doesn't have e.g. release branch checked out locally) when fetch of remote branches is performed before search for required branch(release branch e.g.) Perfect example: only some users are allowed to push to master. Someone starts release and checks if everything's OK but someone else have to finish it.

**Comment by MarkVMk2** [comment]
Another example: jenkins builds - "start" and "finish" goals are being executed with different jobs

**Comment by aleksandr-m** [comment]
@mireczatko @MarkVMk2 I've implemented this for `release-finish` goal for now. Not sure whether there is need to do this in the others goals.

**Comment by mireczatko** [comment]
@aleksandr-m great, thank you. I think hotfix-finish is almost same scenario

**Comment by MarkVMk2** [comment]
It useful for all -finish goals - i had cases when plugin was unable to find release, hotfix or feature branch and several times it failed due to missing develop because it was fetched to HEAD

**Comment by aleksandr-m** [comment]
@mireczatko @MarkVMk2 `1.14.0` is out with fetching remote release branch in `release-finish` goal.
