### ISSUE TITLE
Missing Flow :: Bugfix flow

### ISSUE THREAD

**Issue by frederic-gendebien** [aleksandr-m/gitflow-maven-plugin#197]
As a user I would like to create bugfix on develop, I know that I could create a feature, but semantically speaking this is not a feature, just a bugfix on the development version.

Do you plan to do this, or not at all?

**Comment by aleksandr-m** [comment]
@frederic-gendebien What difference from the feature branch do you expect in the bugfix?

**Comment by frederic-gendebien** [comment]
Glad you ask,

The hot fix is based on the master branch because something when  wrong in the production environment (typically…) but a bug fix is based on the develop branch. Typically, a feature A has been merged into develop branch, but during the demo or further investigations, it appeared that the feature has bugs, so we create bug fix because semantically speaking it is not a feature. So, when it is over it is just merged into develop, like feature branches, but for reports it is really interesting to make them 2 difference flows following 2 different Jira flows...

This is something that exists in the updated gitflow (avh version) you should have a look!

git flow bugfix start <name>
git flow bugfix finish

Kind regards,

Frederic Gendebien

**Comment by aleksandr-m** [comment]
@frederic-gendebien I will. But can you tell what do you want from bugfix branch that feature branch doesn't have? Just naming? Also see https://softwareengineering.stackexchange.com/questions/307360/where-do-bugfixes-go-in-the-git-flow-model

**Comment by frederic-gendebien** [comment]
Basically just naming yes… We have a special trigger when a bugfix is resolved. Testers are asked to retest the buggy scenario automatically, as we are using gitlab, we can trigger a special pipeline based on branch name. That’s why bugfix/<scenario> would be handy.

**Comment by aleksandr-m** [comment]
@frederic-gendebien  This can be achieved with [ability to set `gitFlowConfig` properties from the command line](https://github.com/aleksandr-m/gitflow-maven-plugin/commit/f1adadc44b22895035bdb8cd4d49c748582a515b). Use `mvn gitflow:feature-finish -DgitFlowConfig.featureBranchPrefix=bugfix/` to change feature branch prefix to `bugfix/`.
