### ISSUE TITLE
[FR] Enter commit message for Tag

### ISSUE THREAD

**Issue by stilnox255** [aleksandr-m/gitflow-maven-plugin#199]
We use the version-tag-commit-message, generated for the release, to write some changelog-information. In other Projects we use "git flow release finish <version>" and the user gets promted to enter a commit message for the tag being generated.

However, gitflow-maven-plugin just writes the default message (specified in pom.xml) as commit-message.

Is there a possibility to use something simmilar to 
```
mvn gitflow:release -DtagReleaseMessage="I am a change log"
```
or 
```
mvn gitflow:release -DtagReleaseMessage
```
and the user will get propted by the default editor to enter a commit message (like it's done with git flow)?

**Comment by aleksandr-m** [comment]
Yes, use `commitMessages.tagReleaseMessage`.
```
mvn gitflow:release-finish -DcommitMessages.tagReleaseMessage="Tag message"
```
