### ISSUE TITLE
Problem with maven release > 3.0.5

### ISSUE THREAD

**Issue by blardje** [aleksandr-m/gitflow-maven-plugin#20]
Problem to use this project with a maven release version > 3.0.5.
In these new versions, the mvn.bat has been rename to mvn.cmd

Could you please check either if an mnv.bat or mvn.cmd exists when using this plugin.

Thank you very much for your help and for this wonderful project !

Krgds,
Jerome

**Comment by aleksandr-m** [comment]
Actually, it is already fixed by [5f19e77](https://github.com/aleksandr-m/gitflow-maven-plugin/commit/5f19e774df293af8fc3ddd8cb463810f1b6bd346) commit.
Meanwhile you can use `mvnExecutable` parameter to override executable name.
( Creating copy of mvn.cmd and renaming it to mvn.bat also works. :) )
