### ISSUE TITLE
Ignoring SNAPSHOTS imported from BOM using dependencyManagement

### ISSUE THREAD

**Issue by rjakubco** [aleksandr-m/gitflow-maven-plugin#200]
I was trying to use the plugin on project that is using BOM in dependencyManagement that itself contains version SNAPSHOT and also each dependency defined in the BOM has version with SNAPSHOT. Running `gitflow:release-start` on version 1.13.0 results in successful snapshot check, which is wrong as SNAPSHOT dependencies are imported.

Our project looks somethig like this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>dt.sdp.service</groupId>
    <artifactId>adapter</artifactId>
    <version>1.1.1-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>adapter</name>
    <parent>
        <groupId>dt.sdp.commons</groupId>
        <artifactId>sdp-parent</artifactId>
        <version>2.7.0</version>
    </parent>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>dt.sdp.commons</groupId>
                <artifactId>service-commons-bom</artifactId>
                <version>1.7.2-SNAPSHOT</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
          <dependency>
            <groupId>dt.sdp.commons</groupId>
            <artifactId>service-commons-api</artifactId>
        </dependency>
        <dependency>
            <groupId>dt.sdp.commons</groupId>
            <artifactId>service-commons-metrics</artifactId>
        </dependency>
    </dependencies>
</project>
```

And the BOM looks like this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>dt.sdp.commons</groupId>
    <artifactId>service-commons-bom</artifactId>
    <packaging>pom</packaging>
    <version>1.7.2-SNAPSHOT</version>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>dt.sdp.commons</groupId>
                <artifactId>service-commons-exception</artifactId>
                <version>1.7.2-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>dt.sdp.commons</groupId>
                <artifactId>service-commons-api</artifactId>
                <version>1.7.2-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>dt.sdp.commons</groupId>
                <artifactId>service-commons-metrics</artifactId>
                <version>1.7.2-SNAPSHOT</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
```

I was checking the code and debugging the plugin and it seems there is a bug in `AbstractGitFlowMojo` in `checkSnapshotDependencies()` methd as it is reading the pom.xml `Model` from the file itself and doesn't use resolution of maven when it is building the project:
```java 
protected void checkSnapshotDependencies() throws MojoFailureException {
        getLog().info("Checking for SNAPSHOT versions in dependencies.");

        List<String> snapshots = new ArrayList<String>();
        List<String> builtArtifacts = new ArrayList<String>();

        List<MavenProject> projects = mavenSession.getProjects();
        for (MavenProject project : projects) {
            final Model model = readModel(project);

            builtArtifacts.add(model.getGroupId() + ":" + model.getArtifactId() + ":" + model.getVersion());

            List<Dependency> dependencies = model.getDependencies();
            for (Dependency d : dependencies) {
                String id = d.getGroupId() + ":" + d.getArtifactId() + ":" + d.getVersion();
                if (!builtArtifacts.contains(id) && ArtifactUtils.isSnapshot(d.getVersion())) {
                    snapshots.add(model + " -> " + d);
                }
            }
        }

        if (!snapshots.isEmpty()) {
            for (String s : snapshots) {
                getLog().warn(s);
            }
            throw new MojoFailureException(
                    "There is some SNAPSHOT dependencies in the project, see warnings above. Change them or ignore with `allowSnapshots` property.");
 ```

When debugging the plugin on my code then `model.getDependencies()` returns dependencies with versions set to `null`. I fixed it dirty and quick with calling `project.getDependencies()` as the project object has already all dependencies resolved with correct versions. This solved my issue when using the plugin on my project, but maybe it can break some other cases... but in my opinion the dependencies will be always correct when they are fetch from project object. 

Wanted to ask if this behavior is wanted or if should I create some better fix and make PR to fix this problem? Or maybe if I am using the plugin wrong or forget to set some parameter? :)

**Comment by aleksandr-m** [comment]
It was changed because of #169. Some better way to fix it would be great.

**Comment by cidus** [comment]
This also occurs when dependency version is set using properties.

This will be properly checked:
`
	<dependencies>
		<dependency>
			<groupId>world.hello</groupId>
			<artifactId>dummy-library</artifactId>
			<version>1.0.0-SNAPSHOT</version>
		</dependency>
	</dependencies>
`

This will not:
`
	<properties>
		<dummy-library.version>1.0.0-SNAPSHOT</dummy-library.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>world.hello</groupId>
			<artifactId>dummy-library</artifactId>
			<version>${dummy-library.version}</version>
		</dependency>
	</dependencies>
`

**Comment by cidus** [comment]
I replaced readModel with reloadProject which uses ProjectBuilder in order to recompute all project info, it should resolve transitive dependencies and property versions.
PR https://github.com/aleksandr-m/gitflow-maven-plugin/pull/204
