### ISSUE TITLE
Passing gitflow config values while executing a goal

### ISSUE THREAD

**Issue by ArpitSen** [aleksandr-m/gitflow-maven-plugin#203]
Hi,
Is there a way to pass a value for the gitflow config key while executing a goal??
Something like
```
mvn -B com.amashchenko.maven.plugin:gitflow-maven-plugin:1.13.0:release-finish -DgitFlowConfig.versionTagPrefix="RC_"
```
This will prefix the tag with **"RC_"**, to indicate that the build is a *Release Candidate* and any bugs can still be fixed before the final artifact is moved to production.

Calling the plugin with fully qualified name helps us keeping the plugin updates separate from the actual pom file. Also a single pipeline script can be used across various projects and the tag names can be customized per project.

**Comment by ldeck** [comment]
@ArpitSen did you find an answer to this?

**Comment by srinath45** [comment]
@ArpitSen @ldeck Did you find, how to use  **-DgitFlowConfig** parameter ?

**Comment by ldeck** [comment]
@srinath45 no. Did you?

**Comment by srinath45** [comment]
Nope. Are you doing any alternatives to update gitFlowConfig, other than from POM.xml file

**Comment by ldeck** [comment]
@srinath45 I was kicking the tyres, so to speak, for Git Flow and the gitflow-maven-plugin. Not being able to configure the behaviour externally, I'm looking at alternatives. e.g., using the maven versions plugin directly and git itself otherwise.

**Comment by aleksandr-m** [comment]
Implemented in https://github.com/aleksandr-m/gitflow-maven-plugin/commit/f1adadc44b22895035bdb8cd4d49c748582a515b.
