### ISSUE TITLE
problem with inherited groupid in multi module projects

### ISSUE THREAD

**Issue by wumpz** [aleksandr-m/gitflow-maven-plugin#206]
I have a multi module project, e.g.

    A
       ->  C
       ->  D

with D has a dependency to C.
Module C and D are inheriting the groupid from A (there is no groupid tag within the poms of C and D). 

All of my modules have the same version 1-SNAPSHOT and now I want to release to version 1.

Now gitflow-maven-plugin gives me an error while checking for SNAPSHOT versions in dependencies for D (it has a SNAPSHOT dependency to C). 

This does not happen, if I specify the groupid in C within Cs pom.xml.

**Comment by aleksandr-m** [comment]
Can you try latest snapshot version of the plugin and see if it is already fixed.

**Comment by wumpz** [comment]
It could take a day or two til I can test it.

**Comment by wumpz** [comment]
Sorry. I am not able to test it, at least for some days.

**Comment by wumpz** [comment]
So I wanted to test it. Where is the latest developer build or SNAPSHOT?

**Comment by aleksandr-m** [comment]
```
git clone
mvn clean install
```

**Comment by wumpz** [comment]
Ok. I thought you were deploying the snapshot somewhere.

**Comment by aleksandr-m** [comment]
@wumpz `1.14.0` is released. Try it out.

**Comment by wumpz** [comment]
At first glance it looks good.
