### ISSUE TITLE
Semantic versioning for pom versions

### ISSUE THREAD

**Issue by mjordan79** [aleksandr-m/gitflow-maven-plugin#208]
Hello,
after reading the documentation, I still can't find a way for customizing generated POM versions with some prefixes while doing *-start operations. For example, assuming I want to start a release with gitflow:release-start, I would like to put the version 0.1.1-test in the POM instead of the default 0.0.1.
Obviously, after a gitflow:release-finish I still want to maintain the default 0.0.1 version for the tag in the master branch, along with the same POM version.

Is this possible?

**Comment by aleksandr-m** [comment]
Feature name will be appended to version in `feature` goals by default. Is that what you are looking for?

**Comment by mjordan79** [comment]
> 
> 
> Feature name will be appended to version in `feature` goals by default. Is that what you are looking for?

Hello Aleksandr, thanks for the reply. Not for the feature branch, but for the release branch.
Basically, I would like to obtain the same effect we have now for the feature branch.
Assuming the release branch is configured with release/, I obtain the branch release/0.1.3 when doing a gitflow:release-start, but the maven version in the POM is 0.1.3. Would be possible to configure the plugin in order to change this version, for example 0.1.3-rc or 0.1.3-release, etc.?

**Comment by aleksandr-m** [comment]
What is your release flow looks like? You can set version with some qualifier on start goal and later update it manually or discard release branch and start a new one.
