### ISSUE TITLE
merge behaviour after release-finish

### ISSUE THREAD

**Issue by schnappfuesch** [aleksandr-m/gitflow-maven-plugin#213]
I'm wondering if there is a way to change the behavior when finishing a release, so that we do not 

 - merge `release/1.3.0` to `master` and then
 - merge `release/1.3.0` to `develop` 
but instead
 - merge `release/1.3.0` to `master` and then
 - merge `master` to `develop`

as it is done by e.g. [gitflow script](https://github.com/nvie/gitflow) itself.
I mainly missing the tags on the `develop` branch. (Yes i could simply merge master into develop myself).

mvn gitflow:release-finish
...
[INFO] Checking out 'release/1.3.0' branch.
[INFO] Cleaning and testing the project.
**[INFO] Checking out 'master' branch.**
**[INFO] Merging (--no-ff) 'release/1.3.0' branch.**
[INFO] Creating '1.3.0' tag.
**[INFO] Checking out 'develop' branch.**
**[INFO] Merging (--no-ff) 'release/1.3.0' branch.**
...

Cheers and thanks for the tool!

**Comment by aleksandr-m** [comment]
I doubt gitflow script merges master to develop.

Tags are mainly for releases. What tags do you want in the development branch?

**Comment by schnappfuesch** [comment]
Your are kind of right - git flow does not directly merges `master` back into `develop` but 'only' merges the just created tag back into `develop`.

    mkdir foo && cd foo && git flow init -d
    touch foo1 && git add foo1 && git commit -m "foo1 added"

    git flow release start 1.0.0
    touch foo2 && git add foo2 && git commit -m "foo2 added"

    git checkout develop
    touch foo3 && git add foo3 && git commit -m "foo3 added"

    git flow release finish '1.0.0'
    ....
    Summary of actions:
    - Release branch 'release/1.0.0' has been merged into 'master'
    - The release was tagged '1.0.0'
    - Release tag '1.0.0' has been back-merged into 'develop'
    - Release branch 'release/1.0.0' has been locally deleted
    - You are now on branch 'develop'

I like to see the release tags, when working on develop, as it gives me a clearer idea of what has happened in the past.

**Comment by aleksandr-m** [comment]
@schnappfuesch 
Seems like avh version indeed merges tag/master to develop. Can you tell a bit more what benefits does it bring to you to merge it that way? What are you using to see branch history?

**Comment by schnappfuesch** [comment]
Hi @aleksandr-m,

sorry for the slow response, I was away.

The main reason why I would like to have this feature is to get a better overview of what happened since the last release.

We have a lot of smaller components that will be released a few times a year and I'm regularly asked questions by colleagues responsible for those components.
Of course I could look out for merge commits, but a tag would make it easier for me to get a clearer understanding of what really happened.

**Comment by pennajenna** [comment]
Is there a workaround for this or will this be considered for a fix?  Its a need for our software lifecycle, so I'll need to figure it out or a possible workaround.

**Comment by aleksandr-m** [comment]
@pennajenna I'll look into this.

**Comment by pennajenna** [comment]
@aleksandr-m  --> I just submitted a PR for this:  https://github.com/aleksandr-m/gitflow-maven-plugin/pull/291

**Comment by aleksandr-m** [comment]
Similar like avh gitlfow handles this now tag or production branch will be merged to develop. To restore previous behavior and merge release branch use `noBackMerge` parameter.

**Comment by aleksandr-m** [comment]
`1.18.0` is released.

**Comment by DManstrator** [comment]
Sorry if this is the wrong place to ask but what is the advantage of merging the master into the develop over merging the release branch into the develop? I googled for it but couldn't find an answer there.

And are there any downsides to this approach? This is a breaking change according to the release notes so I assume there are some downsides.

**Comment by aleksandr-m** [comment]
@DManstrator Read this issue and/or other duplicates for the reasoning. It is marked as breaking change because the default behavior has changed.

**Comment by DManstrator** [comment]
Thanks for the hint to read the linked issues. I have actually read this issue but didn't get quite the reason, but got it with #321.

I actually think that GitLab doesn't treat tags correctly since they seem not to be branch-related but repository-related there. This was also confusing me since it looked like the tags were already correct before this change was applied. Nevertheless, this is now really unrelated to this issue, I will keep it since it fixes an issue and is approved.

Thank you. :)

**Comment by yashkolte3** [comment]
@aleksandr-m there would still be a problem where teams would need a tag to be created but want the `master` to be merged to `develop` instead of the `tag`. Merging tags creates `foxtrot-merge` which is discouraged by Atlassian https://www.atlassian.com/blog/it-teams/stop-foxtrots-now

**Comment by yashkolte3** [comment]
For whoever looking for a similar solution, I found a clean way to achieve this: 
use `noBackMerge=true` to enforce merging back `release` branch to `develop` with `releaseRebase=true`. This will prevent the `master` and `develop` branches from divergence, prevents foxtrot merges and keeps the history (along with tags on develop) very neat & clean.

e.g. `mvn com.amashchenko.maven.plugin:gitflow-maven-plugin:1.21.0:release-finish -B -DargLine='-DprocessAllModules' -DnoBackMerge=true -DreleaseRebase=true`
