### ISSUE TITLE
underlying Maven commands ignoring root Maven settings

### ISSUE THREAD

**Issue by mariomartinezricston** [aleksandr-m/gitflow-maven-plugin#214]
I am unable to use the plugin via our build management server (team city). 
We have a maven settings.xml file hosted in a none-default location,which contains multiple configurations, including our nexus repository. The teamcity build pass this argument to the maven step:  "mvn clean gitflow:release-start <<team city maven arguments>>"

When executing the plugin, the internal maven commands fails with an error: 
[ERROR] Unresolveable build extension: Plugin ... or one of its dependencies could not be resolved.

It seems that the underlying commands are ignoring the arguments / settings  provided within the "mvn gitflow:release-start" execution. Moreover, is not even accessing the local repository.

I have been trying to trick the inner maven commands trying to pass the settings location: "-s <<path.to.settings.xml>>" and also, trying to force the usage of the local none default repository "-DargLine=-Dmaven.repo.local=<<path.to.local.repo>>" with no luck.

How to maintain all the settings between the root maven call and the underlying maven commands?

**Comment by aleksandr-m** [comment]
Use `argLine` parameter to pass configuration to the underlying Maven commands.
Try
```
mvn clean gitflow:release-start -DargLine='-s path'
```

**Comment by mariomartinezricston** [comment]
Teamcity was passing the setting location via a new maven parameter. I could make it work with inline configuration:

`         <configuration>
          <argLine>--settings=${teamcity.maven.userSettings.path}</argLine>
        </configuration>`
