### ISSUE TITLE
releasing from aggregator pom?

### ISSUE THREAD

**Issue by GaborVarga** [aleksandr-m/gitflow-maven-plugin#215]
Is there a way to release modules from an aggregator pom which is not the parent of the modules? And one more twist: the modules have 2 different parents where parent A is the child of parent B.

**Comment by injecto** [comment]
I checked the first case: versions of non-child submodules doesn't bump on release.

**Comment by NetForce1** [comment]
I am experiencing the same problem. It looks like this can be solved by passing `-DprocessAllModules=true` to the set-version command here https://github.com/aleksandr-m/gitflow-maven-plugin/blob/625506a5483ebaea6d6396e9a70a1e296e2626fb/src/main/java/com/amashchenko/maven/plugin/gitflow/AbstractGitFlowMojo.java#L1044. I don't know though if there are any downsides to making this the default or whether a configuration property would be needed.

**Comment by aleksandr-m** [comment]
@NetForce1 @GaborVarga Can someone create a test project?

**Comment by NetForce1** [comment]
https://github.com/NetForce1/repro-gitflow-maven-plugin-215/tree/develop/gitflow-test

**Comment by aleksandr-m** [comment]
@NetForce1 Thank you for the repro. I can confirm that using `-DprocessAllModules=true` with your project structure works as expected.

It didn't help in [similar issue](https://github.com/aleksandr-m/gitflow-maven-plugin/issues/130), guess there are some differences in project model.

Actually, the `processAllModules` option can be toggled using `argLine` parameter like so:
`-DargLine="-DprocessAllModules"`.
