### ISSUE TITLE
Have consistent version for tag(git tag) and release version(pom.xml)

### ISSUE THREAD

**Issue by rach1416** [aleksandr-m/gitflow-maven-plugin#225]
This is not exactly an issue rather looking for more information. I was just working on using semantic versioning for a project and wanted to keep the version consistent with both the git tag and the version in pom.xml
I have been using the command as below for creating a release

mvn gitflow:release -B DreleaseVersion=1.0.0

Not using a branch based model and keeping both the <developmentBranch> and <productionBranch> the same.

However, when the command is run it creates a tag '1.0.1` and release version(pom.xml) `1.0.2`
But I would want both the tag and release version to be `1.0.1`

Can anyone suggest on how I would be able to do that? It would be really helpful.

**Comment by aleksandr-m** [comment]
Where tag points to? It should be two commits one with the tag and the other with incremented version to develop further.
You can use `developmentVersion` to set next version.
