### ISSUE TITLE
When starting new release "Release branch already exists. Cannot start release."

### ISSUE THREAD

**Issue by mireczatko** [aleksandr-m/gitflow-maven-plugin#23]
When starting new release with `mvn gitflow:release-start` I receive an exception because of old-release branch... "Release branch already exists. Cannot start release." In fact, plugin refuses to create branch "release/1.0.1" because there is branch "release/1.0.0" already existing.
What is the correct workflow in case there are many installations of the product with different release versions so all release branches should be maintained? I use `<keepBranch>true</keepBranch>` because of that. However it causes this exception...
Btw. how is it possible to set `<keepBranch>true</keepBranch>` only for `release`, `release-start` and `release-finish` goals and keep it false for other goals in parent pom?  It seems like goal `release` doesn't create release branch. It would be nice if it did in case keepBranch=true.

**Comment by aleksandr-m** [comment]
1. Currently you can't set same parameter with different values for different goals, but it is on my todo list.
2. There is no `keepBranch` for `release` goal. The point of the `release` is it doesn't create separate branch for the release. You can execute `mvn gitflow:release-start gitflow:release-finish` in one go to create a release branch and merge it.
3. What do you mean by *in case there are many installations of the product*? Are you supporting multiple versions of your product simultaneously and want to use release branches as long running support branches? Can you elaborate on your workflow.

**Comment by mireczatko** [comment]
Hi @aleksandr-m 
@ 2: it is only nice to have feature to create release branch in case `<keepBranch>true</keepBranch>` and would make real sense if we could have more release branches live side-by-side
@ 3: the workflow is pretty similar to well known http://nvie.com/posts/a-successful-git-branching-model/ Only difference is to not create hotfix branches from master but from "oldest" release branch where the bug appears. After fixing it merge it to all subsequent release branches, develop branch & master branch

**Comment by aleksandr-m** [comment]
In original nvie workflow release branch is dropped when it is merged to main branches and only one release branch is allowed at the time.
Maybe what you really need is [support branches](http://gitversion.readthedocs.io/en/latest/git-branching-strategies/gitflow-examples/#support-branches)?

This plugin aims to support various git workflows so adding goal(s) for support branches sounds like a good idea. Also it is relatively easy to add option to allow multiple release branches, but if support branch goal(s) will be added maybe it isn't needed. Wdyt?

**Comment by mireczatko** [comment]
yeah, this looks like what I really need. It is almost the same as what I call release branch. Only difference I noticed it is created from **master**. I think it is perfectly acceptable. This seems to be another view to same "problem". Now I see, support branch can be created anytime from release-tag. Looks great. Btw. thank you for the link, I never found this page so far. :)

**Comment by aleksandr-m** [comment]
@mireczatko Starting from the next release, `support` branches can be created by executing `support-start` goal. The `hotfix` goals were improved to support hotfixing `support` branches. :)

**Comment by mireczatko** [comment]
Great, @aleksandr-m, thank you for notice me :)

**Comment by aleksandr-m** [comment]
@mireczatko `1.5.0` is out.

**Comment by amitpatel1985** [comment]
$  git flow release start Test2
**_Fatal: There is an existing release branch 'Test1'. Finish that one first.**_

When I am trying to create release branch when there is already one release branch getting above error from Gitbash. any idea how to fix this

**Comment by aleksandr-m** [comment]
@amitpatel1985 In the original gitflow it can be only one release branch at a time. Have you read this discussion and know about support branches? Why do you need multiple release branches?

**Comment by amitpatel1985** [comment]
In our project we will have time between acceptance test completion & Release and during that time other changes come due to that it we need to create release 2nd branch after finishing feature.

**Comment by thamacher** [comment]
But I think this approach still does not work with github-flow. Because I have to run a job twice. First I also get a `Release branch already exists. Cannot start release.' and running it for the 2nd time then works.

**Comment by aleksandr-m** [comment]
@thamacher What do you mean by that?

**Comment by kuhajeyan** [comment]
we are maintaining multiple release branches, and we dont necessarily delete them once we merge to master. In this case, when we are trying to release-start, we get this "release xxxx already exists. Finish that first!". 

is there any parameter to suppress this existing version check?

**Comment by aleksandr-m** [comment]
Just rename them.

**Comment by kngmat004** [comment]
I really hope we could work on a separate config item to allow multiple release branches would be another plus for an already great plugin
