### ISSUE TITLE
Support interactive input for next development version

### ISSUE THREAD

**Issue by stefanseifert** [aleksandr-m/gitflow-maven-plugin#232]
Currently, it's not possible to pass in a next development version when using interactive mode.
There are two parameters to influence the logic that automatically detected the next development version (`digitsOnlyDevVersion` and `versionDigitToIncrement`), but it's not possible to specify a custom next version.

Some of our projects have a more complex version that does not work with the simple automatic increment mechanism. And sometimes it's just easier to type in e.g. "2.0.0-SNAPSHOT" for a major version change than figuring out how exactly `versionDigitToIncrement` did work to achieve the same.

maven-release-plugin and jgitflow-maven-plugin allow to pass in a custom version number interactively, but with a sensible default that can be accepted with just hitting return.

**Comment by aleksandr-m** [comment]
If you don't mind typing than you can use non-interactive mode.
Seems like another annoying "please hit enter" feature, most of the times, at least.

**Comment by stefanseifert** [comment]
true, but i consider it still helpful.
i'm doing a lof of releases per month and although in 90% of the cases hitting entry is the correct choice there are always special cases where it isn't. and then it's easier to remember these cases when the next development version is displayed for confirmation allowing to change it.

i've provided a PR #233 that introduced a new switch to enable this feature optionally, to not bother users who do not need it. WDYT?

**Comment by stefanseifert** [comment]
closing this in favor of https://github.com/aleksandr-m/gitflow-maven-plugin/issues/235
