### ISSUE TITLE
Is it possible to use Eclipse-embedded Maven with this plugin?

### ISSUE THREAD

**Issue by divStar** [aleksandr-m/gitflow-maven-plugin#234]
Awesome Maven-plugin - especially for automation purposes! Thank you!

Currently I use Eclipse to build the release. There is no dedicated external Maven installation on my system nor an entry in the PATH- or MAVEN_HOME-variables.

When I run the plugin, the build failes with an error stating that it could not find `mvn` anywhere (which is true). However: embedded Maven in Eclipse does exist and work - though it does not have a `mvn` script to start it with.

Is there a way to have it work with Eclipse-embedded Maven **or** specify the path to Maven/bin inside the `<configuration>` element or a parameter or something?

**Comment by aleksandr-m** [comment]
@divStar I don't think there is way to use eclipse embedded maven, but you can use maven wrapper if you want to.

Yes, you can set path to maven executable in configuration:
```
<mvnExecutable>path_to_maven_executable</mvnExecutable>
```
