### ISSUE TITLE
Release-finish : Remote branch is ahead of the local branch.

### ISSUE THREAD

**Issue by faulomi** [aleksandr-m/gitflow-maven-plugin#24]
Hello,

First, thank you for your great plugin, especially knowing than the famous jgitflow provided by Atlassian is not maintained anymore.

I just have a question, not really technically-oriented, but more about the workflow and its implications.

In my company, we are using git-flow in the following way :

1) On Jenkins, we start a release (using release-start in our case), and then publish the resulting branch. At this point, the artifact is deployed to the staging environment (Nexus and execution environment as well). Some modifications can be applied to this branch if some bugfixes are required (the artifact is in a Nexus staging repository, so it can be overwritten).

2) When we are done with the testing process (manually for now), we finish the release and can proceed with the merging/tagging phase.

The problem is that between steps 1) and 2), developers keep working on the develop branch, so when we execute release-finish, the local develop branch on Jenkins is not up to date anymore. By default, your plugin parameter fetchRemote is set to true, hence the failure with the message "Remote branch is ahead of the local branch". I guess this check is done to prevent any problem when you merge the release branch back to develop.

Therefore, I'm not sure that setting this parameter to false would solve my issue as it might fail later (during the push phase).

But I'm wondering whether integrating the following strategy option during the merge would help or not :
_git merge --strategy-option theirs_

So the flow would be the following on release-finish:

1) Pull the development branch (should be fast forwarded as we didn't commit anything)
2) Pull the release branch (in case some bugfixes were applied)
2) Merge release branch to master with  no-ff and tag
3) Merge release branch to development using the strategy-option "theirs"
4) Push master and development along with the tag

This way, we could also increment the develop snapshot version as soon as we start the release.

Honestly, I didn't test yet, but I'm about to. If you already tried out this solution, please let me know, I might miss something !

Thanks,

**Comment by aleksandr-m** [comment]
Thanks.

Using `theirs` potentially can lead to the result when some changes are discarded, which you don't want to be happen automatically. :)

There are some options, all with they own drawbacks. A few of them might be:
- don't commit to develop, use feature branches and merge afterwards
- test in develop not in release branch and release in one go (maybe even w/o separate branch)
- start release like you do it right now, but finish not from CI server and resolve any merge conflicts

**Comment by faulomi** [comment]
Hi Aleksandr, 

Thank you for your feedback.

I will go with 3) until my CI pipeline is fully operational (1 and 2 are quite incompatible with my use cases, especially in terms of Maven versioning).

Just for information, it might interest you, I'm using this gitflow-helper plugin in conjunction : https://github.com/egineering-llc/gitflow-helper-maven-plugin

So my goal is to use yours to handle the release steps and then benefit of the gitflow-helper features to automatically build/deploy/promote my artifacts.
