### ISSUE TITLE
Add useSnapshotInSupport parameter to gitflow:support-start

### ISSUE THREAD

**Issue by beatngu13** [aleksandr-m/gitflow-maven-plugin#250]
There are already the options [`useSnapshotInRelease`](https://aleksandr-m.github.io/gitflow-maven-plugin/release-start-mojo.html#useSnapshotInRelease) and [`useSnapshotInHotfix`](https://aleksandr-m.github.io/gitflow-maven-plugin/hotfix-start-mojo.html#useSnapshotInHotfix) to start a `release` (via `gitflow:release-start`) / `hotfix` (via `gitflow:hotfix-start`) branch with a snapshot version. Personally, I find this very helpful while working on a release or a hotfix.

I believe `support` branches are very similar, one might first has to work on a support release before actually releasing it. A snapshot qualifier helps to show this intent. Because of this, and since it fits well to the aforementioned `*-start` goals, I suggest to add a `useSnapshotInSupport` parameter to `gitflow:support-start`.

I'm also happy to help or submit a PR if desired.

**Comment by beatngu13** [comment]
@aleksandr-m thanks for picking this up – and sorry for not sticking to my promise of a PR. 🙏

**Comment by aleksandr-m** [comment]
@beatngu13  `1.16.0` is released.
