### ISSUE TITLE
Question about producing release and hotfixes from support branches

### ISSUE THREAD

**Issue by stephanedaviet** [aleksandr-m/gitflow-maven-plugin#253]
From my point of view, _support_ branches is equivalent to _master_ but for legacy (supported) versions. I then expect all Maven Git Flow plugin to be able to handle the flow towards a _support_ branch as the production one.

I have tested this command without success: `mvn gitflow:hotfix-finish -DuseSnapshotInHotfix=true -DgitFlowConfig.productionBranch=support/1.0.0 -DskipMergeDevBranch=true` to finish a hotfix on my branch `support/1.0.0` without merging in on a dev branch (no dev branch on _support_ version). But the plugin keep doing actions toward `master`.

Am I doing something wrong?

**Comment by aleksandr-m** [comment]
@stephanedaviet You need to start hotfix from the support branch.

**Comment by aleksandr-m** [comment]
Feel free to re-open if you still experiencing some issues with this.

**Comment by stephanedaviet** [comment]
I confirm that the bug is gone in my latest test with your advice. Thanks.
