### ISSUE TITLE
Canary Deployment

### ISSUE THREAD

**Issue by njchandu** [aleksandr-m/gitflow-maven-plugin#255]
Hi,

I am trying to follow gitflow and ran into this issue. I'm trying to hold on to the release branches mainly because we mostly do canary deployment before deploying to all the instances and they are two different processes. First a canary deployment takes place, we monitor the metrics for 1 to 7 days depending on the feature and deploy to all the regions and hosts upon validation.

I got this error when I try `release-finish`

> 23:14:34  [ERROR] Failed to execute goal com.amashchenko.maven.plugin:gitflow-maven-plugin:1.14.0:release-finish (default-cli) on project smw-java-gitflow: release-finish: More than one remote release branch exists. Cannot finish release. -> [Help 1]

What should I do in this case. Thanks in advance.

**Comment by aleksandr-m** [comment]
Why do you need a second release branch? Why not to use the same branch? Or better yet same artifacts in staging and production?

**Comment by njchandu** [comment]
Yes, that actually makes sense. Let me think about it. I will update this ticket in a day or two, thanks.

**Comment by njchandu** [comment]
Hi @aleksandr-m, I agree with your thought process on not needing a second release branch. Would it be better to throw this error during a release:start instead of release:finish?

I am trying gitflow for the first time in our org. First pass was a super duper mess because of conflicts and not thinking the process through completely. 

I'm trying to integrate it with CI. Could you please let me know if there are any fundamental issues with this approach.

There are 2 Jenkins jobs:
- First job cuts the release or hotfix branch.
- Second one is a multi-branch pipeline job. After a successful deployment, it will run the release-finish/hotfix-finish command. If there are any conflicts they should be resolved manually.

**Comment by aleksandr-m** [comment]
@njchandu 
> Would it be better to throw this error during a release:start instead of release:finish?

It is already there.
