### ISSUE TITLE
versionDigitToIncrement ignored during release

### ISSUE THREAD

**Issue by beatngu13** [aleksandr-m/gitflow-maven-plugin#256]
Using the following plugin config:

```xml
<plugin>
	<groupId>com.amashchenko.maven.plugin</groupId>
	<artifactId>gitflow-maven-plugin</artifactId>
	<version>1.14.0</version>
	<configuration>
		<versionDigitToIncrement>1</versionDigitToIncrement>
	</configuration>
</plugin>
```

And the following command line:

```text
$ mvn gitflow:release -B -DversionDigitToIncrement=0
```

The command-line parameter `-DversionDigitToIncrement=0` seems to be ignored as the incremented version digit is still 1.

My assumption was that command-line parameters overwrite the plugin configuration, so that the default is 1 but when there is a major release, one can supply the aforementioned parameter?

**Comment by aleksandr-m** [comment]
For better or worse this is how maven works. See https://issues.apache.org/jira/browse/MNG-4979

**Comment by beatngu13** [comment]
Ah, I see. So one could solve this by using a property. Thx for pointing to that issue!
