### ISSUE TITLE
use annotated tags with release

### ISSUE THREAD

**Issue by mzatko** [aleksandr-m/gitflow-maven-plugin#259]
regarding git guide and best practices annotated tags should be used with release and only annotated tags should be pushed to remote repos

**Comment by aleksandr-m** [comment]
@mzatko Plugin already creates annotated tags.

https://github.com/aleksandr-m/gitflow-maven-plugin/blob/af7a8a1e3d87bad2d1aa6a5ccf05d9443aaaeedb/src/main/java/com/amashchenko/maven/plugin/gitflow/AbstractGitFlowMojo.java#L783-L796

**Comment by mzatko** [comment]
I see, my fault then.
