### ISSUE TITLE
system properties are not propagated down to maven build itself

### ISSUE THREAD

**Issue by mzatko** [aleksandr-m/gitflow-maven-plugin#261]
as example:
`mvn -Dcustom.system.property gitflow:hotfix-finish`

the property `custom.system.property` is not propagated down to build itself, in my case it is for build during gitflow:hotfix-finish goal but it is probably general bug
It is not provided in main project build (**[INFO] Cleaning and testing the project.**)
nor when running postHotfixGoals(probably postReleaseGoals as well)
nor during additional build of develop branch when everything's finished

just side info: property is used to activate profile...

**Comment by aleksandr-m** [comment]
@mzatko Use `argLine` - https://github.com/aleksandr-m/gitflow-maven-plugin#maven-arguments

**Comment by mzatko** [comment]
yeah, it works this way, thank you
