### ISSUE TITLE
using HEAD-SNAPSHOT for development

### ISSUE THREAD

**Issue by vegegoku** [aleksandr-m/gitflow-maven-plugin#266]
Is it possible to have the development branch to be fixed as `HEAD-SNAPSHOT` instead of `x.x.x-snapshot` for example.
and still be able to release with `x.x.x` versions.

**Comment by aleksandr-m** [comment]
Have you tried this?

**Comment by aleksandr-m** [comment]
You can try with `skipUpdateVersion`.
