### ISSUE TITLE
rror injecting: com.amashchenko.maven.plugin.gitflow.GitFlowReleaseStartMojo java.lang.NoClassDefFoundError: org/apache/maven/shared/release/versions/VersionParseException

### ISSUE THREAD

**Issue by narin-kura** [aleksandr-m/gitflow-maven-plugin#27]
how to fix the above issue

rror injecting: com.amashchenko.maven.plugin.gitflow.GitFlowReleaseStartMojo
java.lang.NoClassDefFoundError: org/apache/maven/shared/release/versions/VersionParseException

**Comment by aleksandr-m** [comment]
Which Maven version are you using?
See this [A required class was missing while executing org.apache.maven.plugins:maven-war-plugin:2.1.1:war](http://stackoverflow.com/q/18442753/1700321).

**Comment by narin-kura** [comment]
i am using maven 3.2.5

**Comment by aleksandr-m** [comment]
@narin-kura  Was you able to solve this issue with solutions given in linked question?

**Comment by narin-kura** [comment]
Nope nothing solved i tried to re download all the versions but nothing helped  , maven release plugin and maven release manager versions are 2.5.3

**Comment by aleksandr-m** [comment]
Remove maven release plugin from your local .m2 folder and run again.
