### ISSUE TITLE
Can hotfix-start and release-start allow branch name to differ from version

### ISSUE THREAD

**Issue by kraymondksc** [aleksandr-m/gitflow-maven-plugin#275]
I'm currently looking to migrate to this plugin. We're currently using the jGitFlow plugin.  When using the following command:
`mvn -B gitflow:hotfix-start -DuseSnapshotInRelease=true -DhotfixVersion=1.3.1 useSnapshotInHotfix=true -DpushRemote=true`

The following will create a branch named hotfix-1.3.1 but with a pom version as `<version>1.3.1</version>`.  For us, the version ideally would have "-SNAPSHOT" appended to the version. In order to get the version to have "-SNAPSHOT", the version would need to be specified as: hotfixVersion=1.3.1-SNAPSHOT.  This has the side effect of the branch being named hotfix-1.31-SNAPSHOT.  We would like the branch name to not have the -SNAPSHOT version in it.  I was wondering if it would be possible to add an additional parameter that could control this behavior.

I suspect this happens also with release but have yet to try it.

**Comment by aleksandr-m** [comment]
Use `useSnapshotInHotfix` parameter.

**Comment by kraymondksc** [comment]
Apologies, I did specify that parameter in my command but realized that I missed prefixing with `-D`
