### ISSUE TITLE
customize hotfix and support branch names

### ISSUE THREAD

**Issue by eagleyes** [aleksandr-m/gitflow-maven-plugin#276]
I have the following naming convention: 
major.Minor.Patch number and everythign is getting tagged as that on master (i.e. 1.0.5)

When I try to create the support branch it is forcing me to create the branch name from the tag name , which will create a support branch called support/1.0.5 .

In fact the way we are using the support branch is that we will create the branch for the 1.0 version and once we release under that support it will become 1.0.6,1.0.7 etc... 

Therefore the support branch name should really be support/1.0 and NOT support/1.0.5.

is it possible to customize the name of the support branch instead of hardcoding it to the tag name?

I have the same problem with hotfix , I want to customize the name so that it is hotfix/jira-abc instead of hotfix/support/1.0.5/1.0.6 (which is not the best naming for my liking)

Please let me known if I am missing something or if there is anything I can do !

thanks

**Comment by aleksandr-m** [comment]
Added `supportBranchName` to support-start goal. It is more complicated with hotfix support naming. Support branch prefix must be included in the branch name to know where changes should be merged.
