### ISSUE TITLE
create pull request from feature:finish

### ISSUE THREAD

**Issue by Motyim2** [aleksandr-m/gitflow-maven-plugin#277]
Hi folks,
could this plugin create a pull request from a feature branch to the development branch rather than apply merge directly ?

**Comment by aleksandr-m** [comment]
What do you mean?

**Comment by baedorf** [comment]
I'm not the creator of this issue, but I also have the same question.
Normally, I would implement a feature and a colleage should review the implementation before merging the feature into develop.
After finishing the review, the plugin should be executed to merge feature into develop.
Is this possible?
