### ISSUE TITLE
Release-start and release-finish doesn't check for SNAPSHOT dependencies on submodules

### ISSUE THREAD

**Issue by nickstolwijk** [aleksandr-m/gitflow-maven-plugin#28]
I'm trying out the gitflow-maven-plugin and I'm encountering the following:

I have a project setup with a aggregator pom in the root, a configuration pom in configuration/ and various modules for the functionality, which all have the configuration pom as parent. In the configuration pom all the dependencies are under build/dependencies instead of build/dependencyManagement. This is because the dependencies of the configuration pom are added to the Tycho targetplatform.

If I run mvn gitflow:release-start on the aggregator pom, I see the logging "INFO : Checking for SNAPSHOT versions in dependencies.", but it finishes without seeing the SNAPSHOT-dependencies of the configuration pom. I believe this is because it checks only the dependencies of the aggregator project and not of the other projects in the <modules> tag.

Is this by design or should the check for snapshot stage also check the projects under the <modules> tag for SNAPSHOTS? (And the modules under the modules tag can have sub-modules, so it should be recursive if that is the case)

**Comment by aleksandr-m** [comment]
Currently it doesn't check for snapshots in modules. But it probably should. Let's see if getting projects from `MavenSession` will resolve it.

**Comment by Yeggstry** [comment]
Hi,

Is there any plans for including this change into a release? My company are currently evaluating various maven gitflow release plugins and really like that this is still being actively developed. This change would be a great help for us as we have a lot of multi-module maven projects in our codebase.

Thanks,

Lewis

**Comment by aleksandr-m** [comment]
Sure. It is good time to release. :) I'll try to do it in a next few days.

**Comment by aleksandr-m** [comment]
@nickstolwijk @Yeggstry 1.4.0 is released. Enjoy.

**Comment by Yeggstry** [comment]
Thanks a lot :)

**Comment by aleksandr-m** [comment]
@thaDude See https://github.com/aleksandr-m/gitflow-maven-plugin/issues/64. If you can create small example project it would help.
