### ISSUE TITLE
release-finish: misleading commit message

### ISSUE THREAD

**Issue by bannmann** [aleksandr-m/gitflow-maven-plugin#281]
When release-finish makes the final commit on the release branch before merging to master, the commit message is "Update for next development version" (the commit `e0ece71` below, marked in green):

![commits](https://user-images.githubusercontent.com/3303967/109397662-1b6a1a80-7938-11eb-9b31-4639fd1bb791.png)

That message is misleading because it is the same one that is used on develop as part of release-start (commit `6753f46`). I think the "correct" message for the `e0ece71` commit should be something like "Update release branch to production version".

Here are my settings:
```
<plugin>
    <groupId>com.amashchenko.maven.plugin</groupId>
    <artifactId>gitflow-maven-plugin</artifactId>
    <version>1.14.0</version>
    <configuration>
        <commitDevelopmentVersionAtStart>true</commitDevelopmentVersionAtStart>
        <useSnapshotInRelease>true</useSnapshotInRelease>
        <preReleaseGoals>package -DperformRelease=true</preReleaseGoals>
        <pushRemote>true</pushRemote>
        <commitMessagePrefix>[gitflow] </commitMessagePrefix>
    </configuration>
</plugin>
```

**Comment by aleksandr-m** [comment]
@bannmann Commit messages can be changed in pom.

```
<commitMessages>
  <releaseFinishMessage>Update release branch to production version</releaseFinishMessage>
  <releaseVersionUpdateMessage>Update for next development version</releaseVersionUpdateMessage>
</commitMessages>
```
