### ISSUE TITLE
Need ability to override GitFlowConfig and CommitMessages via CLI

### ISSUE THREAD

**Issue by kutsal** [aleksandr-m/gitflow-maven-plugin#284]
Have a particular use-case where (because our CI pipeline is using this plugin indiscriminately across all our Java projects) we need the ability to override the plugin configuration defaults via maven command-line even when the project being built does not reference this plugin. Right now `gitFlowConfig` cannot be specified via command-line. #263 attempts this, but since it's doing it in constructor, pom files override the configuration, which isn't how it should work with Maven -- _command-line_ overrides pom, not the other way around.

**Comment by aleksandr-m** [comment]
@kutsal 

> pom files override the configuration, which isn't how it should work with Maven

But it is.

I see what benefit it brings, but I'm not sure that going against Maven way is the best course of action.

**Comment by kutsal** [comment]
Given the following `pom.xml`

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>foo</groupId>
    <artifactId>bar</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <properties>
        <maven.compiler.release>11</maven.compiler.release>
    </properties>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.8.1</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
```

and executing `mvn -X clean compile` gives the following output:

```
[DEBUG] Configuring mojo 'org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile' with basic configurator -->
...
[DEBUG]   (f) project = MavenProject: foo:bar:1.0-SNAPSHOT @ /homes/x/x/pom.xml
[DEBUG]   (f) projectArtifact = foo:bar:jar:1.0-SNAPSHOT
[DEBUG]   (s) release = 11
...
[DEBUG] -- end configuration --
[DEBUG] Using compiler 'javac'.
```

However, running it with `mvn -X clean compile -Dmaven.compiler.release=15` does this (as I'd expect):

```
[DEBUG] Configuring mojo 'org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile' with basic configurator -->
...
[DEBUG]   (f) project = MavenProject: foo:bar:1.0-SNAPSHOT @ /homes/x/x/pom.xml
[DEBUG]   (f) projectArtifact = foo:bar:jar:1.0-SNAPSHOT
[DEBUG]   (s) release = 15
...
[DEBUG] -- end configuration --
[DEBUG] Using compiler 'javac'.
```

So the functionality in the attached PR does not go against Maven conventions at all.

**Comment by nicman42** [comment]
I did have a similar problem. I want to set the _developmentBranch_ on the command line.

My solution for this problem is as follows:

In the pom.xml define a variable with a default value:
```
<properties>
  <gitflow-maven-plugin.developmentBranch>develop</gitflow-maven-plugin.developmentBranch>
</properties> 
```

Use this variable in the gitFlowConfig:
```
<gitFlowConfig>
  <developmentBranch>${gitflow-maven-plugin.developmentBranch}</developmentBranch>
</gitFlowConfig>
```

The config can now be overwritten on the command line:
`mvn gitflow:feature-start -Dgitflow-maven-plugin.developmentBranch=feature/next-big-thing`
