### ISSUE TITLE
Automatically update property project.build.outputTimestamp at release time

### ISSUE THREAD

**Issue by Jurrie** [aleksandr-m/gitflow-maven-plugin#286]
I am trying to get my build [to be reproducible](https://maven.apache.org/guides/mini/guide-reproducible-builds.html). For this, you have to supply the `project.build.outputTimestamp` property. This property needs to be updated at release time.

The maven-release-plugin already does this. This is implemented in [cfcc8ca59e483](https://github.com/apache/maven-release/commit/cfcc8ca59e483227dcbff8935f3b95d1d3344c13). Maybe gitflow-maven-plugin can implement the same?

**Comment by aleksandr-m** [comment]
@Jurrie Thanks for pointing this out! 
Do you think `project.build.outputTimestamp` should be updated on `release-start` also, or only when finishing a release?

**Comment by Jurrie** [comment]
Hi @aleksandr-m, I don't know :) I'm currently trying to get our build to be reproducible, updating plugins etc. I'm not yet at the point where I want to update this property.

I think gitflow-maven-plugin should follow maven-release-plugin here as much as possible. The Maven guide states that the maven-release-plugin updates this property in the same commit where it updates the version. I don't actually know if the property will be updated again when the version is set to `-SNAPSHOT`.

**Comment by aleksandr-m** [comment]
`1.16.0` is released.
