### ISSUE TITLE
merge feature branch with squash should copy messages from squashed commits or give oportunity to set own commit message

### ISSUE THREAD

**Issue by alapierre** [aleksandr-m/gitflow-maven-plugin#287]
currently after 

```
mvn -DfeatureSquash=true gitflow:feature-finish
```

 commit message is only: feature/feature_name 

![image](https://user-images.githubusercontent.com/5985325/111308382-e6113c80-865a-11eb-9f1d-5fd140384d89.png)

**Comment by Karolok** [comment]
true, defining the commit name after squash would be a nice feature

Currently, to work around the problem, I turn off the automatic pushing of the commit after merging by:
`<pushRemote>false</pushRemote>`
next I change the name of the commit manually and push it manually

**Comment by aleksandr-m** [comment]
@alapierre @karolbryzgiel  1.17.0 is out.

**Comment by alapierre** [comment]
greate, thank you!

wt., 7 gru 2021 o 15:12 Aleksandr Mashchenko ***@***.***>
napisał(a):
