### ISSUE TITLE
Release-finish merge is merging release-branch into develop instead of master onto develop

### ISSUE THREAD

**Issue by pennajenna** [aleksandr-m/gitflow-maven-plugin#289]
https://github.com/aleksandr-m/gitflow-maven-plugin/blob/da562a0730e23e361107de965be61ab6bacff81f/src/main/java/com/amashchenko/maven/plugin/gitflow/GitFlowReleaseFinishMojo.java#L308

When using this, the release-finish is merging release-branch onto master and tagging correctly.  Then it merges release-branch onto develop.  This doesn't allow for the tag to be on develop.  Is there a reason for this?

**Comment by aleksandr-m** [comment]
@pennajenna Seems same as #213. Can you elaborate what benefit does it bring?

**Comment by pennajenna** [comment]
Yes, if you merge master into develop, the tag from master is on develop. The way it is now, develop doesn’t have the same tag

**Comment by pennajenna** [comment]
#213 reasons are exactly the same as mine, having that tag on develop is a necessity for me
Jenna

**Comment by pennajenna** [comment]
submitted a PR for this: https://github.com/aleksandr-m/gitflow-maven-plugin/pull/291

**Comment by pennajenna** [comment]
DUPLICATE of https://github.com/aleksandr-m/gitflow-maven-plugin/issues/213
