### ISSUE TITLE
[FR] Provide option to deploy to nexus on release-finish

### ISSUE THREAD

**Issue by laur89** [aleksandr-m/gitflow-maven-plugin#29]
It's quite likely that on `release-finish` one would like the tag to be deployed to nexus. At the moment it appears not to be the case and can't find an option to enable it.

Would this be a feature you'd consider?

**Comment by aleksandr-m** [comment]
There is some thought about executing custom commands during the release cycle in #13.
Contributions are welcome!

**Comment by laur89** [comment]
See PR #43

**Comment by aleksandr-m** [comment]
@laur89 Initial commit for allowing to run additional Maven goals is [here](https://github.com/aleksandr-m/gitflow-maven-plugin/commit/1e26c36077e91398638ba7b625810d55dc48aad8).
Please test and review.

**Comment by aleksandr-m** [comment]
Implemented in 9e57bb0.
