### ISSUE TITLE
can't finish feature with Java 11 version in project

### ISSUE THREAD

**Issue by Karolok** [aleksandr-m/gitflow-maven-plugin#290]
When i finishing feature, maven compiler can't compile the project because of java 11 functions in project. I saw that gitflow-maven-plugin has default java 1.7 version in maven compiler.
It would be nice to be able to define what java version the project should compile in

**Comment by aleksandr-m** [comment]
@Karolok It is working fine with jdk11. Post the error you're getting.

**Comment by Karolok** [comment]
I am using kotlin in my project and compilation by maven works, but during finish feature not because of two properties which are since JDK11

I have this error during finish feature:
![image](https://user-images.githubusercontent.com/25080975/115711203-8b62b300-a373-11eb-9d8e-aa36a325a26e.png)

**Comment by aleksandr-m** [comment]
@Karolok Try to build your project from the command line, not from your IDE, e.g. `mvn clean package`.

**Comment by Karolok** [comment]
From command-line `mvn clean package` working fine. And after that, plugin from command line work too. 
Before, I tried finish feature from IDE with maven and it not worked. I switched JAVA_HOME version to 11 and it working now. 
Thank you for help :)
