### ISSUE TITLE
CommitMessagePrefix got concatenated with messages without a space in the middle

### ISSUE THREAD

**Issue by bl4ckh4t3** [aleksandr-m/gitflow-maven-plugin#293]
First of all, thanks for this amazing plugin that resolve a lot of issues found in the jgitflow plugin.
I'm using commitMessagePrefix properties to set a default prefix for all the messages in order to mark them as done by the plugin and adding the version too with @{version} placeholder. However I found that the prefix message is concatenated to messages without a space in the middle resulting in
[GITFLOW] v5.4.0.5.0Update for next development version
even if the property has been set in the following way
```
<commitMessagePrefix>[GITFLOW] v@{version} </commitMessagePrefix>
```

Is it possible to change the plugin to add a space between prefix and message?

**Comment by aleksandr-m** [comment]
See https://issues.apache.org/jira/browse/MNG-5380.

You can use `xml:space="preserve"`

```
<commitMessagePrefix xml:space="preserve">[GITFLOW] v@{version} </commitMessagePrefix>
```

**Comment by bl4ckh4t3** [comment]
Hi @aleksandr-m thanks for your comment.
I've tried with 

 <commitMessagePrefix xml:space="preserve>[GITFLOW] v@{version} </commitMessagePrefix>

but the pom is now broken and every build cause the following error:

 Non-parseable POM /Users/bl4ckh4t3/Downloads/demo-version/pom.xml: markup not allowed inside attribute value - illegal <  (position: TEXT seen ...<commitMessagePrefix xml:space="preserve>[GITFLOW] v@{version} <... @67:85)  @ line 67, column 85

**Comment by aleksandr-m** [comment]
Seem like there is missing `"` in `"preserve>`

**Comment by aleksandr-m** [comment]
I've added a note about that in the readme.
