### ISSUE TITLE
Run the plugin from Bitbucket Pipelines

### ISSUE THREAD

**Issue by shvalb** [aleksandr-m/gitflow-maven-plugin#297]
Hey guys,

I'm really excited about this plugin and it works great for me running it from local command line, but I wonder what needs to be done in order to run it from Bitbucket pipelines...

**Comment by aleksandr-m** [comment]
@shvalb Git and Maven. Have you experienced any problems running it from bitbucket?

**Comment by shvalb** [comment]
I guess the missing piece for running it on Bitbucket is to provide a Docker image that has Git+Maven+JDK, usually I use maven:3.8.1-jdk-11-slim as the base image, but in this case I need something that contains Git.
Any recommendations?

**Comment by aleksandr-m** [comment]
You can just install git.
