### ISSUE TITLE
fromBranch parameter doesn't get support branch

### ISSUE THREAD

**Issue by mserbi** [aleksandr-m/gitflow-maven-plugin#298]
Here is the script line:
sh './mvnw gitflow:hotfix-start -B -DfromBranch="support/test" -s $MAVEN_SETTINGS -DmvnExecutable=$(pwd)/mvnw -Dsurefire.useSystemClassLoader=false -Dgitflow.push.remote=true -Dgitflow.maven.argline="-s $MAVEN_SETTINGS -Dgitflow.push.remote=true"'

Here is the error:
[ERROR] Failed to execute goal com.amashchenko.maven.plugin:gitflow-maven-plugin:1.11.0:hotfix-start (default-cli) on project *******: The fromBranch is not production or support branch. -> [Help 1]

Here is the support branch created in Bitbucket:
![Screenshot 2021-05-12 at 23 50 37](https://user-images.githubusercontent.com/48235671/118042560-ea1cba80-b37c-11eb-9f6b-6f8f2067d22f.png)

It works with -DfromBranch="master" or without the parameter at all but it seems like support branches are not accepted.

**Comment by aleksandr-m** [comment]
@mserbi  Have you changed `supportBranchPrefix`?

Also `1.11.0` is pretty old version.

**Comment by aleksandr-m** [comment]
@mserbi Ping

**Comment by mserbi** [comment]
Hi @aleksandr-m, it was because of the version. The latest one worked, sorry for not replying earlier.
