### ISSUE TITLE
Would it make sense to support --ff-only for release?

### ISSUE THREAD

**Issue by raehalme** [aleksandr-m/gitflow-maven-plugin#30]
I'm including this plugin in our development process and was wondering if it would make sense to support `--ff-only` when merging the release branch to master? I would like to see the master branch updated "as is" without any changes from the release branch.

**Comment by aleksandr-m** [comment]
What are you trying to achieve with that? What is the use case?

Are you sure that `--ff-only` is what you want?

--ff-only
> Refuse to merge and exit with a non-zero status unless the current HEAD is already up-to-date or the merge can be resolved as a fast-forward.

**Comment by raehalme** [comment]
I would like the master branch to represent the last commit of the latest release. The release branch is used to prepare the release, build the artifacts, and the master should just point to the final commit of the  release branch. 

If there is a merge commit in the master branch, then master does not necessarily represent the same content that was in the release branch where the release was prepared and probably tested too. 

The option `--ff-only` can be used to enforce this requirement.

**Comment by raehalme** [comment]
Awesome, thanks!
