### ISSUE TITLE
<verbose>true</verbose> not taken into account

### ISSUE THREAD

**Issue by thaDude** [aleksandr-m/gitflow-maven-plugin#311]
Hello, 

I am configuring version 1.16.0 of the gitflow-maven-plugin in my projects' parent POM like so:

```
<configuration>
        <!-- SHOW COMMAND OUTPUT -->
        <verbose>true</verbose>
        <gitFlowConfig>
                <productionBranch>master</productionBranch>
                <developmentBranch>dev</developmentBranch>
                ...
        </gitFlowConfig>
</configuration>
```

However, in order to see command output during the release of a project which uses the parent POM I'd need to do:

```
mvn gitflow:release-finish -Dverbose=true -DpostReleaseGoals=deploy
```

otherwise I won't see any output of the maven deploy plugin etc. What am I missing?

Thank you,

David

**Comment by aleksandr-m** [comment]
Are you running plugin from the parent project? If not then you probably need to use `pluginManagement` section.

**Comment by aleksandr-m** [comment]
@thaDude Ping.

**Comment by thaDude** [comment]
Hi, thanks for replying and sorry for the late reply. I do have the configuration in a `pluginManagement` section inside my company's parent POM. I do not override the configuration in any of the projects that use that reference the parent POM. The particular project I am trying to build is a multi-module project, not sure if that matters.

I wanted to provide a sample project to help reproduce, let me know if still helpful.

```
mvn --version
Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T17:06:16+02:00)
Maven home: /Users/xxxxxx/.sdkman/candidates/maven/current
Java version: 11.0.2, vendor: Oracle Corporation, runtime: /Users/xxxxxx/.sdkman/candidates/java/11.0.2-open
Default locale: en_FR, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.6", arch: "x86_64", family: "Mac"
```
