### ISSUE TITLE
Hotfix finish will merge only to develop if release branch not locally checked out

### ISSUE THREAD

**Issue by pcasaes** [aleksandr-m/gitflow-maven-plugin#318]
How to reproduce:

Have a develop, release and hotfix branch.
Have main, develop and hotfix checked out locally (release branch not checked out locally)

When running hotfix-finish will merge to develop branch and ignore release branch.

**Comment by aleksandr-m** [comment]
Seem like global issue. Maybe we should always try to fetch whole remote if `fetchRemote` is set to true?

**Comment by aleksandr-m** [comment]
`1.19.0` is released.
