### ISSUE TITLE
Push to remote when starting a release

### ISSUE THREAD

**Issue by raehalme** [aleksandr-m/gitflow-maven-plugin#32]
When I start a release, I'd like to see the new branch being pushed to the remote. My use case is that I want the CI server to start building the branch immediately.

Currently the `pushRemote` configuration option does not seem to have any effect on the `release-start` goal. Would it be possible to use it also when starting a release?

**Comment by aleksandr-m** [comment]
Yes, sounds good. But I think it is better to create separate parameter for it or to implement feature that allows to set different parameters values for different goals.

**Comment by raehalme** [comment]
I agree with you that support for goal specific parameter values is the way to go (actually I was under the impression that it was already supported).
