### ISSUE TITLE
git command error and strange behaviour on Windows

### ISSUE THREAD

**Issue by CidTori** [aleksandr-m/gitflow-maven-plugin#320]
When running `mvn gitflow:release-finish` (for example) in CMD on Windows (with git for Windows installed), strange things happen :
- I get the following logs :
  ```
  [INFO] Checking for uncommitted changes.
  [DEBUG] git diff --no-ext-diff --ignore-submodules --quiet --exit-code
  [DEBUG] git diff-index --cached --quiet --ignore-submodules HEAD --
  [DEBUG] git for-each-ref --format="%(refname:short)" refs/heads/release/**
  [INFO] Checking out 'short)' branch.
  [DEBUG] git checkout short)
  ```
- even if some steps didn't work, the command proudly gives a `BUILD SUCCESS` at the end (the command did nothing but commit "Update for next development version" on the release branch...)

**Comment by aleksandr-m** [comment]
Which git version? Which windows? Which plugin version do you use? How do you running maven build?

**Comment by CidTori** [comment]
- git version 2.34.1.windows.1
- Windows 10 Enterprise version 1909
- gitflow-maven-plugin:1.16.0
- What do you mean ? I run the goal with `mvn -X gitflow:release-finish`

**Comment by aleksandr-m** [comment]
Cannot reproduce.

The `git for-each-ref --format="%(refname:short)" refs/heads/release/**` works just fine in cmd and power shell.

When git tries to checkout unknown branch it will fail along with the maven goal, outputting something like `release-finish: error: pathspec 'some_wrong_branch_name_here' did not match any file(s) known to git` and `BUILD FAILURE`.

**Comment by CidTori** [comment]
Did you try release-finish after a successful release-start?

It seems that in my case, `git for-each-ref --format="%(refname:short)" refs/heads/release/**` will output a `short)` line for any release/* branch in my repo, but sometimes (I didn't determine the conditions yet), release-start will also fail silently and, since it didn't create a release/* branch, no `short)` is output with `git for-each-ref --format="%(refname:short)" refs/heads/release/**`.

**Comment by CidTori** [comment]
You can also simply try `git for-each-ref --format="%(refname:short)"` in any repo

**Comment by CidTori** [comment]
Nevermind, I found the problem : on my machine I call git through a .bat that calls git.exe, passing the CLI parameters with `%*`, which apparently do the `%` substitution somewhere.
I'm closing this.
