### ISSUE TITLE
release-finish should merge master, not the release branch, into develop

### ISSUE THREAD

**Issue by CidTori** [aleksandr-m/gitflow-maven-plugin#321]
See my answer to a StackOverflow question [here](https://stackoverflow.com/a/70248167/6315631) for the full story, but the bottom line is: you should back-merge the release tag (or master) into develop, instead of back-merging the release branch into develop, contrary to what the original article and most popular sources say, because of an issue with `git describe`.

This is already the default behaviour for the most popular implementation of gitflow, [gitflow-avh](https://github.com/petervanderdoes/gitflow-avh) (default on Windows and Ubuntu for example), and it was approved by Vincent Driessen aka nvie, even if he never made it official (the links in my SO answer lead to the corresponding source code lines, issue and PR).

**Comment by CidTori** [comment]
Moreover, [this comment](https://github.com/aleksandr-m/gitflow-maven-plugin/blob/54d31d967f3e4b54c6f46a41dc73a6f35325562d/src/main/java/com/amashchenko/maven/plugin/gitflow/GitFlowReleaseFinishMojo.java#L307) is misleading, since it is not the current behaviour.

**Comment by aleksandr-m** [comment]
Seems same as https://github.com/aleksandr-m/gitflow-maven-plugin/issues/213 ?
I remember there was some issue with avoiding direct commits to master.

**Comment by CidTori** [comment]
I see no objection in #213, #289 or #291.
Moreover, it's about a merge commit on develop, not a direct commit on master.
(By the way, PR #291 isn't ideal either: it back-merges the release branch AND the release tag into develop, but if you do the latter, you don't need the former. See my SO answer for the full story and references.)

**Comment by gbaso** [comment]
This is also the current behaviour in jgitflow. I'm evaluating a migration to gitflow-maven-plugin and it would be nice if the behaviour were similar.

**Comment by aleksandr-m** [comment]
Resolved in da263d3f6672d0c26243c829aef4d3a457848ee6
