### ISSUE TITLE
Java 7 compatibility silently broken

### ISSUE THREAD

**Issue by RyanFoulds** [aleksandr-m/gitflow-maven-plugin#330]
The latest `versions-maven-plugin` (2.9.0) is compiled on java 8. The command used to invoke that plugin will, without special care, use the latest version. ​Could this dependency be explicitly declared or a known-good version be pinned? Perhaps even a configuration parameter to specify the version of `versions-maven-plugin` to be used?

This issue can easily be worked-around by using specifying a version in a pluginManagement element of a  java 7 project using this plugin, but diagnosing the release pipeline failure was tricky without the dependency on `versions` being declared.
```xml
<build>
    <pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>versions-maven-plugin</artifactId>
                <version>2.8.1</version>
            </plugin>
       </plugins>
    </pluginManagement>
</build>
```

edit: this also applies to the tycho versions plugin which broke support for Java 7 back in version 0.25.0 and now requires at least Java 11.

**Comment by aleksandr-m** [comment]
Related #115

**Comment by aleksandr-m** [comment]
Added `versionsMavenPluginVersion` and `tychoVersionsPluginVersion` properties with defaults.
