### ISSUE TITLE
setting profile is not working on release-finish

### ISSUE THREAD

**Issue by alapierre** [aleksandr-m/gitflow-maven-plugin#332]
we have dedicated profile for building docker images. It is critical to build and deploy images on release phase. When I try to do this by

```
mvn -Pdocker gitflow:release-finish
```

profile is ignored. It will be nice if I can specify profile like eg. `preReleaseGoals` in plugin config

**Comment by aleksandr-m** [comment]
Use `argLine` to pass parameters to internal commands. 

E.g.
```
mvn gitflow:release-finish -DargLine="-Pdocker"
```
