### ISSUE TITLE
Looking for Help: Is this possible with gitflow-maven-plugin

### ISSUE THREAD

**Issue by jenslauterbach** [aleksandr-m/gitflow-maven-plugin#333]
Hello 👋 ,

I am trying to set up a Gitlab CI/CD pipeline using the `gitflow-maven-plugin:1.18` and have been successful so far. But now I came across a problem that I was not able to solve yet. So I wanted to ask for help here.

This is what I want to achieve:

- 3 branches: `main`, `develop` and `release/<version>`
- When I use `release-start` in `develop` a new `release/<version>` branch is created
- In the `develop` branch the version is already bumped (`commitDevelopmentVersionAtStart`)
- In the `release` branch I keep a `SNAPSHOT` version (`useSnapshotInRelease`)

When I finish the release (`release-finish`) I want the following to happen (which does not work yet):

- A non-SNAPSHOT tag is created
- A non-SNAPSHOT version is merged to `main`

What actually happens:

- A SNAPSHOT tag is created
- A SNAPSHOT version is merged to `main`

Help would be appreciated :D

**Comment by aleksandr-m** [comment]
@jenslauterbach Use `useSnapshotInRelease` in the `release-finish` goal as well.

**Comment by jenslauterbach** [comment]
@aleksandr-m I just tested it and it worked. Thank you 👍
