### ISSUE TITLE
Error release-finish, don´t get git userName from project

### ISSUE THREAD

**Issue by limkinZero** [aleksandr-m/gitflow-maven-plugin#34]
When I´m trying to run release-finish goal, I have the next issue:

[INFO] --- gitflow-maven-plugin:1.4.0:release-finish (default-cli) @ im-manager-all ---
[INFO] Checking for uncommitted changes.
[INFO] Fetching remote branch 'origin develop'.
[INFO] Comparing local branch 'develop' with remote 'origin/develop'.
[INFO] Fetching remote branch 'origin master'.
[INFO] Comparing local branch 'master' with remote 'origin/master'.
[INFO] Checking out 'release/1.0' branch.
[INFO] Cleaning and testing the project.
[INFO] Checking out 'master' branch.
[INFO] Merging (--no-ff) 'release/1.0' branch.
[INFO] Creating 'v1.0' tag.
[INFO] Checking out 'develop' branch.
[INFO] Merging (--no-ff) 'release/1.0' branch.
[INFO] Updating version(s) to '1.1-SNAPSHOT'.
[INFO] Committing changes.
[INFO] Deleting 'release/1.0' branch.
[INFO] Pushing 'master' branch to 'origin'.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] My project ....................... FAILURE [ 49.465 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 50.134 s
[INFO] Finished at: 2017-02-14T17:53:34+01:00
[INFO] Final Memory: 9M/119M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.amashchenko.maven.plugin:gitflow-maven-plugin:1.4.0:release-finish (default-cli) on project my-project: bash: /dev/tty: No such device or address
[ERROR] error: failed to execute prompt script (exit code 1)
[ERROR] fatal: could not read Username for 'http://localhost:8080': Invalid argument
[ERROR] -> [Help 1]

**Comment by aleksandr-m** [comment]
Do you have a git repo at http://localhost:8080 ?

**Comment by limkinZero** [comment]
Yes, I've a git repo in this port. I fixed the git error configuring the username parameter in git repository with command but i think that this plugin has yo get

**Comment by aleksandr-m** [comment]
Can you share more details. How did you *configured the username parameter in git repository with command*?

**Comment by limkinZero** [comment]
Hi,
You can store your credentials using the following command

$ git config credential.helper store
$ git push http://example.com/repo.git
Username: <type your username>
Password: <type your password>

After this, i can finish release ok.
