### ISSUE TITLE
"gitflow:hotfix-finish" does not apply changes back to deveop

### ISSUE THREAD

**Issue by tygroo** [aleksandr-m/gitflow-maven-plugin#346]
Hello,
When we make a "hotfix-finish" from a hotfix from a support branch, there is no report of these modifications on the develop branch.
Is it completely unthinkable in "gitflow" principles to report these modifications on develop for our next "release" of "develop" on "master"?
Should we always apply our changes manually on develop?
Is it possible to add an option to apply these hotfixes also on develop?

Thank you very much for your help.

**Comment by aleksandr-m** [comment]
Support branches are usually used in parallel with the main branches and not merged back. Why and how do you use them that you want to merge it back to develop?

**Comment by tygroo** [comment]
Hello,
In fact, we don't want to merge the support branch into our development branch. 
But when we make a hotfix that starts from the support branch (for example with the parameters: gitflow:hotfix-start -DfromBranch=support/1.35.x), we want to be able to apply the hotfix also to our development branch.
Because, when we make a correction on the support branch, we don't want to lose it and we want to apply it to our develop branch.
Today, the support branch is our production but our application continues to be developed and always releases over our sprints. Our master branch will move into our production after being tested.

Maybe we're doing something wrong
Thank you so much.

**Comment by aleksandr-m** [comment]
@tygroo Have you managed to somehow overcome this issue? For now, it is seems that merging support hotfix would introduce more troubles later. Maybe cherry picking changes would be a more nicer solution for you.

**Comment by tygroo** [comment]
Thank you for your reply.
Indeed, this is the solution we have adopted. 
We do cherry picks on develop because develop can be much further than support and merge can be extremely complicated.
Thanks for the time you spent there.
