### ISSUE TITLE
Parameter for release-finish with multiple release-branches in repository 

### ISSUE THREAD

**Issue by jelingi** [aleksandr-m/gitflow-maven-plugin#356]
Good day, 

we use the Goals release:start and release:finsih in our project. In our project it is common that we use multiple release branches in our repository, because we work on multiple releases at the same time. 
Problem is that the goal release:finish does not permit multiple release branches. Error message: **More than one remote release branch exists. Cannot finish release.** (As in the following issue: https://github.com/aleksandr-m/gitflow-maven-plugin/issues/308 )
Is there a way to use a parameter to tell the goal which release branch should be released? 
Like @Parameter(property = "releaseBranchforRelease", defaultValue = "release/2.0.x")

Kind regards

**Comment by aleksandr-m** [comment]
Currently only one release branch is allowed. https://github.com/aleksandr-m/gitflow-maven-plugin/issues/217

**Comment by jelingi** [comment]
Hi @aleksandr-m ,
the issue in #217 is not really what we're looking for. We do use support branches for released version. But in bigger teams we're often forced to work on multiple releases at a time. This is why a configuration where you can select the release branch would be necessary. Could you please consider to implement this feature?
cheers
Jelin

**Comment by aleksandr-m** [comment]
One configuration is not enough. Currently release goals will not work if there are multiple release branches. See this for example - https://github.com/aleksandr-m/gitflow-maven-plugin/blob/ea7841df0aa3d361d70d133f827b768a972a3311/src/main/java/com/amashchenko/maven/plugin/gitflow/GitFlowReleaseStartMojo.java#L157-L160
