### ISSUE TITLE
`feature-finish` only resets artifact version when invoked from the branch to be finished

### ISSUE THREAD

**Issue by kzander91** [aleksandr-m/gitflow-maven-plugin#358]
Steps:
1. Checkout `develop`, current artifact version is `1.0.0-SNAPSHOT`.
2. `mvn gitflow:feature-start`
3. Enter feature name `my-feature`.
4. Plugin creates branch `feature/my-feature`, sets artifact version to `1.0.0-my-feature-SNAPSHOT`.
5. Checkout `develop`.
6. Run `mvn gitflow:feature-finish`, select the `my-feature` branch and confirm.
7. Plugin merges `feature/my-feature` into `develop` _but does not set the artifact version back to `1.0.0-SNAPSHOT` beforehand_. If I switch to `feature/my-feature` first and then run `gitflow:feature-finish`, it _does_ correctly set the version back before merging.

As a consequence, if I forget to checkout the feature branch to be merged before invoking `feature-finish`, I end up with the feature's artifact version on `develop`.

The desired behavior is that the plugin resets the artifact version regardless of the branch I have currently checked out.

**Comment by aleksandr-m** [comment]
Should be fixed by 4b40a6ca24d98228f238636777efdf9bba62bc13

**Comment by kzander91** [comment]
@aleksandr-m Nice, thanks 👍 . Do you have an ETA on when the next version might be available?

**Comment by aleksandr-m** [comment]
@kzander91 `1.19.0` is released.
