### ISSUE TITLE
Specify executables in shell variables

### ISSUE THREAD

**Issue by steppinrazor** [aleksandr-m/gitflow-maven-plugin#36]
#### Use case: 

If you have the plugin in a parent pom used by multiple diff applications, locally devs on Windows have the freedom to have the Maven binaries where they please so you do not want to set executables in the parent pom. Having to specify `mvnExecutable` every time on the command line can be inconvenient but we can have a seamless alternative.

#### Proposed Solution:

In Git Bash (and this can be used even on *nix to override the PATH) you can specify the executable in the env e.g. `export mvnExecutable=/c/path_to_m2_home/bin/mvn.bat`. This would be the default which can be overridden by `-DmvnExecutable=...`. When the env variable is not set the code behaves as it is does before the change.
 
See #35

**Comment by aleksandr-m** [comment]
Why this is better than having executable in the PATH?

**Comment by steppinrazor** [comment]
Not _better_ but as an alternative - there are a couple odd cases on my team where when running the plugin in Git Bash or Cygwin it does not honor 'mvn' on the PATH so this is an option that is also transparent.

**Comment by aleksandr-m** [comment]
You can use environment variables in pom.xml.
E.g. `<mvnExecutable>${env.mvnExecutable}</mvnExecutable>`

**Comment by steppinrazor** [comment]
Yes I suppose we could set this up in the parent pom to have the same effect - closing.
