### ISSUE TITLE
Move to java 8 and update dependencies

### ISSUE THREAD

**Issue by aleksandr-m** [aleksandr-m/gitflow-maven-plugin#369]

**Comment by DRoppelt** [comment]
if java8 becomes the baseline, the plugin versions pinned with this can be pulled up to more recent versions: https://github.com/aleksandr-m/gitflow-maven-plugin/issues/330

for instance, `versions-maven-plugin` with `2.8.1` from 2010 pulls in strutsv1 (which we in our org noticed as the mvn-repositury was flaggen on our build nodes)

![image](https://user-images.githubusercontent.com/6932863/213504741-9604c631-4a85-4721-af4b-e7693c11c057.png)

**Comment by DRoppelt** [comment]
I got stuck for a while since the tests kept being red, I missed that this has changed meanwhile https://github.com/aleksandr-m/gitflow-maven-plugin/commit/3327fb55f277882c0d89b9c6b7de440de1c08204

PR is in progress

**Comment by DRoppelt** [comment]
Now that 1.20.0 is released... what do you think about bringing this ticket/PR into the next release? And if so, when?

I think that you mentioned that this ticket was more for intent than actually working on it in november. With the change of maven 3.9.X having java 8 as minimum version, it feels like this is something that can be introduced in your plugin too?
