### ISSUE TITLE
Release branch creating with snapshot suffix

### ISSUE THREAD

**Issue by sriram0721** [aleksandr-m/gitflow-maven-plugin#370]
Hello,

First of all thanks for the amazing plugin, which is making our lives easy.

I have a develop branch which holds snapshot version of pom as 1.x.x-SNAPSHOT-1 . I used gitflow maven plugin to start and end release.

whenever it creates a release branch on the start-release goal, it creates a release branch as release/1.x.x-SNAPSHOT-1 . The expected behaviour is to create the release branch as release/1.x.x and update the release pom as 1.x.x-RC1, 1.x.x-RC2 etc. 

I use the following command for starting the release
        - mvn gitflow:release-start -DuseSnapshotInRelease=true -DcommitDevelopmentVersionAtStart=true -DversionDigitToIncrement=1 -DpushRemote=true
        
 Do I need to add anything on the configuration section?. Thanks again

**Comment by aleksandr-m** [comment]
You're asking for snapshot version in release in your command `-DuseSnapshotInRelease=true`.
