### ISSUE TITLE
gitflow-maven snapshot suffix issue

### ISSUE THREAD

**Issue by sriram0721** [aleksandr-m/gitflow-maven-plugin#371]
Hello,

I'm using git-flow maven for my releases. I'm doing version bumping of my features based on the develop. For example, if my development is 1.0.0-SNAPSHOT, if I create a release branch it will become, 1.0.0-SNAPSHOT-1. When I merge my feature to develop, the develop version is updated as 1.0.0-SNAPSHOT-1 . 
Now, if I start the release, using the gitflow-maven-plugin, it creates the release branch as release/1.0.0-SNAPSHOT-1 even though If i set use-snapshot-version is set to false.

After that, i tried removing the -1 from the develop version and when i started the release, it create the release branch as release/1.0.0.

How can i mitigate this

**Comment by aleksandr-m** [comment]
Don't put `-1` after snapshot. If you want something like release candidate numbering then use `1.0.0-RC1-SNAPSHOT` pattern.
Also, you can always set release version in release-finish goal.

**Comment by sriram0721** [comment]
**Also, you can always set release version in release-finish goal**  can you please explain this and how to do it ? @aleksandr-m

**Comment by aleksandr-m** [comment]
Sorry, was referring to `release-start` goal and `releaseVersion` parameter. E.g. `-DreleaseVersion=1.0.0`.
