### ISSUE TITLE
Merge conflicts when running gitflow:release

### ISSUE THREAD

**Issue by ftho1** [aleksandr-m/gitflow-maven-plugin#373]
Hello,

When I run `mvn --batch-mode gitflow:release`, I get the following error:

```
[ERROR] Failed to execute goal com.amashchenko.maven.plugin:gitflow-maven-plugin:1.19.0:release (default-cli) on project ci-test: release: Auto-merging pom.xml
[ERROR] CONFLICT (content): Merge conflict in pom.xml
[ERROR] Automatic merge failed; fix conflicts and then commit the result.
```

In actuality, I don't understand how this could work. I am very new to this plugin (and to Java and Maven generally speaking), but as far as I can see, this is what the gitflow plugin attempts to do, assuming the `develop` branch has a pom file with version 1.0.1-SNAPSHOT:

 1. Merge `develop` into `master`
 2. Modify the pom file in the `master` branch to set the version to 1.0.1 and commit that change
 3. Modify the pom file in the `develop` branch to set the version to 1.0.2-SNAPSHOT and commit that change

Now `develop` and `master` have diverged on the same line of code in the pom file. The next time the gitflow plugin will try to run step 1 (merge `develop` into `master`), the merge will fail. It either requires an explicit merging strategy, such as `git merge -X theirs develop`, or something/somebody to fix the conflict. Given that we want to run that in a CI pipeline, manual intervention is not an option.

I can't imagine we are the only people facing this problem, how is this problem usually solved? Thanks a lot for any help!

**Comment by alexist** [comment]
Release goal : 

* [Checkout develop](https://github.com/aleksandr-m/gitflow-maven-plugin/blob/master/src/main/java/com/amashchenko/maven/plugin/gitflow/GitFlowReleaseMojo.java#L190)  branch, 
* [change version](https://github.com/aleksandr-m/gitflow-maven-plugin/blob/master/src/main/java/com/amashchenko/maven/plugin/gitflow/GitFlowReleaseMojo.java#L255)  to release version
*  and [merge develop](https://github.com/aleksandr-m/gitflow-maven-plugin/blob/master/src/main/java/com/amashchenko/maven/plugin/gitflow/GitFlowReleaseMojo.java#L265) into master

I have no conflict issue using this goal on multiple projects. Maybe you could share the plugin configuration, and enable maven debug log.

**Comment by aleksandr-m** [comment]
@ftho1 Not sure why do you think it should fail. And it shouldn't.

Have you modified version in production branch by hand?
