### ISSUE TITLE
Missing backmerge with gitlow:release goal

### ISSUE THREAD

**Issue by alexist** [aleksandr-m/gitflow-maven-plugin#374]
Hi, 

The goal gitflow:release doesn't back merge into develop after tag is created.

The main issue is develop branch doesn't contains tag.

Release-finish and hotfix-finish do a back merge : 
https://github.com/aleksandr-m/gitflow-maven-plugin/blob/master/src/main/java/com/amashchenko/maven/plugin/gitflow/GitFlowReleaseFinishMojo.java#L313

https://github.com/aleksandr-m/gitflow-maven-plugin/blob/master/src/main/java/com/amashchenko/maven/plugin/gitflow/GitFlowHotfixFinishMojo.java#L327

Is it possible to add back merge option in this goal ?

**Comment by aleksandr-m** [comment]
How it will look like? PR-s are welcome. :)

**Comment by alexist** [comment]
The PR has been tested manually and in a CI/CD pipeline.

Can you review the PR ?

**Comment by aleksandr-m** [comment]
`1.20.0` is out.
