### ISSUE TITLE
Is it possible put all command parameter to the configuration?

### ISSUE THREAD

**Issue by jeffwji** [aleksandr-m/gitflow-maven-plugin#376]
For example, if I prefer push to remote when perform `release-start`. but not pushing when `release-finish`, I have to set `-DpushRemote=true` to the first command, and set `-DpushRemote=false` the the second. Which is very annoy. However there is a `<pushRemote>` option under `<configuration>` but it looks affect globally. I'm hoping it can be set separately and works to every command line parameter. For example:

```
<configuration>
  <args>
    <releaseStart>
      <pushRemote>true</pushRemote>
      <otherParameter>...</otherParameter>
    </releaseStart>
    <releaseFinish>
      <pushRemote>false</pushRemote>
      <otherParameter>...</otherParameter>
    <releaseFinish>
    <otherPhase>
      ...
    </otherPhase>
  </args>
</configuration>
```

**Comment by aleksandr-m** [comment]
AFAIK Maven doesn't support this. Ideas of workarounds are welcome.

**Comment by mzatko** [comment]
i thing it should work "classic maven way"
```
<plugin>
   <artifactId>gitflow-maven-plugin</artifactId>
   ...
   <configuration>
      <!-- common configuration -->
   </configuration>
   <executions>
      <execution>
         <goals>
            <goal>release-start</goal>
         </goals>
         <configuration>
            <!-- per-goal(s) configuration -->
            <pushRemote>true</pushRemote>
         </configuration>
      </execution>
      <execution>
         <goals>
            <goal>release-finish</goal>
         </goals>
         <configuration>
            <!-- per-goal(s) configuration -->
            <pushRemote>false</pushRemote>
         </configuration>
      </execution>
   </executions>
</plugin>
```

**Comment by aleksandr-m** [comment]
@mzatko Each execution must have unique id.

One possible workaround is to use execution id in command line - see [Maven 3.3.1 Release Notes](https://maven.apache.org/docs/3.3.1/release-notes.html#plugin-goal-invocation-from-command-line).

**Comment by alexist** [comment]
I think you can define some profiles, for example release-start, release-finish and configure in each profile the specic configuration (pushRemote,....).
Then execute the gitflow goal with the related profile 
`mvn giflow:release-start -Prelease-start`

**Comment by aleksandr-m** [comment]
@jeffwji Have you resolved this?

**Comment by jeffwji** [comment]
> @jeffwji Have you resolved this?

Yes, it resolve!

**Comment by aleksandr-m** [comment]
@jeffwji Good. Can you post which solution did you use, to help future visitors.
