### ISSUE TITLE
release-finish: 'origin/master' is not a commit and a branch 'master' cannot be created from it

### ISSUE THREAD

**Issue by peanut006** [aleksandr-m/gitflow-maven-plugin#377]
Hi,

Thank you for great plugin! In my environment we are taking Gitlab in to use with Jenkins Gitlab Branch Source plugin. With old VCS and Jenkins plugin gitflow have been working nicely. But now with the new environment I'm having little issue. I'm getting following error:

`[ERROR] Failed to execute goal com.amashchenko.maven.plugin:gitflow-maven-plugin:1.16.0:release-finish (default-cli) on project dbunit-demo-pom: release-finish: fatal: 'origin/master' is not a commit and a branch 'master' cannot be created from it -> [Help 1]`

Looks like that git is missing origin/master ref which might be the reason for the problem? Not sure what causes that.

```
$ git show-ref
5063c60d8d6a1637e2bd5ad429050b81ee7a90eb refs/remotes/origin/develop
```

I was wondering that it would be nice if the plugin had functionality/parameter to force update refs if wanted. The "--refetch" might do the work. What do you think?

Br, Timo

**Comment by peanut006** [comment]
Forgot to mention that the error comes when the plugin tries to checkout master "git checkout -b master origin/master"

**Comment by peanut006** [comment]
The remote was missing the master refs, the situation cannot be resolved by the plugin. The issue is invalid.

**Comment by aleksandr-m** [comment]
@peanut006 
Maybe a git cloning issue.
You should upgrade to the latest version of the plugin, there are improvements to interactions with remotes.

**Comment by peanut006** [comment]
Thanks @aleksandr-m !

Finally found the issue! Jenkins Gitlab plugin did the clone/fetch using +refs/heads/develop:refs/remotes/origin/develop which caused the master branch checkout failure of the gitflow plugin. The Jenkins Gitlab plugin have "Specify ref specs" setting in job config where to a information about master refs can be added "+refs/heads/master:refs/remotes/origin/master".
