### ISSUE TITLE
Allow a regex to enforce feature branch naming rules

### ISSUE THREAD

**Issue by steppinrazor** [aleksandr-m/gitflow-maven-plugin#38]
Sometimes in enterprises you may want to enforce feature branch naming standards such as possibly based on tracking codes (like Jira, Mantis, YouTrack...) and/or you want to restrict summary message lengths - these become relevant when running `merge --squash` and the feature branch name represents the commit on develop/master.

See #37

**Comment by aleksandr-m** [comment]
`1.5.0` is out.
