### ISSUE TITLE
gitflow-maven-plugin ignores settings.xml from command line

### ISSUE THREAD

**Issue by schweben** [aleksandr-m/gitflow-maven-plugin#382]
In order to automatically perform a release in our CI environment I need to pass a custom Maven ``settings.xml`` file into the build so that Maven will use our internal artefact repository. This is done using the normal ``-s`` argument to the Maven command line

When the ``gitflow:release`` goal runs I can initially see artefacts being downloaded from the internal repository.

![image](https://user-images.githubusercontent.com/19774427/228494178-26a931f4-bbc1-4717-9b82-98b6ec8cca8a.png)

However once the plugin execution starts a Maven build internally (for example to run the deploy goal), the mirror settings in the custom ``settings.xml`` file are ignored and artefacts are downloaded from the Central Maven repository. This then causes the build to fail because it cannot find an internally-developed Maven plugin which is unavailable from the Central repository.

![image](https://user-images.githubusercontent.com/19774427/228494246-78315dbf-ceb1-423b-ac53-f5678046a965.png)

It seems that the gitflow-maven-plugin is ignoring any settings file passed via the ``-s`` argument and will only use ``settings.xml`` from the system's ``.m2`` directory

**Comment by aleksandr-m** [comment]
You need to pass arguments with `argLine` parameter. https://github.com/aleksandr-m/gitflow-maven-plugin#maven-arguments
