### ISSUE TITLE
[Question] Is it possible to release the next Patch Version?

### ISSUE THREAD

**Issue by Mom0aut** [aleksandr-m/gitflow-maven-plugin#387]
I wanna use the goal `mvn gitflow::release` and i dont wanna set the next release/deployment version manually. Can i somehow set the next possible patch version. For example current Version is `0.0.1` and i perform` mvn gitflow::release -DReleaseNextPatch` it should release the Version  `0.0.2`.

Is there any command for that in the actual plugin?

Thanks

**Comment by aleksandr-m** [comment]
Usually, the development version is already incremented, comparing to the last release version.
You can use `releaseVersion` parameter to change it when running the release goal.
Also, you can implement [custom version policy](https://github.com/aleksandr-m/gitflow-maven-plugin#versioning) and use it.

**Comment by Mom0aut** [comment]
Thank you for your response, can i use the `developmentVersion` during runtime like `mvn gitflow::release -DreleaseVersion=developmentVersion` ?
