### ISSUE TITLE
[Question] Maven repository to retrieve current 1.19.1-SNAPSHOT?

### ISSUE THREAD

**Issue by rmontag-ap** [aleksandr-m/gitflow-maven-plugin#388]
Is there a public maven repository where the current 1.19.1-SNAPSHOT can be downloaded? 
I checked snapshots repo on https://oss.sonatype.org/#view-repositories;snapshots~browsestorage but didn't found it there.

**Comment by DRoppelt** [comment]
Is there a way we can help with a 1.19.1/1.20.0/2.0.0 release? 

prepare releasenotes or such?

**Comment by aleksandr-m** [comment]
@DRoppelt `1.20.0` is released.

As for the snapshot builds maybe github packages can be used.
