### ISSUE TITLE
checkSnapshotDependencies() should not check internal dependencies of a multi module project

### ISSUE THREAD

**Issue by tompluess** [aleksandr-m/gitflow-maven-plugin#39]
in a maven multi module project, internal SNAPSHOT dependencies should not be checked, since they will be bumped to the release version while setting the respective release version.

i would see two approaches:
A) these internal dependencies could be ignored
B) check for SNAPSHOT dependencies should be done only after updating the release version (call to `mvnSetVersions(..)`)

**Comment by aleksandr-m** [comment]
@tompluess Test and review, please.

**Comment by pogocode** [comment]
I ran into the same issue this afternoon, but noticed this commit. Cloned and build and it certainly sorted out the multi module build for me.

**Comment by aleksandr-m** [comment]
@tompluess  @pogocode  1.4.1 is in the maven central.

**Comment by pogocode** [comment]
@aleksandr-m nice one, thanks!

**Comment by tompluess** [comment]
@aleksandr-m Thank you very much, version 1.4.1 works very well in our build / release pipelines.
