### ISSUE TITLE
[Question] release:perform

### ISSUE THREAD

**Issue by DempseyRoller** [aleksandr-m/gitflow-maven-plugin#392]
Hi!
I'm looking in to this project and it seems quite near. However a relatively new Maven user I'm wondering if there's a way to release a version with this similar to release:perform of the maven release plugin. And of course if it is, how?

**Comment by aleksandr-m** [comment]
Take a look at the provided [goals](https://github.com/aleksandr-m/gitflow-maven-plugin/tree/v1.20.0#goals-overview).

For releasing there is `gitflow:release` goal and `gitflow:release-start` and `gitflow:release-finish` if you want to use separate branch for releases.

**Comment by DempseyRoller** [comment]
Thanks for the quick answer. I worded my question poorly. I wanted to do a deploy with my release. And it seems the parameter -DpostReleaseGoals can do that. Am I correct that there's no way to put those same arguments inside the pom file?

**Comment by mzatko** [comment]
@DempseyRoller , you can do it directly in pom.xml

        <pluginManagement>
            <plugins>
                ...
                <plugin>
                    <groupId>com.amashchenko.maven.plugin</groupId>
                    <artifactId>gitflow-maven-plugin</artifactId>
                    <version>${gitflow-maven-plugin.version}</version>
                    <configuration>
                        ...
                        <postHotfixGoals>deploy</postHotfixGoals>
                        <postReleaseGoals>deploy</postReleaseGoals>
                        ...
                    </configuration>
                </plugin>
                ...
            </plugins>
        </pluginManagement>

**Comment by DempseyRoller** [comment]
@mzatko
Thanks! I though I tried it already but I had written the parameter wrong. Enbolded by your comment I tried it again with the right parameter name and lo and behold! It works!

Thanks again!
