### ISSUE TITLE
Pass arguments down to spawned Maven processes

### ISSUE THREAD

**Issue by jwgmeligmeyling** [aleksandr-m/gitflow-maven-plugin#397]
Is it possible to pass arguments down to spawned Maven sub-processes? (like `-DskipTests` for `postReleaseTasks`) or `-s location/to/settings.xml` for `deploy`)

**Comment by aleksandr-m** [comment]
Use `argLine` parameter. https://github.com/aleksandr-m/gitflow-maven-plugin#maven-arguments

**Comment by jwgmeligmeyling** [comment]
Ah somehow I missed that option, thanks!
