### ISSUE TITLE
Expose modified project version as properties

### ISSUE THREAD

**Issue by jycr** [aleksandr-m/gitflow-maven-plugin#41]
I would like to customize commit message as follow :

```
    <commitMessages>
        <hotfixStartMessage>update versions for hotfix: ${project.version}</hotfixStartMessage>
        <hotfixFinishMessage>update for next development version: ${project.version}</hotfixFinishMessage>
        
        <releaseStartMessage>update versions for release: ${project.version}</releaseStartMessage>
        <releaseFinishMessage>update for next development version: ${project.version}</releaseFinishMessage>
        
        <tagHotfixMessage>tag hotfix: ${project.version}</tagHotfixMessage>
        <tagReleaseMessage>tag release: ${project.version}</tagReleaseMessage>
    </commitMessages>
```

But, as described in documentation:

> ${project.version} can be used any changes to version introduced by this goal won't be reflected in a commit message for this goal.

So: how can I put information on commit message about version?

**Comment by aleksandr-m** [comment]
I suppose that custom pattern can be introduced (e.g. `{{version}}`) to be string replaced in the appropriate goals.

**Comment by jycr** [comment]
Good idea.

Another proposal : add a Maven property :
* `gitflow.nextVersion`

NB : The default value of this property could be `X.Y.(Z+1)-SNAPSHOT` and can also be customize when user launch mvn command with `-Dgitflow.nextVersion= ...` (see issue #42 )

**Comment by aleksandr-m** [comment]
How do you set the default value to be `X.Y.(Z+1)-SNAPSHOT` before running a goal?

**Comment by aleksandr-m** [comment]
From the next release `@{version}` can be used.
