### ISSUE TITLE
Prompt for new version

### ISSUE THREAD

**Issue by jycr** [aleksandr-m/gitflow-maven-plugin#42]
In interactive mode, by default, `mvn gitflow:release` asks/prompts for the released version, but not for the new development version.

Is it possible to also ask the user to enter the version number for the next development version (SNAPSHOT)?

**Comment by aleksandr-m** [comment]
Smells too much like the release plugin. :) Why do you want this? What the use case?

**Comment by jycr** [comment]
Exactly.
But maybe I misunderstood the use of this plugin?
I thought that with gitflow-maven-plugin, I did not have to use the plugin maven-release-plugin. But maybe I was wrong?

Do I have to use both at the same time?

**Comment by aleksandr-m** [comment]
> I thought that with gitflow-maven-plugin, I did not have to use the plugin maven-release-plugin.

Correct.

But why do you want that the next development version would be something different than `x.x.x+1-SNAPSHOT` ?

**Comment by jycr** [comment]
Following http://semver.org, we usually work on next version X.X+1.0
X.X.X+1 is reserved for fixes (only if needed after QA phase).

**Comment by aleksandr-m** [comment]
But using semver doesn't mean that your next snapshot version should be `X.X+1.0`. What are you going to do if you want to develop patch in the feature branch or in the hotfix? Downgrade version manually?

**Comment by jycr** [comment]
When we need to develop a hotfix, we create a branch from tag which represents production deployed version.

**Comment by aleksandr-m** [comment]
How about boolean property which if set will increment minor version number instead of patch number?

**Comment by jycr** [comment]
It seems less flexible than give the new version number

2017-04-05 20:19 GMT+02:00 Aleksandr Mashchenko <notifications@github.com>:

**Comment by aleksandr-m** [comment]
With boolean you don't have to type every time `x.x+1.0`. What will happen if you want this behavior in not interactive mode?

**Comment by jycr** [comment]
I think I did not understand correctly

So you suggest a setting that:
- if true: suggests entering the version in interactive mode
- if it is false, keep the same behavior as at present?

If that's right, it would be perfect for me :)

**Comment by bjansen** [comment]
I agree with @jycr's original request, it would be nice for the plugin to ask what the next SNAPSHOT version is.

> But why do you want that the next development version would be something different than x.x.x+1-SNAPSHOT

I could ask the same question for the version to be released: if the current version is `x.x.x-SNAPSHOT`, why would you want to release something other than `x.x.x`? Yet the plugin still asks what version it should set 😉 .

OTOH, it would be convenient to ask for the next SNAPSHOT version (with a default set to `x.x.x+1-SNAPSHOT`). Developers can simply hit enter to select that default version, or specify a different version if they want to use `x.x+1.x` instead of `x.x.x+1`.

**Comment by aleksandr-m** [comment]
@bjansen It is not the same. The release version isn't known until the actual release is happening, so it has to be entered upon releasing.

> Developers can simply hit enter to select that default version

If someone is using `x.x+1.x` pattern for the next snapshot version then they're forced to type it every time on releasing. Much more convenient would be to configure which number will be incremented.

Just curious, how do you decide what next snapshot version will be? How often do you change next snapshot version pattern for the project?

**Comment by mireczatko** [comment]
from my point of view it could be nice feature. At least would be nice to fix it like when I enter different release version than default, next shapshot will continue from that(entered/released) version, not remain with incrementing default...

how to reproduce:
1. current develop branch snapshot is "0.1.0-SNAPSHOT"
2. running gitflow:release I enter "1.0.0" as desired release
3. now current master branch version is "1.0.0", OK
4. but now current develop branch version is "0.1.1-SNAPSHOT". I would expect version "1.0.1-SNAPSHOT" here

**Comment by aleksandr-m** [comment]
@mireczatko Well, it should be `1.0.1-SNAPSHOT`. Could you create a separate issue for that, so I don't forget about it.

As for the feature request at hand, same questions:
> Just curious, how do you decide what next snapshot version will be? How often do you change next snapshot version pattern for the project?

**Comment by mireczatko** [comment]
@aleksandr-m, I created new issue: https://github.com/aleksandr-m/gitflow-maven-plugin/issues/47

regarding your questions: yeah, to be honest, I found this problem developping my little private project where there is no release management at all. I just suddenly decided, this will be version 1.0.0 :smiley:

**Comment by danielborges93** [comment]
The implementation of [`DefaultVersionInfo`](https://maven.apache.org/maven-release/maven-release-manager/xref/org/apache/maven/shared/release/versions/DefaultVersionInfo.html) always [increment the last digit of the actual version](https://maven.apache.org/maven-release/maven-release-manager/xref/org/apache/maven/shared/release/versions/DefaultVersionInfo.html#L207). So it is not a "problem" of this plugin.

**Comment by jbadeau** [comment]
Our issues is this.

We tag our release like: releaseVersion=1.0.0-Final
The development branch is changed to 1.0.1-final-SNAPSHOT
We want: 1.0.1-SNAPSHOT

I have patched the required Mojos to accept an optional parameter called 'developmentVersion' to allow custom naming of the new development version.

Would you be interested in a pull request? Or you rather not introduce this feature?

**Comment by aleksandr-m** [comment]
@jbadeau Finally, some real use case. :) Another option is to introduce parameter which when set will remove qualifiers from version. Wdyt?

**Comment by jbadeau** [comment]
Would also work for us

**Comment by marandalucas** [comment]
@jbadeau I have the same problem. I would like to have that optiontional parameter 'developmentVersion'
Could you provide it? Thanks

**Comment by jbadeau** [comment]
@aleksandr-m  Do you have an ETA on a release? Can I help you in some way?

**Comment by aleksandr-m** [comment]
Here we go:

The `developmentVersion` in non interactive mode will set next development version.
```
mvn gitflow:release-finish -B -DdevelopmentVersion=3.0.0-SNAPSHOT
```

---

The `digitsOnlyDevVersion` when set will remove qualifiers from the release version.
E.g.
Release version: `1.0.0-Final` -> Development version: `1.0.1-SNAPSHOT`.

---

The `versionDigitToIncrement` adds ability to increment major/minor/whatever digit in the version.
E.g.
```
mvn gitflow:release-finish -DversionDigitToIncrement=1
```
Release version: `1.2.3.4` -> Development version: `1.3.0.0-SNAPSHOT`.

---

@jbadeau Of course. Pull, build, test. Feedback is welcome. :)

ETA on release? If no problem arises, then probably somewhere around this week.

**Comment by jbadeau** [comment]
Sounds great. :)
