### ISSUE TITLE
Default (or by config) delete feature and release branches on remote/origin during a `-release`

### ISSUE THREAD

**Issue by stevenpark** [aleksandr-m/gitflow-maven-plugin#44]
I'm not sure if this is expected behavior but I've noticed that during `-finish` for both feature and release phases that the plugin only deletes the respective branch locally but not on the remote.

It appears that `keepBranch` config only controls the behavior for local branches and `pushRemote` appears to be related to pushing the `develop` branch to the remote.

Is there another way to achieve this w/o manually doing a `git push origin --delete feature/feature-x`?

**Comment by aleksandr-m** [comment]
Currently, only the development and production branches are pushed to the remote. Hence there is no deleting feature/release branches from the remote.
Thanks for the info, this should be implemented along with the #32.

**Comment by stevenpark** [comment]
Ah, I see what you mean -- feature/release branches are not, by default, pushed to the remote (usually happens during the first commit then push). With #32, you'll make it a "thing" and close clean up during the `-finish` phase. Thanks!
