### ISSUE TITLE
Fails if local 'master' branch does not exist

### ISSUE THREAD

**Issue by agentgonzo** [aleksandr-m/gitflow-maven-plugin#45]
Working with Jenkins where we regularly have the workspace wiped out. When this happens, the Jenkins job will pull only the origin/develop branch to a local develop branch.

When running `release-start release-finish`, the plugin fails with the following error:
`[ERROR] Failed to execute goal com.amashchenko.maven.plugin:gitflow-maven-plugin:1.4.1:release-finish (default-cli) on project platform-parent: fatal: ambiguous argument 'master...origin/master': unknown revision or path not in the working tree.`

This is because there is no local master branch to merge to. 

Ideally the plugin would detect that there is no local `master` branch and create one based on `origin/master`.

We have to have a manual step to create the local master branch to work around this issue.

**Comment by aleksandr-m** [comment]
You mean [like this](https://github.com/aleksandr-m/gitflow-maven-plugin/commit/755bba3a4231f40108e4d3b811a7a311f7c3f661)? :) Use latest version.

**Comment by agentgonzo** [comment]
Sweet! Thank you!
