### ISSUE TITLE
*-start goals don't update version of child modules

### ISSUE THREAD

**Issue by arikkfir** [aleksandr-m/gitflow-maven-plugin#48]
When running a "-start" goal on a multi-module project (at the root), only the root's version is updated to the new release's version.

**Comment by arikkfir** [comment]
#49

**Comment by aleksandr-m** [comment]
Do you have different group id for the module projects? Can you show relevant parts of your projects pom xmls? Or create a MCVE?

**Comment by aleksandr-m** [comment]
@arikkfir ^ ping!

**Comment by tomcooperca** [comment]
One thing to note - `versions-maven-plugin` added the `<processAllModules>` property in version 2.5 of that plugin. I've used that in a mixed multi module project where a parent module is used to inherit an external parent POM and most of the modules don't inherit from the root POM. Looks like gitflow uses a hardcoded 2.1 version for the versions:set goal here https://github.com/aleksandr-m/gitflow-maven-plugin/blob/228ef8a69a52c0c897edc917ec301e6c17b93041/src/main/java/com/amashchenko/maven/plugin/gitflow/AbstractGitFlowMojo.java#L48 

Exposing that behavior via the gitflow might be a simpler solution.
