### ISSUE TITLE
Is it possible for releases branches always have the same name?

### ISSUE THREAD

**Issue by elmart** [aleksandr-m/gitflow-maven-plugin#5]
I see that it's possible to configure branch names/prefixes.
But it seems implied that, particularly, release branches will always be of the form `prefix + version`.
At my day job, release branch is always called the same way, with no version info. It gets created when starting a new release and deleted after that. There are never two releases in parallel, so that poses no problems.
So, can this plugin be configured somehow to achieve that workflow, and have release branch always being named the same?
If not, could you point me to the place in code where I should patch to achieve it?
I can explore code and find out on my own, but I'd be grateful if you saved me that time.
I would issue a PR with my patch in that case.

Thanks.

**Comment by aleksandr-m** [comment]
Currently it can't be configured.
Points of interest [GitFlowReleaseStartMojo](https://github.com/aleksandr-m/gitflow-maven-plugin/blob/master/src/main/java/com/amashchenko/maven/plugin/gitflow/GitFlowReleaseStartMojo.java#L91) and in `execute` method of [GitFlowReleaseFinishMojo](https://github.com/aleksandr-m/gitflow-maven-plugin/blob/master/src/main/java/com/amashchenko/maven/plugin/gitflow/GitFlowReleaseFinishMojo.java).

**Comment by aleksandr-m** [comment]
@elmart Any progress? Do you still need this?

**Comment by elmart** [comment]
Sorry, I didn't find the time to investigate more. Closing this by now. I'll reopen if/when I make advance on this. Thanks.

**Comment by aleksandr-m** [comment]
@elmart After few changes it became rather trivial to implement this. Could you clone, build/install and test with `1.1.1-SNAPSHOT`?

**Comment by aleksandr-m** [comment]
`1.2.0` version has been released. If something isn't working like expected please re-open this issue or create a new one.
