### ISSUE TITLE
Hotfix SNAPSHOT

### ISSUE THREAD

**Issue by jbadeau** [aleksandr-m/gitflow-maven-plugin#51]
Given master version 1.0.0
When I perform a hotfix I would expect my pom in the hotfix branch to have a SNAPSHOT qualifier.
Maybe i misunderstand something, or what is the reasoning behind this?

My issues is the same as this issue:
https://ecosystem.atlassian.net/browse/MJF-18

**Comment by aleksandr-m** [comment]
You can input SNAPSHOT version when prompted.

**Comment by jbadeau** [comment]
Ok, illl give that a go. Thanx

**Comment by jbadeau** [comment]
Do you have an ETA on a release? Can I help you in some way?
