### ISSUE TITLE
run custom goals

### ISSUE THREAD

**Issue by HonoluluHenk** [aleksandr-m/gitflow-maven-plugin#54]
We do have excessive enforcer (http://maven.apache.org/enforcer/maven-enforcer-plugin/) rules set up to prevent some errors (like allowSnapshots, but much more).
Also: integration tests do not run.

Our customers CI does not allow custom goals to be run, so we're basically stuck with mvn clean deploy and have to do our releases locally, then letting the CI build master.

Now what I'd like to do is (pseudo-code):
mvn -DskipTestProject=true gitflow:release-start clean verify mycoolgoal gitflow:release-finish
This command line actually does run but uses the SNAPSHOT version it started with, so enforcer does not see the release version and does not fail. Splitting this into two separate mvn commands works but is not very nice :(

What would be really cool is a configuration parameter that lets me set the goals during release:
Sample-command line:
mvn -DskipTestProject=true -DreleaseGoals=clean,verify,mycoolgoal gitflow:release
This might make skipTestProject obsolete since it could be replaced by -DreleaseGoals=
Also might make allowSnapshots obsolete since it could be replaced by using enforcer rule "requireReleaseDeps"

Implementing this might also solve #29 (mvn -DreleaseGoals clean,deploy gitflow:release-finish) and #13 (mvn -DreleaseGoals clean,install gitflow:release-finish)

**Comment by aleksandr-m** [comment]
@HonoluluHenk Take a look at [this commit](https://github.com/aleksandr-m/gitflow-maven-plugin/commit/1e26c36077e91398638ba7b625810d55dc48aad8) in the [feature/additional_goals](https://github.com/aleksandr-m/gitflow-maven-plugin/tree/feature/additional_goals) branch. Ideas and feedback are welcome.

**Comment by phuonghuynh** [comment]
@aleksandr-m how can i use this feature?

**Comment by aleksandr-m** [comment]
@phuonghuynh It isn't released yet. But you can checkout [feature/additional_goals](https://github.com/aleksandr-m/gitflow-maven-plugin/tree/feature/additional_goals), install and test it.

**Comment by phuonghuynh** [comment]
@aleksandr-m I tested the branch, waiting this feature in next release.

**Comment by aleksandr-m** [comment]
Implemented in 9e57bb0.

**Comment by aleksandr-m** [comment]
@HonoluluHenk @phuonghuynh `1.8.0` is released. See [Running custom Maven goals](https://github.com/aleksandr-m/gitflow-maven-plugin#running-custom-maven-goals).
