### ISSUE TITLE
settings/global settings file not propagated to mvn versions

### ISSUE THREAD

**Issue by ksraja** [aleksandr-m/gitflow-maven-plugin#55]
Ran this in a docker which has connectivity only to enterprise mvn repos/plugin repos.

mvn -B gitflow:release-start -DreleaseVersion=2.0.0 --global-settings enterprisesettings.xml -X

After it created a release branch, its trying to set the version using this below plugin. But it fails as its not using the settings file initially passed.

[DEBUG] mvn org.codehaus.mojo:versions-maven-plugin:2.1:set -DnewVersion=2.0.0 -DgenerateBackupPoms=false

[ERROR] [ERROR] Plugin org.codehaus.mojo:versions-maven-plugin:2.1 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.codehaus.mojo:versions-maven-plugin:jar:2.1: Could not transfer artifact org.codehaus.mojo:versions-maven-plugin:pom:2.1 from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org: Name does not resolve: Unknown host repo.maven.apache.org: Name does not resolve 

Error makes sense as we have no connectivity to outside, but that plugin is available in our enterprise repo which is defined in enterprisesettings.xml.

**Comment by aleksandr-m** [comment]
See https://github.com/aleksandr-m/gitflow-maven-plugin/issues/53
