### ISSUE TITLE
[FR] Provide option to set the starting point on release-start

### ISSUE THREAD

**Issue by oliveiragabriel07** [aleksandr-m/gitflow-maven-plugin#56]
Hello @aleksandr-m. Thanks for the plugin!

I'm using the plugin to create an automated delivery pipeline with Jenkins. I have configured a input in my job to create a release direct from pipeline after performing automated integration tests. I'd like to start a release branch from this, already tested, point (identified by the commit SHA1) and not from the top of develop.

Currently, is possible to achieve this by disabling fetchRemote and creating a local develop branch at the desired location, but it requires extra work. It would be nice if the plugin supported this through a release-start property. Something like the following:

`mvn -B gitflow:release-start -DInitialCommit=<SHA1>`

Would you consider including this feature?

**Comment by aleksandr-m** [comment]
Hello. Sounds good. What about merging back to develop? Does `release-finish` needs to be aware of this?

**Comment by oliveiragabriel07** [comment]
I don't think that the release-finish goal needs to be changed, because the release-start doesn't touch the develop branch. It's exactly the same as adding commits to the develop branch before the release is finished.
