### ISSUE TITLE
Auto merge conflict when release finish for pom version changes

### ISSUE THREAD

**Issue by ksraja** [aleksandr-m/gitflow-maven-plugin#57]
I have seen similar kind of issue reported for hotfix and its pretty straightforward to not to have a conflict when merging. 

This is what I'm doing, can someone tell me what i'm doing wrong?

develop> mvn -B gitflow:release-start -DreleaseVersion=2.0.0 -DpushRemote=true -DkeepBranch=true

release/2.0.0>  mvn gitflow:release-finish -DpushRemote=true -DkeepBranch=true

Finish step failed with following error
```
[ERROR] Failed to execute goal com.amashchenko.maven.plugin:gitflow-maven-plugin:1.6.0:release-finish (default-cli) on project xxxx: Auto-merging pom.xml
[ERROR] CONFLICT (content): Merge conflict in pom.xml
```

master> git diff
```
++<<<<<<< HEAD
 +    <version>1.0.2</version>
++=======
+     <version>2.0.0</version>
++>>>>>>> release/2.0.0
```

**Comment by aleksandr-m** [comment]
Does if fails every time when you release?

In the diff you've shown there is some space before ` +    <version>1.0.2</version>`. Is it copy-paste typo or it is really there? Maybe there is some invisible characters in version.

**Comment by ksraja** [comment]
this is the first time am evaluating this on one repo. I used the same branch and everytime it fails.
And the space in the question is a typo. Its very strange, as the version change is the only delta. 
Any suggestions?

**Comment by ksraja** [comment]
For some reason the develop and master where deviated. I rebased it and it fixed the problem. Thanks.
