### ISSUE TITLE
Update versions on the develop branch when starting a release

### ISSUE THREAD

**Issue by raehalme** [aleksandr-m/gitflow-maven-plugin#58]
When a new release is started, shouldn't all new development be done on the next version following the release? At the moment the new development version is set only after finishing the release. 

What do you think of adding an option to set the versions when starting a release? If enabled the release-start goal would first set and commit the release version, then create the release branch and finally set and commit the next development version on the develop branch.

For example when the develop branch has version 0.1-SNAPSHOT the process of starting the release would be something like this:

1. On the develop branch change version to 0.1
2. Commit the change 
3. Create a release branch from the previous commit
4. On the develop branch change version to 0.2-SNAPSHOT
5. Commit the change
6. Checkout the release branch

This kind of workflow would make it clear that a version is about to be released and the develop branch already focuses on the next version while avoiding merge conflicts related to changing version numbers in pom.xml files.

**Comment by raehalme** [comment]
Sent a PR #61

**Comment by raehalme** [comment]
The PR adds a new configuration option `commitDevelopmentVersionAtStart` which defaults to `false`. When set to `true` release-start and release-finish follow the steps outlined in the first comment.

**Comment by aleksandr-m** [comment]
Merged. Thanks.

**Comment by raehalme** [comment]
Do you have ideas when the next version might be released? Would be great to see this feature in a release :-)

**Comment by aleksandr-m** [comment]
@raehalme Next week, probably.

**Comment by aleksandr-m** [comment]
@raehalme `1.7.0` is out.

**Comment by raehalme** [comment]
Awesome, thanks!
