### ISSUE TITLE
releaseMergeFFOnly should not apply when the release branch is merged into develop

### ISSUE THREAD

**Issue by raehalme** [aleksandr-m/gitflow-maven-plugin#59]
When finishing a release, the configuration option `releaseMergeFFOnly` is also applied when merging the master into develop. I think the flag should only apply when merging the release branch into master as the develop branch may have progressed while preparing the release.

The purpose of `releaseMergeFFOnly` was to make sure that there are no modifications when promoting a release to production (ie. merging the release branch into master).

**Comment by raehalme** [comment]
Sent a PR #60.

**Comment by aleksandr-m** [comment]
PR merged. Thank you.

Do you want `1.6.1` to be released with this fix? Or can you wait for the `1.7.0`?

**Comment by raehalme** [comment]
No problem waiting for 1.7.0. Thanks!
