### ISSUE TITLE
Problem with multi-level project with multiple repos

### ISSUE THREAD

**Issue by robmoore** [aleksandr-m/gitflow-maven-plugin#6]
I have a project with a super POM project and a number of organizing projects which inherit from the super POM. These organizing projects in turn have a number of child projects which inherit from the POM defined from their parent. All of these projects (the super POM project, the organizing projects, and the leaf projects) live in their own git repos. I'd like to be able to run release-start on the projects independently but currently when I run it on the super POM project all  of the POMs that inherit from it are versioned to the same number. 

I looked at the code (in particular mvnSetVersions) and I don't see any explicit settings to cascade the version to the child projects but it appears this is how the versions plugin works by default (see http://www.mojohaus.org/versions-maven-plugin/plugin-info.html). It seems that this behavior is not configurable.

As it stands today, I would be happy with this behavior if it created a release branch for each repo but instead only the super POM project has a release branch created for it. In future, however, we intend to version these projects independently of each other so this approach wouldn't work for us in the long term. 

I suppose we could do something using the SCM plugin to revert any of these changes to the project before running the gitflow-maven-plugin on each subproject but I'd appreciate any input you might have on other strategies.

**Comment by aleksandr-m** [comment]
Need more info about your project structure. Does super POM and/or organizing project have modules defined? Can you illustrate it somehow? E.g. superPOM (modules:mod1) -> mod1 (parent: superPOM, modules: mod21) -> mod21 (parent: mod1).

**Comment by robmoore** [comment]
Sure -- the super POM has a profile which defines the organizing modules (mod1, mod2, etc). In turn each of these organizing POMs has modules defined for their child projects (mod11, mod21, etc). 

For example:
- super POM project [modules defined using profile]
- mod1 project (parent: super  POM) [modules defined at the project level]
-- mod11 project (parent: mod1)
-- mod12 project (parent: mod1)
-- etc 
- mod2 project (parent: super POM)  [modules defined at the project level]
-- mod 21 project (parent: mod2)
-- mod 22 project (parent: mod2)
-- etc

**Comment by robmoore** [comment]
The non-recursive option in Maven had no effect.

I experienced the same behavior when using the Maven versions plugin and was finally able to get it to leave the module POMs alone by running the following:

```mvn versions:set -DnewVersion=123 -DupdateMatchingVersions=false -DprocessParent=false```
and then was able to update the module POMs (eg, mod1) and the submodule POMs (eg, mod11) by running the following:

```
mvn versions:set -DnewVersion=123
# This is required to update the super POM version to the correct value
mvn versions:update-parent
```

**Comment by aleksandr-m** [comment]
If you have different version in module project then executing `mvn versions:set ...` on parent project won't change module version.

**Comment by robmoore** [comment]
Thanks, Alexsandr.

**Comment by aleksandr-m** [comment]
@robmoore So your problem is resolved? Can we close this issue?

**Comment by robmoore** [comment]
Yes. I should have done so myself.
