### ISSUE TITLE
Expose feature name as maven property

### ISSUE THREAD

**Issue by bissaias** [aleksandr-m/gitflow-maven-plugin#62]
Consider exposing feature name as a maven property so it can be used in commit messages. Then the developer may set something like:

```
<configuration>
    <commitMessages>
        <featureStartMessage>${featureName} is now in #Developing</featureStartMessage>
        <featureFinishMessage>${featureName} is now #Developed</featureFinishMessage>
    </commitMessages>
</configuration>
```

When pushing to Bitbucket, the syntax above will trigger Bitbucket's [Smart Commits](https://confluence.atlassian.com/bitbucketserver/using-smart-commits-in-bitbucket-server-802599018.html). This in combination with `pushRemote = true` and a `featureNamePattern` that matches that of JIRA issues, the developer can accomplish automated transitions of JIRA issues that follow the gitflow methodology.

BTW great work!

**Comment by aleksandr-m** [comment]
From the next release `@{featureName}` can be used.
