### ISSUE TITLE
Plugin Allows Releases of Projects with SNAPSHOT parent POMs

### ISSUE THREAD

**Issue by lorkpoin** [aleksandr-m/gitflow-maven-plugin#64]
**Expected behavior:**
If I attempt to release a project with the following lines in the pom.xml, I expect the release to fail along the same lines as if I had a SNAPSHOT dependency:

```
<parent>
      <groupId>com.mypackage.whatever</groupId>
      <artifactId>some-project</artifactId>
      <version>0.1-SNAPSHOT</version>
</parent>
```

Instead it seems to release with no problem. I can't imagine that this is a valid use case, but even if it is I would like to be able to enable this kind of checking with a config setting.

Version: 1.6.0

**Comment by LudovicPecquot** [comment]
Same problem with a multi-module project with dependency management.
The method com.amashchenko.maven.plugin.gitflow.AbstractGitFlowMojo#checkSnapshotDependencies
don't see the versions of dependencies (always null), so the allowSnapshots has no effects.

**Comment by Opa-** [comment]
Any update on this as this could lead to release unstable versions

**Comment by glianeric** [comment]
I've made a dirty fix to take care of this; I run with 'allowSnapshots', but I've added code to the plugin to execute enforcer's requirereleasedeps rule.   I'm not submitting a PR because it's a dirty change that suits my purpose for now, but in case you'd like to 'roll your own', that's the direction I chose to go in for now.

I think fixing up @aleksandr-m function is a better idea.

**Comment by user667** [comment]
Same issue, also with version `1.12.0`. According to the [documentation (Additional goal parameters)](https://github.com/aleksandr-m/gitflow-maven-plugin#additional-goal-parameters) the expected behavior would be different:

> All release goals have allowSnapshots parameter which controls whether SNAPSHOT dependencies are allowed. The default value is false (i.e. build fails if there SNAPSHOT dependency in project).

**Comment by aleksandr-m** [comment]
The `allowSnapshots` parameter checks **only dependencies**.

**Comment by glianeric** [comment]
It would be good to check the parent also.   The parent in my workflow dictates versions of dependencies, so the parent itself must not be permitted to be a SNAPSHOT.
As I've mentioned, I got around this by hacking in an enforcer run, but it was a quick/dirty solution that is inserted exactly where I need it in the workflow to prevent any releases with snapshots.

**Comment by kutsal** [comment]
@aleksandr-m we have it where parent holds all `<dependencyManagement>` for the multi-module project. If the managed dependency is a snapshot, the plugin allows release to happen.

Parent pom snippet:
```maven-pom
    <modules>
        <module>child1</module>
    </modules>

    <properties>
        <baz-lib.version>1.3.2-SNAPSHOT</baz-lib.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.foo.bar</groupId>
                <artifactId>baz-lib</artifactId>
                <version>${baz-lib.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

Module pom snippet:

```maven-pom
    <artifactId>child1</artifactId>

    <dependencies>
        <dependency>
            <groupId>org.foo.bar</groupId>
            <artifactId>baz-lib</artifactId>
        </dependency>
    </dependencies>
```

This should not be released at all.

**Comment by aleksandr-m** [comment]
@kutsal Which version you are using? If latest then please register a new issue, seems it is unrelated to this one.

**Comment by kutsal** [comment]
@aleksandr-m We're using `1.13.0`. I'm going to try with `1.14.0` and see if it happens with that version as well.

**Comment by gscokart** [comment]
I have similar issues with a simple project where the -SNAPSHOT version is defined in a properties, and the <version> tag is using that property.

**Comment by pisarenko** [comment]
Got the same issue with `1.14.0`.

**Comment by user667** [comment]
I could verify that version `1.14.0` solves our issue with SNAPSHOT versions in the dependency management section.
* Releases with `1.12.0` were only failing with direct SNAPSHOT dependencies
* Releases with `1.14.0` fail with direct SNAPSHOT dependencies and SNAPSHOTs in dependency managemet (even if defined in a property) (cc @kutsal )

This issue (parent pom SNAPSHOT) is still present in `1.14.0`.

**Comment by aleksandr-m** [comment]
Can someone create small test project demonstrating the case with SNAPSHOT in parent pom?

/cc @user667 @glianeric @pisarenko

**Comment by stefanseifert** [comment]
i've provided a PR which adds a check for SNAPSHOT version in parent POM (and also adds integration tests): #323

**Comment by aleksandr-m** [comment]
The `allowSnapshots` parameter now checks dependencies and parent project.
