### ISSUE TITLE
Allow branchName parameter to be set on the command line

### ISSUE THREAD

**Issue by Steve973** [aleksandr-m/gitflow-maven-plugin#65]
**User Story**:
As a member of CM personnel that maintains the code base configuration and repositories, I need to be able to set the release branch name on the command line so that I can set the release branch name to something other than the specified releaseVersion parameter.

**Information**:
If I set the releaseVersion property to 1.5.0_RC1, this results in a release branch name of <prefix>1.5.0_RC1.  But I might want to have a release branch that is only <prefix>1.5.0, and create multiple release candidates on that same branch, until the release is finalized.

**Acceptance Criteria**:
User can specify separate properties for releaseVersion and branchName on the command line when invoking the plugin release goals.

**Comment by Steve973** [comment]
It might be useful to broaden the scope of this ticket a bit so that a command-line user can override any of the default or pom-specified gitFlowConfig properties on invocation.

**Comment by aleksandr-m** [comment]
Have you seen [`sameBranchName` parameter](https://github.com/aleksandr-m/gitflow-maven-plugin/issues/5)?

**Comment by Steve973** [comment]
@aleksandr-m yes, but sameBranchName is a boolean, and you need to configure releaseBranchPrefix to be something meaningful in the plugin configuration section of the pom.  I have a workaround that uses the build-helper-maven-plugin and its parse-version goal.  My release profile includes a property:

`<releaseBranchName>${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}</releaseBranchName>`

And I configured the gitflow-maven-plugin to have the following property in `<gitFlowConfig>`: `<releaseBrnachPrefix>release/${releaseBranchName}</releaseBranchPrefix>`

While this works, it is a bit inconvenient.  It would be much easier to expose the various gitFlowConfig parameters to the command line.

**Comment by aleksandr-m** [comment]
Command line arguments doesn't map well to complex objects. Thoughts?

**Comment by emmanuel-coquelin** [comment]
From what I understand there is no need for a complex object. We just need a parameter which will specify the branch name to set when starting a release.

We have the same situation where our release branches are used to qualify Release Candidates which will then be turned into effective releases and deployed to production.

I've created a pull request illustrating what our need would be. Please note that the "branchName" parameter would superseed in this case the "sameBranchName" parameter but it could go the other way around, the point being that those two parameters won't work well together.

**Comment by Steve973** [comment]
I agree with the above comment. Separate command line parameters for the branch name, and possibly other config parameters, would be great.  Alternatively, pointing to a properties file or yaml to represent the config object would be a decent solution, as well.

**Comment by Steve973** [comment]
@aleksandr-m and @emmanuel-coquelin do either of you have any further thoughts on this?  I would not mind making an attempt at this and providing a pull request.

**Comment by aleksandr-m** [comment]
@Steve973 What exactly do you have in mind? There is already [Adds parameter "branchName" on the release-start goal ](https://github.com/aleksandr-m/gitflow-maven-plugin/pull/70) PR. Does it suit your needs?

**Comment by Steve973** [comment]
It probably does.  When this is released, and when I have some time to try it, I will try to reconfigure my pom.xml parameters and test out how it works.  Thanks for your help.

**Comment by aleksandr-m** [comment]
#70 merged.
