### ISSUE TITLE
Unable to do hotfix-finish

### ISSUE THREAD

**Issue by lshens** [aleksandr-m/gitflow-maven-plugin#68]
Hi,

I created a *hotfix* from my *support* branch **support/demo-1.3.0**. When I try to do a *mvn gitflow:hotfix-finish*, I get this error:

> [INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building demo 1.7.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- gitflow-maven-plugin:1.7.0:hotfix-finish (default-cli) @ demo ---
[INFO] Checking for uncommitted changes.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.820 s
[INFO] Finished at: 2017-09-12T16:23:22-03:00
[INFO] Final Memory: 17M/303M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.amashchenko.maven.plugin:gitflow-maven-plugin:1.7.0:hotfix-finish (default-cli) on project demo: There are no hotfix branches. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

My *pom.xml* configuration:

> 
> <plugin>
	<groupId>com.amashchenko.maven.plugin</groupId>
	<artifactId>gitflow-maven-plugin</artifactId>
	<version>1.7.0</version>
	<configuration>
		<verbose>true</verbose>
		<versionDigitToIncrement>1</versionDigitToIncrement>
		<pushRemote>true</pushRemote>
		
		<gitFlowConfig>
			<productionBranch>master</productionBranch>
			<developmentBranch>development</developmentBranch>
			<featureBranchPrefix>feature-${project.artifactId}-</featureBranchPrefix>
			<releaseBranchPrefix>release-${project.artifactId}-</releaseBranchPrefix>
			<hotfixBranchPrefix>hotfix-${project.artifactId}-</hotfixBranchPrefix>
			<versionTagPrefix>${project.artifactId}-</versionTagPrefix>
		</gitFlowConfig>
		<commitMessages>
			<featureFinishMessage>update versions for development branch [skip ci]</featureFinishMessage>
			<hotfixFinishMessage>update for next development version [skip ci]</hotfixFinishMessage>
			<releaseFinishMessage>update for next development version [skip ci]</releaseFinishMessage>
		</commitMessages>
	</configuration>
</plugin>

My *git branch* command result:

>   development
  hotfix-demo-support/demo-1.3.0/1.3.1-SNAPSHOT
  master
  support/demo-1.3.0

**Comment by aleksandr-m** [comment]
Try to conf branches names with ending `/` -> `hotfix-${project.artifactId}-/`.
Even if it works don't close this issue yet. I'll take a look if this can be improved.

**Comment by lshens** [comment]
I tried that, but still get the same problem. I also tried to change the *support* to *support-* in the configuration, but didn't work.

**Comment by aleksandr-m** [comment]
Adding `/` works for me. In which branch did you add it? You need to add to support branch and then start a hotfix.

Currently you have `hotfix-demo-support/demo-1.3.0/1.3.1-SNAPSHOT` as a support hotfix branch but it should be `hotfix-demo-/support/demo-1.3.0/1.3.1-SNAPSHOT`.

**Comment by lshens** [comment]
I deleted every branch create before and reapplied your solution; and works. I don't know what happened, but it is working now.

Thanks.

**Comment by aleksandr-m** [comment]
@jesramgue The fix isn't released yet. Wait for the next version.
