### ISSUE TITLE
Support `versionDigitToIncrement` or not update version for hotfix-finish

### ISSUE THREAD

**Issue by konraifen88** [aleksandr-m/gitflow-maven-plugin#69]
We have applied the `versionDigitToIncrement` to update always the minor version in the `pom.xml`. Everything works fine when doing releases. The version is correctly updated for develop branch. But when performing a hotfix-finish the defined name/version number is applied as master version (as it should be) and the develop version is updated wrong.

# Example

* master: 1.0.0
* develop: 1.1.0-SNAPSHOT

Starting new Hotfix with name hotfix/1.0.1

After `hotfix-finish` this results in:
* master: 1.0.1
* develop 1.0.2-SNAPSHOT

This should be changed to not apply a new version for develop branch or also apply the `versionDigitToIncrement` for the develop branch.

Edit: maybe this is already implemented in #63

**Comment by joan-miralles** [comment]
Yes, the problem you comment when you finish a hotfix is resolved here:

https://github.com/aleksandr-m/gitflow-maven-plugin/pull/63/files#diff-bffa9e595c1eab520a7abe29104f3ff7L212

**Comment by aleksandr-m** [comment]
Seems like this is resolved. Fill free to reopen if not.
