### ISSUE TITLE
Finishing release fails when build encounters log4j warnings when run in Jenkins

### ISSUE THREAD

**Issue by Steve973** [aleksandr-m/gitflow-maven-plugin#72]
I am not sure if I can reproduce this issue from a bash command line, but if I try to finish a release via Jenkins and the build encounters log4j warnings, the build fails during the build and test phase.

**Comment by Steve973** [comment]
Here is some more information.  My jenkins script invokes the plugin like this:
`mvn -B -e validate gitflow:release-start -Dverbose=false -DcommitDevelopmentVersionAtStart=true -DdigitsOnlyDevVersion=true -DpushRemote=true -DdevelopmentVersion=${DEV_VER} -DreleaseVersion=${REL_VER}_${RC_VER} -DsameBranchName=true -DallowSnapshots=true \
&& mvn -B -e validate gitflow:release-start -Dverbose=false -DcommitDevelopmentVersionAtStart=true -DdigitsOnlyDevVersion=true -DpushRemote=true -DkeepBranch=true -DdevelopmentVersion=${DEV_VER} -DreleaseVersion=${REL_VER}_${RC_VER} -DsameBranchName=true -DallowSnapshots=false`

When the release-finish goal fails, I get the following:
`[ERROR] Failed to execute goal com.amashchenko.maven.plugin:gitflow-maven-plugin:1.6.0:release-finish (default-cli) on project myproject: Picked up JAVA_TOOL_OPTIONS:
-Dmaven.ext.class.path="/local/tomcat/.jenkins/workspace/TEST-Release_Dev_Deploy_RC1@tmp/withMavend32d6172/pipeline-maven-spy.jar"
-Dorg.jenkinsci.plugins.pipeline.maven.reportsFolder="/local/tomcat/.jenkins/workspace/TEST-Release_Dev_Deploy_RC1@tmp/withMavend32d7162"`

Then it will list various warnings regarding loggers, including appenders not being found, or any other misconfiguration.  While I agree that these warnings are not ideal to have, should it be failing the build, or do you see something wrong with what I'm doing?

**Comment by aleksandr-m** [comment]
Do you have a stacktrace? In which step do you get this warnings?

Do you know that you can use `release` goal to release w/o separate branch in one go?

**Comment by aleksandr-m** [comment]
@Steve973 Ping.

**Comment by Steve973** [comment]
@aleksandr-m please forgive the delay in response.  I think that my error was, in fact, due to a problem with the structure of the project that I was releasing.  I have been using your plugin since then, and after fixing some problems with the project, I have not had the same problem again.

**Comment by aleksandr-m** [comment]
Very good. :) Closing then.
