### ISSUE TITLE
Enable non-interactive use of support-start

### ISSUE THREAD

**Issue by mkavanagh** [aleksandr-m/gitflow-maven-plugin#75]
It'd be useful to be able to supply the release number via a parameter to support-start, or (better for me) to pick the most recent release automatically if running in batch mode

**Comment by aleksandr-m** [comment]
Most recent by date? Version number?

**Comment by mkavanagh** [comment]
🤔 well, either would work for my case - what i'm looking to do is create a support branch every time i finish a release

**Comment by aleksandr-m** [comment]
Interesting. Out of curiosity: Why?

**Comment by mkavanagh** [comment]
it's one less thing to be done manually - i am happy to have the support branches sit around unused if we never need to use the hotfix workflow, but if we do then it saves a bit of process/documentation complexity to have the support branch ready

**Comment by mkavanagh** [comment]
thanks 👍
