### ISSUE TITLE
goal hotfix-finish fails in version 1.8.0

### ISSUE THREAD

**Issue by hfatela** [aleksandr-m/gitflow-maven-plugin#76]
I just run 

mvn com.amashchenko.maven.plugin:gitflow-maven-plugin:1.8.0:hotfix-finish -DpushRemote -Dverbose

and I got this error:

[DEBUG] === REACTOR BUILD PLAN ================================================
[DEBUG] Project: com.xxxxxxxxxxxxxxxxxxx:pom:2.6.4
[DEBUG] Tasks:   [clean, test, mx1024m]
[DEBUG] Style:   Regular
[DEBUG] -----------------------------------------------------------------------
[DEBUG] Project: com.xxxxxxxxxxxxxxxxxxxx:jar:2.6.4
[DEBUG] Tasks:   [clean, test, mx1024m]
[DEBUG] Style:   Regular
[DEBUG] -----------------------------------------------------------------------
[DEBUG] Project: com.xxxxxxxxxxxxxxxxxxxxxxxx:pom:2.6.4
[DEBUG] Tasks:   [clean, test, mx1024m]
[DEBUG] Style:   Regular
... 
[ERROR] Unknown lifecycle phase “mx1024m”. You must specify a valid lifecycle phase ...

If I use the previous version:

mvn com.amashchenko.maven.plugin:gitflow-maven-plugin:1.7.0:hotfix-finish -DpushRemote -Dverbose

It works just fine.

**Comment by aleksandr-m** [comment]
Do you use `preHotfixGoals` or `postHotfixGoals` or `argLine`? How?

**Comment by aleksandr-m** [comment]
@hfatela Ping.

**Comment by hfatela** [comment]
sorry for only come back to this now, I was relocated to another project, had to travel to the other side of the world and only return to my old duties this week. trying to catch up. I will try to replicate the error scenario and post some logs until the end of this week.

"Do you use preHotfixGoals or postHotfixGoals or argLine? How?"
I didn't use any options other than -DpushRemote -Dverbose

**Comment by hfatela** [comment]
sorry for the delay. 

I managed to replicate this error with the release goal also and got some logs for you. 
In this log I run the goal release 2 times, one with version 1.7.0 (lines 1 - 214) and another with 1.8.0 (214 - end).

As you can see it fails with version 1.8.0. 
[logs.txt](https://github.com/aleksandr-m/gitflow-maven-plugin/files/1638819/logs.txt)

The project is a very simple 3 module java hello-world, nothing special.

**Comment by hfatela** [comment]
I closed this ticket before I posted the reason why, sorry. the error was on our side, we use a company parent pom for all projects and someone a couple of years ago added this to the pom properties:

(...)
        <argLine>-Xmx1024m</argLine>
    </properties>

ya, fixed, sorry for the lost time. closed
