### ISSUE TITLE
Unable to execute "start hotfix" in batch mode

### ISSUE THREAD

**Issue by akoita** [aleksandr-m/gitflow-maven-plugin#77]
Hello,
I'm unable to execute "start hotfix" in batch mode. I have all the time the promt:
`What is the hotfix version? [1.1]:`

An with Jenkins it is the infinite loop:
`"What is the hotfix version? [1.1]: [INFO] The version is not valid."`

I've tried each of these options:

```
mvn -B gitflow:hotfix-start
mvn --batch-mode gitflow:hotfix-start
mvn -DnonInteractive=true gitflow:hotfix-start
```
I even set the value of the property "interactiveMode" to false in the settings.xml file.

And more strangely, I have no promt when using the goals "start release", "finish release".

Can you tell me what I'm missing?

Thanks

**Comment by aleksandr-m** [comment]
This feature was added just recently in [4159fff](https://github.com/aleksandr-m/gitflow-maven-plugin/commit/4159fff794c4621dbe8fab1facf43cb2c0bed767). You have to wait for the next release.

**Comment by akoita** [comment]
Indeed, I was investigating the problem on the master branch rather than on the  tag 1.8.0.

**Comment by aleksandr-m** [comment]
@akoita `1.9.0` is out.
