### ISSUE TITLE
Implementation of non-interactive mode in "hotfix-finish"

### ISSUE THREAD

**Issue by akoita** [aleksandr-m/gitflow-maven-plugin#79]
In the implementation of the "hotfix-finish" in non-interactive mode, why not make the parameter "hotfixVersion" facultative when there is only one hotfix branch?

**Comment by glianeri** [comment]
Submitted PR #193 for this.

**Comment by aekrylov** [comment]
I think many projects don't use multiple simultaneous hotfixes, in which case specifying hotfix branch only adds to the complexity. We ran into this after migrating from Atlassian's jgitflow plugin

**Comment by beatngu13** [comment]
I also wonder why `hotfixVersion` is mandatory for `hotfix-finish`, whereas `release-finish` can be invoked without supplying a version. If there is only one hotfix branch—as pointed out by @aekrylov, I also think the majority of projects doesn't use simultaneous hotfixes—the plugin could pick that branch. This would be super helpful for CI integration.

**Comment by aleksandr-m** [comment]
There is `hotfixBranch` parameter which can be used to specify full branch name to make it easier to finish hotfix in the ci environment.
