### ISSUE TITLE
Enable to customize commit messages

### ISSUE THREAD

**Issue by adko-pl** [aleksandr-m/gitflow-maven-plugin#8]
Currently the commit messages such as e.g. `updating for next development version` and `updating versions for release` are hardcoded inside the plugin. It would be great to have a configuration option allowing to customize them.

**Comment by aleksandr-m** [comment]
Good one. I'll see what I can do.

**Comment by adko-pl** [comment]
awesome work @aleksandr-m! thanks

**Comment by aleksandr-m** [comment]
@adko-pl 1.2.1 version is released with the ability to customize commit messages. [Readme updated.](https://github.com/aleksandr-m/gitflow-maven-plugin#customizing-commit-messages)

Thank you for contributing!
