### ISSUE TITLE
add the ability to mark a hotfix as SNASPHOT

### ISSUE THREAD

**Issue by wtoscer** [aleksandr-m/gitflow-maven-plugin#81]
and when hotfix:finish is launched, remove -SNAPSHOT from version

**Comment by aleksandr-m** [comment]
@wtoscer 
What about tag? Should it contain SNAPSHOT in it?

> remove -SNAPSHOT from version

You mean in production branch? Development still has the SNAPSHOT?

**Comment by wtoscer** [comment]
Actually, if I run hotfix:start and I put 1.0.1-SNAPSHOT for the version, when I run hotfix:finish , I have 1.0.1-SNAPSHOT in my pom.xml on master.
I just want to keep my hotfix in SNAPSHOT mode while I'm currently developing, but remove it when finishing the hotfix (and the tag don't have to contains snapshot)

**Comment by aleksandr-m** [comment]
@marcschiely Have you tested this PR? Does it works as you want it to?
@wtoscer

**Comment by marcschiely** [comment]
@aleksandr-m I just tested if the PR does fulfill our needs. Looks like this is exactly what we wanted. So from my side +1 for this PR.

**Comment by aleksandr-m** [comment]
@marcschiely Good. Merged.

**Comment by marcschiely** [comment]
@aleksandr-m What is your plan to build the next release that contains this issue?

**Comment by aleksandr-m** [comment]
@marcschiely I'll try to do a release in the next couple of weeks.

**Comment by aleksandr-m** [comment]
@wtoscer @marcschiely `1.10.0` is out.
