### ISSUE TITLE
Feature request : Username/Password configuration

### ISSUE THREAD

**Issue by Modzful** [aleksandr-m/gitflow-maven-plugin#82]
Something like :
```
<configuration>
      <username>MY_USER</username>
      <password>MY_PW</password>
</configuration>
```
Could be useful if you checkout with HTTPS instead of SSH with --batch-mode.

**Comment by aleksandr-m** [comment]
I believe there is no way to pass them to the underlying processes.
Not to mention that this is not secure.
Use [Credential Storage](https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage).

**Comment by frosiere** [comment]
Maybe I missed something but I don't really understand why it's not possible as the similar [jgit-flow plugin](https://bitbucket.org/atlassian/jgit-flow/wiki/goals.wiki#!usernamepassword-configuration) provided by Atlassian is able to do it.

It's effectively not secured to store a plain text password. In example, while using the plugin with Gitlab, it's possible to store the password in a secret variable to have something like this
`mvn -B gitflow:release -Dusername=gitlab_runner -Dpassword=${GITLAB_RUNNER_PASSWORD}`
Not perfect but it can be an alternative to the credential storage.

**Comment by aleksandr-m** [comment]
@frosiere This plugin uses [command line](https://github.com/aleksandr-m/gitflow-maven-plugin/blob/master/src/main/java/com/amashchenko/maven/plugin/gitflow/AbstractGitFlowMojo.java#L1037).
If you know how to pass username/password to the underlying processes, please share.

**Comment by aleksandr-m** [comment]
There is bunch of links over there on how to configure ci for push-ing. E.g. [Push files to gitlab-ci via CI runner](https://stackoverflow.com/questions/40122780/1700321) see `before_script` section. 
Or with `.netrc` file - [How to enter command with password for git pull?](https://stackoverflow.com/questions/11506124/1700321)
