### ISSUE TITLE
pass all profiles and multiple properties down to maven

### ISSUE THREAD

**Issue by hfreedman** [aleksandr-m/gitflow-maven-plugin#84]
The plugin seems to ignore all passed profiles when forking an underlying maven process

`mvn gitflow:release -PrestProfile,soapProfile` forks a process `mvn clean test` without passing those profiles.

There is an option `-DargLine=-PrestProfile,soapProfile` but it did not seem to help. 

As a workaround, I tried to have those profiles activated on a property and tried to pass them as 
`-DargLine="-Drest -Dsoap"` and that did not help neither. If I call `mvn clean test -Drest -Dsoap`  it works though.

**Comment by aleksandr-m** [comment]
`-DargLine=-PrestProfile,soapProfile` Works for me. With `-X` there is `mvn clean install -PrestProfile,soapProfile` in the console.

**Comment by hfreedman** [comment]
ok, when upgrading to latest version, it indeed works as expected. Thanks, Aleksandr.

**Comment by hfreedman** [comment]
//
