### ISSUE TITLE
Update release version in a file

### ISSUE THREAD

**Issue by arunkjn** [aleksandr-m/gitflow-maven-plugin#85]
Hi,

I have a use case in which I want to automatically update the release version in a configuration file before commit. Is there anyway it can be achieved through this plugin? Is it possible to pass the release version to a shell script?

**Comment by lrkwz** [comment]
It could be used to replace the release version in CHANGELOG.md as well.

* you are working on version 0.0.1-SNAPSHOT
* add your edits in `CHANGELOG.md` under a line like `# 0.0.1-SNAPSHOT`
* execute `mvn gitflow:release`
* automatically change `CHANGELOG.md`  replacing `0.0.1-SNAPSHOT` with `0.0.1` and a new empty section above that one with line `# 0.0.2-SNAPSHOT`

**Comment by cobaasta** [comment]
I wish the plugin would set the version in file package.json too, not only in pom.xml

**Comment by aleksandr-m** [comment]
Out of scope of this plugin. Probably can be achieved with filtering/replacing and using scm plugin to do commit.
