### ISSUE TITLE
Feature Request: Create goals to allow release, hotfix and feature on top of support branches

### ISSUE THREAD

**Issue by hfatela** [aleksandr-m/gitflow-maven-plugin#86]
I'm requesting something like:

support-release-start, support-release-finished
support-hotfix-start, support-hotfix-finished
support-feature-start, support-feature-finished

so I can do this:

https://gitversion.readthedocs.io/en/latest/git-branching-strategies/img/b035b8ca99bd34239518_support-hotfix.png

or this:

https://gitversion.readthedocs.io/en/latest/git-branching-strategies/img/2167fb1c4a5cf84edfd8_support-minor.png

**Comment by aleksandr-m** [comment]
Hotfix from `support` branch is already here - [add support for support branches](https://github.com/aleksandr-m/gitflow-maven-plugin/commit/919ba97d5f852eee0e52f5d62a0a44cb41c10d58).

Usually, new features are not added to support versions and hotfix serves as release in support.

**Comment by aleksandr-m** [comment]
Right.
