### ISSUE TITLE
gitflow:release-start hangs after "fetchRemote"

### ISSUE THREAD

**Issue by flod1** [aleksandr-m/gitflow-maven-plugin#89]
I start maven "gitflow:release-start"

after a sort time, it hangs on: "fetchRemote" 

I user windows 10, maven 3.5.0, java 1.8

**Comment by aleksandr-m** [comment]
Password protected repository? You need to install [Git Credential Manager for Windows](https://github.com/Microsoft/Git-Credential-Manager-for-Windows). It is included in [git installation package](https://git-scm.com/downloads), you just need to tick a checkbox.

**Comment by aleksandr-m** [comment]
@flod1 Have you resolved this?

**Comment by kekzpanda** [comment]
Same issue here. We were going to integrate the plugin into our TeamCity CI environment. The local tests worked but once it runs in a TeamCity build configuration, the goal "release-start" gets stuck at "fetchRemote". Is there any known workaround?

**Comment by kekzpanda** [comment]
I solved this with SSH key authentication. If you are a TeamCity user and end up here:

- enable SSH key authentication in your repo server (we use BitBucket) and upload a key for your release git user
- upload the private key to TeamCity: project configuration -> SSH Keys
- in your TeamCity build configuration vcs root insert the ssh urls for pushing and fetching:
ssh://git_user@my.git.server/repo/myproject.git (important for BitBucket: this is similar to the HTTPS-path BUT the default "/scm" part of the URL for HTTPS must be excluded - this is not document)
- set "Uploaded Key" as authentication method in vcs root (becomes available when the fetch URL uses ssh)
- additionally: set up the build feature "SSH Agent" for your build and set it up with the private key as well

I guess any similar authentication issue can be solved with an SSH agent.

**Comment by aleksandr-m** [comment]
@kekzpanda Good you've solved it. :) Thank you for contributing.
