### ISSUE TITLE
version management in properties

### ISSUE THREAD

**Issue by KimJejun** [aleksandr-m/gitflow-maven-plugin#9]
Hi there.

My project using maven multiple modules and manage version in properties attribute.
This maven plug-in cannot support version properties
<version>${project.version}</version>

Can u update module can support properties?

**Comment by aleksandr-m** [comment]
Can you share relevant configuration of your project. I'm using it for multi module project and it is working fine.

**Comment by aleksandr-m** [comment]
@KimJejun ping.

**Comment by aleksandr-m** [comment]
Feel free to reopen it if you have additional details.
