### ISSUE TITLE
How can i update submodules versions

### ISSUE THREAD

**Issue by flod1** [aleksandr-m/gitflow-maven-plugin#90]
If there no Paramater for "autoVersionSubmodules" ?
example
mvn release:update-versions -DautoVersionSubmodules=true

**Comment by aleksandr-m** [comment]
It should work in most cases out of the box. What is your project structure?

**Comment by flod1** [comment]
pom
- submodules1
- submodules2
....

**Comment by aleksandr-m** [comment]
Do they have different parent? Different groupId?

**Comment by aleksandr-m** [comment]
Seems like duplicate of #48. If not, feel free to reopen with more info.
