### ISSUE TITLE
Message "Release branch already exists" with mvn gitflow:release in Jenkins 

### ISSUE THREAD

**Issue by bigloupe** [aleksandr-m/gitflow-maven-plugin#91]
Your plugin works wondefully well in command line.

mvn gitflow:release

where i've got a question

What is release version? [0.2.5]:

But in Jenkins, i've got a message "Release branch already exists"
How can i use in Jenkinsfile your plugin to precise release version ?
I thought i can be taken from pom.xml

Thanks

**Comment by bigloupe** [comment]
I forgot to precise that I launch mvn in batch mode (mvn -B gitflow:release)

**Comment by bigloupe** [comment]
I found the git command provoking the issue in Jenkins :

 git for-each-ref --count=1 refs/heads/release/*

and result 
068e8da348a084d604d0eeb56310ed75598d7533 commit refs/heads/release/0.2.4

therefore in command line : 

 git for-each-ref --count=1 refs/heads/release/*

return nothing

Jenkinsfile works with jgit flow. (https://bitbucket.org/atlassian/jgit-flow)

**Comment by bigloupe** [comment]
I found. A file scm-revision-hash.xml in jenkins dir forced a specific commit hash.

**Comment by aleksandr-m** [comment]
Unrelated. You can use `releaseVersion` parameter to set release version in non-interactive mode.
