### ISSUE TITLE
Changelog generation

### ISSUE THREAD

**Issue by hypery2k** [aleksandr-m/gitflow-maven-plugin#92]
Is it somehow planned to include the possibility to add scripts, e.g. for changeling generation within the release?

**Comment by aleksandr-m** [comment]
You can run Maven goals with `preReleaseGoals` and `postReleaseGoals` parameters in the `release-finish` and `release` goals.

**Comment by aleksandr-m** [comment]
@hypery2k Have you tried above parameters?

**Comment by hypery2k** [comment]
yes, this basically works. Thanks
