### ISSUE TITLE
Goal for change snapshot to build-number

### ISSUE THREAD

**Issue by rodrigongarcia** [aleksandr-m/gitflow-maven-plugin#95]
I was begin use this plugin for replace maven-jgitflow-plugin
Now i need this goal usesfull for change pom in CI,
Description: Updates the pom versions in the current branch by adding a build number label: "-buildX" where X is a provided number It does NOT commit the changes and is basically used in a CI task to ensure you can deploy unique non-SNAPSHOT version for every build.

this will be posible?

Gretings
pd.: i can solve ussing other plugin: `mvn build-helper:parse-version versions:set -DbuildNumber=${BUILD_NUMBER} '-DnewVersion=${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}-build${buildNumber}' -DgenerateBackupPoms=false`

**Comment by aleksandr-m** [comment]
You mean like new separate goal? How it is related to git flows? What is your workflow where you use such goal?

BTW this plugin uses `versions` plugin to update pom.
