### ISSUE TITLE
Can't enter ssh key password

### ISSUE THREAD

**Issue by ejlindahl** [aleksandr-m/gitflow-maven-plugin#96]
I've been using jgitflow (https://bitbucket.org/atlassian/jgit-flow which I guess has the same origin as this?). Whenever jgitflow had to use my ssh key it prompted for the password of the ssh key. As far as I can see this does note happen with this aleksandr-m/gitflow-maven-plugin? Solved it by creating an ssh key with no password protection. But I'd rather have my ssh key protected, so what I would like to see is the possibility to use password protected ssh keys. 

My apologies if this is already possible; please give me a link to the documentation, because I couldn't find it.

(Running jgitflow in Windows cmd inside IntelliJ IDEA)

**Comment by aleksandr-m** [comment]
What do you mean by *the same origin*? :)

Which ssh-agent you are using?

**Comment by ejlindahl** [comment]
Sorry about "the origin"; somehow I had got the impression that this project was a continuation of jgitflow which atlassian no longer is developing. You shouldn't trust everything you can read on the Internet, I guess  :-)

I'm not using an ssh-agent. I'm developing on windows, created my ssh key with ssh-keygen in a Git bash-window and added the public key to our local Gitlab. Then, when running jgitflow in the terminal (which is a windows cmd-window) inside IDEA, I was prompted for the password. As far as I know there is no ssh-agent available in windows cmd so that was very convenient. And for different reasons I'm kind of stuck to this "cmd-inside-IDEA", that's why I'm asking

**Comment by aleksandr-m** [comment]
This plugin runs commands from the command line. AFAIK you can't get prompt and pass info back to it in that way. And typing password into the console isn't secure anyway. :)

What you can try is to install some ssh-agent and configure it. There is some included in the git installer. The point is to make prompt for passphrase from some helper program as with passwords and [Git Credential Manager for Windows](https://github.com/Microsoft/Git-Credential-Manager-for-Windows).

**Comment by ejlindahl** [comment]
OK. Thanks, I'll check out the Credential Manager for Windows.

**Comment by aleksandr-m** [comment]
@ejlindahl Credential manager should work only for password protected repositories, not ssh keys. For ssh try to use ssh-agent. Google for git ssh-agent passphrase.

If you will find a solution and have some spare time, can you write here what did you do to handle this. It would be good reference for future users with similar issue. Thanks.
