### ISSUE TITLE
maven version issue when merging release back to develop branch

### ISSUE THREAD

**Issue by igrapp** [aleksandr-m/gitflow-maven-plugin#97]
Hi,  here is the use case I am struggling with:

1. Work in develop branch with maven version set to 1.0-SNAPSHOT - finish story or two. Commit/push  into develop.
2.  run gitflow-start-release - create release branch releases/1.0 , maven version set to "1.0" - everything is great so far. 
3.  do release hardening in releases/1.0 - fix bug or two, commit/push into releases/1.0 - everything is great so far.
4.  In parallel other developers work in develop branch on some stories
5.   now comes an issue - I would like to merge my bug fixes from release/1.0 into develop branch, but this will implicitly set  maven  version in develop to "1.0". 

So here come an enhancement proposition - should giflow-maven-plugin have "gitflow-branch-merge" goal, that would do the merging between branches but preserve maven version until "release-finish" ( or other "*-finish" is executed ?

There could be other simpler ways to do this, but I fail to see it at this point.

thank you.
Igor.

**Comment by raehalme** [comment]
If I understood you correctly I had a similar problem and introduced the configuration option `commitDevelopmentVersionAtStart` to fix the issue. Enabling the option causes the plugin to update the version when starting a release like this:

1. In develop change the version to 1.0 (removing the "-SNAPSHOT").
2. Create a release branch releases/1.0
3. In develop change the version to 1.1-SNAPSHOT

This ensures there is no conflict regarding version in pom.xml, and you can now do changes in the release branch and easily merge them back to the develop branch. The plugin also takes care of automatically merging the changes, if any, when finally finishing the release.

**Comment by aleksandr-m** [comment]
Why not to use `git merge`? Otherwise what Thomas said. Or maybe you should use `hotfix` goals to introduce bug fixes to release and to develop branches.
