### ISSUE TITLE
Override merge commit message

### ISSUE THREAD

**Issue by yodamad** [aleksandr-m/gitflow-maven-plugin#99]
Hi,

I need to override merge commit message to fit the pre-commit hook that check that the message is correctly formatted. I didn't find the right parameter to do so.

Is it possible ?

Here is an example of message I'd like to override : `Merge branch 'release/3.3.0' into dev`

Thank you

**Comment by aleksandr-m** [comment]
What message do you want to have in merge commits? Which variables do you need there, if any?

**Comment by yodamad** [comment]
In fact i pushed a PR to correct this (#100)

**Comment by aleksandr-m** [comment]
In that way you won't be able to use branch name and other variables in the merge message.

**Comment by yodamad** [comment]
What kind of variables ? because i've tested with maven variable such as project.version, and it worked correctly

**Comment by aleksandr-m** [comment]
Git branch name. Read my questions again and answer them.

`project.version` is not updated version in that case.

Also all merges will have that message.

**Comment by yodamad** [comment]
Ok forget about it.
I've fixed what i need in my fork

**Comment by aleksandr-m** [comment]
@yodamad If you ever finish this with git variables and different messages, then feel free to re-open.
